### ISSUE TITLE
When the window position moves, the position of the popup control does not follow

### ISSUE THREAD

**Issue by Gaoyifei1011** [microsoft/microsoft-ui-xaml#10443]
### Describe the bug

dsd

### Steps to reproduce the bug

dd

### Expected behavior

dd

### Screenshots

dd

### NuGet package version

None

**Comment by kmgallahan** [comment]
Dupe and resolved in the 1.7 release.

**Comment by Gaoyifei1011** [comment]
> Dupe and resolved in the 1.7 release.

However, I tested it in the official version 1.7 yesterday and found that it wasn't fixed.

**Comment by snigdha011997** [comment]
Hi @Gaoyifei1011, can you please us by providing minimal repro project for further investigation?

**Comment by ayushjai30** [comment]
Hi @Gaoyifei1011, the attached video is not visible.

**Comment by Gaoyifei1011** [comment]
> Hi [@Gaoyifei1011](https://github.com/Gaoyifei1011), the attached video is not visible.

I can still watch the video here
![Image](https://github.com/user-attachments/assets/fa2b6ce4-4d25-44f5-83c1-8af3b1559559)
