### ISSUE TITLE
__CxxFrameHandler4 API is causing Microsoft Store certification failure, thus blocking all app store updates

### ISSUE THREAD

**Issue by dpaulino** [microsoft/microsoft-ui-xaml#1446]
**Describe the bug**

All UWP apps submitted to the Microsoft Store must pass certification. There seems to be a bug in the WinUI library that is causing all UWP apps that use WinUI to fail Store certification due to an unsupported API. Here is a certification report that I received from the Store team (and I also reproduced this report locally on my machine using the Windows App Certification Kit):
![image](https://user-images.githubusercontent.com/7649589/66801191-0e789280-eecd-11e9-80dc-60ad94ade3a4.png)

**Steps to reproduce the bug**

0. Ensure you are logged into VS2019 with a Microsoft Account that has UWP apps available in the Windows Developer Dashboard (https://partner.microsoft.com/en-us/dashboard/windows/overview).
1. Download this repo and launch the solution in VS2019: https://github.com/dpaulino/winui-unsupported-api
2. In solution explorer, right click on the project name `UnsupportedApiTest (Universal Windows)`
3. Select publish > create app package
4. Now we just need Visual Studio to create a signed package. So when the app package wizard pops up, select the option to associate the project with a Microsoft Store app. Select any app (it doesn't matter which app since we are not going to upload the package). 
![image](https://user-images.githubusercontent.com/7649589/66801444-f0f7f880-eecd-11e9-9f0a-f243725835d0.png)
5. Leave the defaults on this screen:
![image](https://user-images.githubusercontent.com/7649589/66801460-fd7c5100-eecd-11e9-9e55-144caef4b223.png)
6. Click create.
7. After the package is created, Visual Studio will launch a pop up window asking you if you want to launch the app certification kit. Click launch.
8. In the app cert kit, follow instructions to run the kit. 
9. Eventually, the kit should result in a failure:
![image](https://user-images.githubusercontent.com/7649589/66801514-30264980-eece-11e9-9185-01389f5a6d35.png)
10. This should be one of them:
![image](https://user-images.githubusercontent.com/7649589/66801550-4f24db80-eece-11e9-8ba3-86f9af77f747.png)

**Expected behavior**

There should be no error related to unsupported APIs

**Screenshots**

See above

**Version Info**

NuGet package version: 

2.3.191007001-prerelease

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2019 Update (18362)            | Yes   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
2.3.190910001-prerelease **does not** have this same problem.

**Comment by dpaulino** [comment]
@jevansaks when you marked this as `needs: follow-up`, do you need anything from me?

**Comment by jevansaks** [comment]
> @jevansaks Jevan Saks FTE when you marked this as `needs: follow-up`, do you need anything from me?

That's for me, thanks!

I was following up with the WACK team and they told me that this is a regression that the Store is hoping to fix this week. Hopefully you can just use the older WinUI version while you wait? I don't know if it's worth releasing a nuget package with a workaround if it should be fixed that soon.

**Comment by dpaulino** [comment]
No, don't worry about releasing another package with a workaround since this issue is only affecting the prerelease package.

Is there somewhere I can track the progress of that WACK bug?

**Comment by jevansaks** [comment]
Let's just use this issue -- I'll post back here when I hear that it's fixed.

**Comment by dpaulino** [comment]
Sounds good. I appreciate your help with this.

**Comment by jevansaks** [comment]
This issue should be resolved now. Can you try re-submitting to the store?

**Comment by dpaulino** [comment]
Thank you for the update! I'll try re-submitting today or tomorrow

**Comment by jevansaks** [comment]
Oh and just to clarify, the locally run WACK will continue to fail until the fix is incorporated into the Insider SDK. But the store submissions should be unblocked.

**Comment by hippieZhou** [comment]
@dpaulino ,I still have this issue when updated.

![Snipaste_2019-11-26_11-10-16](https://user-images.githubusercontent.com/13598361/69596459-9d84d880-103d-11ea-9247-954ae4dc5371.png)

![Snipaste_2019-11-26_11-08-31](https://user-images.githubusercontent.com/13598361/69596465-9fe73280-103d-11ea-9efe-0b1791b725b3.png)

**Comment by dpaulino** [comment]
@hippieZhou Are you seeing the error in the local Windows App Certification Kit (WACK) tool or are you seeing the error from the Dev Centre Portal after submitting your app package?

If you are seeing the error in the local WACK tool, then you can ignore the error. The WACK tool does not have the bugfix, but the Dev Centre Portal DOES have the bugfix.

**Comment by hippieZhou** [comment]
@dpaoliello ,thanks for your help. I'm trying to submit it to the Dev Center.

**Comment by solomonfried** [comment]
This still fails in the WACK 10.0.18362.1
Is there a fix in the works? Has a new version of the SDK been released or announced?

**Comment by jevansaks** [comment]
I think the fix is only in the insider SDK, not the 18362 SDK. Sorry, I don't have any more info at the moment. Is this blocking your CI pipelines or store submissions?

**Comment by solomonfried** [comment]
> I think the fix is only in the insider SDK, not the 18362 SDK. Sorry, I don't have any more info at the moment. Is this blocking your CI pipelines or store submissions?

This is not a block. Just a bit unnerving to always see the "Failed" message and then having to look at the report to make sure that the failure is not this issue.

Thanks

**Comment by solomonfried** [comment]
Just wondering, This issue has been open since late 2019. There have been several updates to VS2019 since then but the WACK is still at 10.0.18362.1
Will there ever be an update to get rid of the false "Fail" report?

**Comment by ranjeshj** [comment]
@MikeHillberg @Austin-Lamb do you know the answer or can you route @solomonfried 's  question ?

**Comment by KevinLaMS** [comment]
Greetings  @solomonfried
Sorry about the delay.  This has been fixed in the latest Windows App Certification Kit that will ship in the next Windows SDK.  We have also updated the test already in the Windows Store.  So your store submission will not fail due to this API.
Sorry for the inconvenience.

Kevin

**Comment by DiverseTGM** [comment]
![image](https://user-images.githubusercontent.com/63060694/81495370-c5908d00-92a7-11ea-9a0e-ef8c77d05770.png)

Im getting this error still.

**Comment by mc0re** [comment]
How can I submit to the store if WACK failed? There is no "Submit" button on it...

**Comment by grork** [comment]
If you build the package for store upload, you can skip running the WACK tests, and then just submit the `.appxupload` to the store through the store dashboard (https://partner.microsoft.com/en-us/dashboard/windows/overview)

**Comment by DevEddy** [comment]
I still get this error, any updates? 
Any updates on this?

@DiverseTGM have you resolved the issue?

-- Eddy

**Comment by ShaneOss** [comment]
I'm also seeing the issue. Seems it's been around for about a year now. Any ETA on fix for WACK tool? So workaround is build without certifying and upload package manually to dev portal?
Also seeing another false positive of... Error Found: The high OS version validation detected the following errors:
        Task failed to enable HighVersionLie.

**Comment by ranjeshj** [comment]
@KevinLaMS FYI
