### ISSUE TITLE
Unhandled exception with TreeViewItem IsSelected

### ISSUE THREAD

**Issue by michael-hawker** [microsoft/microsoft-ui-xaml#2303]
**Describe the bug**
In a certain scenario, I'm getting an unhandled exception from within MUX that takes down the app/managed debugger when trying to set a `TreeViewItem.IsSelected` to `true`.

**Steps to reproduce the bug**
1. Clone this project: https://github.com/michael-hawker/XmlSyntaxVisualizerUWP
2. Turn on mixed managed/native debugging
3. Run the project
4. Once the editor in the top-left loads, immediate select-all the text and paste in this snippet:
```xml
<xml>
  <sometag>
    <innertag attribute="something"/>
    <partial
  </sometag>
</xml>
```
5. Get an unhandled exception from [MainPage.xaml.cs line 235](https://github.com/michael-hawker/XmlSyntaxVisualizerUWP/blob/master/MainPage.xaml.cs#L235) (container.IsSelected = true where container is a TreeViewItem):
```
Unhandled exception at 0x75C9C28B (ucrtbase.dll) in XmlSyntaxVisualizerUwp.exe: Fatal program exit requested. occurred
```
(full stack below)

_Ensuring on UI Thread in the Dispatcher makes no difference here._

**Expected behavior**
Not crash. If only doing managed debugging this just kills the app instantly, no triggers in the debugger.

**Version Info**

NuGet package version: **2.4.0-prerelease.200322001**

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (19608)              | Yes  |
| November 2019 Update (18363)  |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 | Yes  |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**
I'm wondering if this is some issue between selection and expansion? As I don't see the tree expanded yet at the point where I ask the item to be selected? But that's a shot in the dark. It does appear that the tree has the new nodes when this issue hits, I tried dispatching the call to scroll itself after I update the nodes collection via binding, but that made no difference.

Full stack:
```
 	ucrtbase.dll!_abort()	Unknown
 	ucrtbase.dll!__purecall()	Unknown
 	ucrtbase.dll!__crt_state_management::wrapped_invoke<int (*)(void),int>(int (*)(void))	Unknown
 	Windows.UI.Xaml.dll!ctl::WeakReferenceSourceNoThreadId::CreateTrackerHandle(TrackerHandle__ * * returnValue) Line 1070	C++
 	Windows.UI.Xaml.dll!ctl::interface_forwarder<ITrackerOwner,DirectUI::DependencyObject>::CreateTrackerHandle(TrackerHandle__ * * returnValue) Line 95	C++
 	Microsoft.UI.Xaml.dll!ITrackerHandleManager::NewTrackerHandle(TrackerHandle__ * & handle) Line 26	C++
 	Microsoft.UI.Xaml.dll!tracker_ref<winrt::Windows::UI::Xaml::Window,0,IUnknown *>::set(const winrt::Windows::UI::Xaml::Window & value) Line 239	C++
 	Microsoft.UI.Xaml.dll!tracker_ref<winrt::Windows::UI::Xaml::UIElement,0,IUnknown *>::tracker_ref<winrt::Windows::UI::Xaml::UIElement,0,IUnknown *>(const tracker_ref<winrt::Windows::UI::Xaml::UIElement,0,IUnknown *> & other) Line 368	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>::{ctor}(const std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>> &) Line 710	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!std::_Default_allocator_traits<std::allocator<std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *>>>::construct(std::allocator<std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *>> &) Line 670	C++
 	Microsoft.UI.Xaml.dll!std::_Tree_temp_node<std::allocator<std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *>>>::_Tree_temp_node<std::allocator<std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *>>><std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>> &>(std::allocator<std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *>> & _Al_, std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>>,void *> * _Myhead, std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::Collections::VectorChangedEventHandler<winrt::Windows::Foundation::IInspectable>,0,IUnknown *>> & <_Vals_0>) Line 807	C++
 	Microsoft.UI.Xaml.dll!std::_Tree<std::_Tmap_traits<__int64,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>,std::less<__int64>,std::allocator<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>>,0>>::_Emplace_hint<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>> &>(std::_Tree_node<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>,void *> * const _Hint, std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>> & <_Vals_0>) Line 1112	C++
 	Microsoft.UI.Xaml.dll!std::_Tree<std::_Tmap_traits<__int64,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>,std::less<__int64>,std::allocator<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>>,0>>::insert<std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>>>>>(std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>>>> _First, std::_Tree_iterator<std::_Tree_val<std::_Tree_simple_types<std::pair<__int64 const ,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::Foundation::Collections::IVectorChangedEventArgs>,0,IUnknown *>>>>> _Last) Line 1373	C++
 	Microsoft.UI.Xaml.dll!event_base<event_source<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::UI::Xaml::DependencyPropertyChangedEventArgs>>,winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::UI::Xaml::DependencyPropertyChangedEventArgs>,tracker_ref<winrt::Windows::Foundation::TypedEventHandler<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode,winrt::Windows::UI::Xaml::DependencyPropertyChangedEventArgs>,0,IUnknown *>>::remove(const winrt::event_token token) Line 64	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!TreeViewNode::ChildrenChanged(winrt::event_token) Line 137	C++
 	Microsoft.UI.Xaml.dll!ViewModel::UpdateNodeSelection(const winrt::Microsoft::UI::Xaml::Controls::TreeViewNode & selectNode, const TreeViewNode::TreeNodeSelectionState & selectionState) Line 702	C++
 	Microsoft.UI.Xaml.dll!ViewModel::UpdateSelection(const winrt::Microsoft::UI::Xaml::Controls::TreeViewNode & selectNode, const TreeViewNode::TreeNodeSelectionState & selectionState) Line 715	C++
 	Microsoft.UI.Xaml.dll!SelectedTreeNodeVector::UpdateSelection(const winrt::Microsoft::UI::Xaml::Controls::TreeViewNode & node, TreeViewNode::TreeNodeSelectionState state) Line 39	C++
 	Microsoft.UI.Xaml.dll!SelectedTreeNodeVector::RemoveAt(unsigned int index) Line 76	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!SelectedTreeNodeVector::RemoveAtEnd() Line 80	C++
 	Microsoft.UI.Xaml.dll!SelectedTreeNodeVector::Clear() Line 98	C++
 	Microsoft.UI.Xaml.dll!winrt::impl::produce<SelectedTreeNodeVector,winrt::Windows::Foundation::Collections::IVector<winrt::Microsoft::UI::Xaml::Controls::TreeViewNode>>::Clear() Line 609	C++
 	Microsoft.UI.Xaml.dll!winrt::impl::consume_Windows_Foundation_Collections_IVector<winrt::Windows::Foundation::Collections::IVector<winrt::Windows::UI::Xaml::UIElement>,winrt::Windows::UI::Xaml::UIElement>::Clear() Line 236	C++
 	Microsoft.UI.Xaml.dll!TreeView::UpdateSelection(const winrt::Microsoft::UI::Xaml::Controls::TreeViewNode & node, bool isSelected) Line 140	C++
 	Microsoft.UI.Xaml.dll!TreeViewItem::UpdateSelection(bool isSelected) Line 441	C++
 	Microsoft.UI.Xaml.dll!TreeViewItem::OnIsSelectedChanged(const winrt::Windows::UI::Xaml::DependencyObject & __formal, const winrt::Windows::UI::Xaml::DependencyProperty & args) Line 473	C++
 	[Inline Frame] Microsoft.UI.Xaml.dll!winrt::Windows::UI::Xaml::Input::TappedEventHandler::<lambda_23e0ea00c94f958fd4ddf01adfb048e6>::operator()(const winrt::Windows::Foundation::IInspectable &) Line 4229	C++
 	Microsoft.UI.Xaml.dll!winrt::impl::delegate<winrt::Windows::UI::Xaml::Input::TappedEventHandler,<lambda_23e0ea00c94f958fd4ddf01adfb048e6>>::Invoke(void * sender, void * e) Line 1482	C++
 	Windows.UI.Xaml.dll!DirectUI::CEventSourceBase<DirectUI::IUntypedEventSource,Windows::UI::Xaml::IDependencyPropertyChangedCallback,Windows::UI::Xaml::IDependencyObject,Windows::UI::Xaml::IDependencyProperty>::Raise(Windows::UI::Xaml::IDependencyObject * pSource, Windows::UI::Xaml::IDependencyProperty * pArgs) Line 275	C++
 	Windows.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(const PropertyChangedParams & args) Line 2372	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::DependencyObject::NotifyPropertyChanged(CDependencyObject *) Line 2763	C++
 	[Inline Frame] Windows.UI.Xaml.dll!CFxCallbacks::DependencyObject_NotifyPropertyChanged(CDependencyObject *) Line 698	C++
 	[Inline Frame] Windows.UI.Xaml.dll!CDependencyObject::NotifyPropertyChanged(const PropertyChangedParams &) Line 2833	C++
 	Windows.UI.Xaml.dll!CDependencyObject::SetEffectiveValue(const CDependencyObject::EffectiveValueParams & args) Line 1698	C++
 	Windows.UI.Xaml.dll!CDependencyObject::UpdateEffectiveValue(const CDependencyObject::UpdateEffectiveValueParams & args) Line 1979	C++
 	Windows.UI.Xaml.dll!CDependencyObject::SetValue(const SetValueParams & args) Line 1740	C++
 	Windows.UI.Xaml.dll!CUIElement::SetValue(const SetValueParams & args) Line 773	C++
 	Windows.UI.Xaml.dll!CFrameworkElement::SetValue(const SetValueParams & args) Line 236	C++
 	Windows.UI.Xaml.dll!CControl::SetValue(const SetValueParams & args) Line 105	C++
 	Windows.UI.Xaml.dll!CContentControl::SetValue(const SetValueParams & args) Line 114	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DependencyObject_SetValue(CDependencyObject *) Line 2351	C++
 	Windows.UI.Xaml.dll!DirectUI::DependencyObject::SetValueCore(const SetValueParams & args, bool fSetEffectiveValueOnly) Line 1052	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::DependencyObject::SetValueCore(const CDependencyProperty *) Line 273	C++
>	Windows.UI.Xaml.dll!DirectUI::DependencyObject::SetValueByKnownIndex<unsigned char>(KnownPropertyIndex nPropertyIndex, unsigned char value) Line 392	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::SelectorItem::put_IsSelectedImpl(unsigned char) Line 251	C++
 	Windows.UI.Xaml.dll!DirectUI::SelectorItemGenerated::put_IsSelected(unsigned char value) Line 77	C++
 	[Managed to Native Transition]	
 	XmlSyntaxVisualizerUwp.exe!XmlSyntaxVisualizerUwp.MainPage.TreeView_ScrollNode(Microsoft.Language.Xml.SyntaxNode raw_node) Line 240	C#
 	XmlSyntaxVisualizerUwp.exe!XmlSyntaxVisualizerUwp.MainPage.UpdateCurrentInfo() Line 170	C#
 	[Resuming Async Method]	
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<XmlSyntaxVisualizerUwp.MainPage.<UpdateCurrentInfo>d__23>..cctor.AnonymousMethod__9_0(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<System.Threading.Tasks.VoidTaskResult>.AsyncStateMachineBox<XmlSyntaxVisualizerUwp.MainPage.<UpdateCurrentInfo>d__23>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetExistingTaskResult(Monaco.Position result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetResult(Monaco.Position result)	Unknown
 	[Completed] Monaco.winmd!Monaco.CodeEditor.SendScriptAsync<Monaco.Position>(string script, string member, string file, int line)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.CodeEditor.<SendScriptAsync>d__18<Monaco.Position>>..cctor.AnonymousMethod__9_0(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.CodeEditor.<SendScriptAsync>d__18<Monaco.Position>>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetExistingTaskResult(Monaco.Position result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetResult(Monaco.Position result)	Unknown
 	[Completed] Monaco.winmd!Monaco.Extensions.WebViewExtensions.RunScriptAsync<Monaco.Position>(Windows.UI.Xaml.Controls.WebView _view, string script, string member, string file, int line)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.Extensions.WebViewExtensions.<RunScriptAsync>d__1<Monaco.Position>>..cctor.AnonymousMethod__9_0(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.Extensions.WebViewExtensions.<RunScriptAsync>d__1<Monaco.Position>>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetExistingTaskResult(Monaco.Position result)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.SetResult(Monaco.Position result)	Unknown
 	[Completed] Monaco.winmd!Monaco.Extensions.WebViewExtensions.RunScriptHelperAsync<Monaco.Position>(Windows.UI.Xaml.Controls.WebView _view, string script)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.Extensions.WebViewExtensions.<RunScriptHelperAsync>d__2<Monaco.Position>>..cctor.AnonymousMethod__9_0(object s)	Unknown
 	System.Private.CoreLib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Monaco.Position>.AsyncStateMachineBox<Monaco.Extensions.WebViewExtensions.<RunScriptHelperAsync>d__2<Monaco.Position>>.MoveNext()	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.TaskAwaiter.OutputWaitEtwEvents.AnonymousMethod__12_0(System.Action innerContinuation, System.Threading.Tasks.Task innerTask)	Unknown
 	System.Private.CoreLib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.ContinuationWrapper.Invoke()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.InvokeAction(object state)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunCallback(System.Threading.ContextCallback callback, object state, ref System.Threading.Tasks.Task currentTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.SynchronizationContextAwaitTaskContinuation.Run(System.Threading.Tasks.Task task, bool canInlineContinuationTask)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.RunContinuations(object continuationObject)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Private.CoreLib.dll!System.Threading.Tasks.TaskCompletionSource<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	System.Runtime.WindowsRuntime.dll!System.Threading.Tasks.AsyncInfoToTaskBridge<string, System.VoidValueTypeParameter>.Complete(Windows.Foundation.IAsyncInfo asyncInfo, System.Func<Windows.Foundation.IAsyncInfo, string> getResultsFunction, Windows.Foundation.AsyncStatus asyncStatus)	Unknown
 	System.Runtime.WindowsRuntime.dll!System.Threading.Tasks.AsyncInfoToTaskBridge<string, System.VoidValueTypeParameter>.CompleteFromAsyncOperation(Windows.Foundation.IAsyncOperation<string> asyncInfo, Windows.Foundation.AsyncStatus asyncStatus)	Unknown
 	[Native to Managed Transition]	
 	EdgeManager.dll!16003478()	Unknown
 	EdgeManager.dll![Frames below may be incorrect and/or missing, no symbols loaded for EdgeManager.dll]	Unknown
 	EdgeManager.dll!16003245()	Unknown
 	EdgeManager.dll!16002e6a()	Unknown
 	edgehtml.dll!165296f3()	Unknown
 	edgehtml.dll!165295eb()	Unknown
 	edgehtml.dll!1687bad4()	Unknown
 	edgehtml.dll!1687bc88()	Unknown
 	edgehtml.dll!1687c0bd()	Unknown
 	edgehtml.dll!1687ab86()	Unknown
 	edgehtml.dll!168852e0()	Unknown
 	edgehtml.dll!1687accd()	Unknown
 	edgehtml.dll!1646af6c()	Unknown
 	edgehtml.dll!1646a982()	Unknown
 	edgehtml.dll!164688c1()	Unknown
 	edgehtml.dll!164681c6()	Unknown
 	user32.dll!75f974b3()	Unknown
 	user32.dll!75f7493a()	Unknown
 	user32.dll!75f7f53f()	Unknown
 	ntdll.dll!77026d2c()	Unknown
 	user32.dll!75f7f557()	Unknown
 	win32u.dll!7596102c()	Unknown
 	user32.dll!75f7b86e()	Unknown
 	user32.dll!75f7b7ce()	Unknown
 	user32.dll!75f72cc0()	Unknown
 	Windows.UI.dll!09f0e6b8()	Unknown
 	Windows.UI.dll!09f0e47d()	Unknown
 	Windows.UI.dll!09f14995()	Unknown
 	Windows.UI.dll!09f0d022()	Unknown
 	Windows.UI.dll!09f0c548()	Unknown
 	[Inline Frame] Windows.UI.Xaml.dll!CJupiterWindow::RunCoreWindowMessageLoop() Line 1251	C++
 	[Inline Frame] Windows.UI.Xaml.dll!CJupiterControl::RunMessageLoop() Line 1065	C++
 	[Inline Frame] Windows.UI.Xaml.dll!DirectUI::DXamlCore::RunMessageLoop() Line 2496	C++
 	Windows.UI.Xaml.dll!DirectUI::FrameworkView::Run() Line 101	C++
 	twinapi.appcore.dll!61f5eaf2()	Unknown
 	twinapi.appcore.dll!61f60044()	Unknown
 	SHCore.dll!7648b793()	Unknown
 	kernel32.dll!75d96739()	Unknown
 	ntdll.dll!7701bc50()	Unknown
 	ntdll.dll!7701bc1a()	Unknown
```

**Comment by dpaulino** [comment]
I'm getting the exact same error message. I get it when I assign a node to treeview.SelectedNode property to update the highlighted item in the tree.
WinUI version: 2.3.200213001
OS: Windows 10 2004 Build 19041.208

Note that on 90% of the cases, assigning a node to SelectedNode works fine. However, the crash occurs when I performs these steps:
- select the last item of the tree root
- delete that item while it's selected
- add a new item to the tree root
- search for the new node associated with the new item and assign it to SelectedNode

![image](https://user-images.githubusercontent.com/7649589/80324766-2cfa0780-87e7-11ea-8615-b5d8521243f0.png)

**Comment by zhuxb711** [comment]
I also encountered the same problem, whether it is setting the IsSelected property of the TreeViewItem or directly setting the SelextedNode property, there is a certain probability that fast fail.

This problem is extremely serious because the exceptions it triggers cannot be caught, and often cause the program to flash back directly

**Comment by chingucoding** [comment]
This might be an issue with tracker ref:

![image](https://user-images.githubusercontent.com/16122379/83625887-edb49880-a594-11ea-9df6-21771cc0d6fe.png)

@ranjeshj  Would you like me to look into this? We might be getting into a bad state somewhere in the process of setting selection under certain circumstances.

@michael-hawker Can you try to create a minimal repro project or is this something that only happens in this exact scenario (at least reliably)? 
@dpaulino @zhuxb711 Since you also are experiencing this issue, do you maybe have any tips on what a minimal repro project needs to contain? Does this happen even with a blank app only containing a TreeView or are there certain steps that are needed for the crash to occur?

**Comment by zhuxb711** [comment]
@chingucoding
There is a hint that if the SelectedNode is set to null before assignment, the probability of such a crash will be greatly reduced (only the conclusion of the observation, may be incorrect, only for reference)

**Comment by chingucoding** [comment]
> There is a hint that if the SelectedNode is set to null before assignment, the probability of such a crash will be greatly reduced (only the conclusion of the observation, may be incorrect, only for reference)

Thank you @zhuxb711 for the tip! This behavior would fit in with the theory that the reference is in a bad state, since setting the SelectedNode to null before that would likely get rid of the reference.

**Comment by ranjeshj** [comment]
@kmahone can you help debug this issue ?

**Comment by chingucoding** [comment]
It seems that this issue was solved with the changes introduced to TreeView from version 2.4.2 until the latest prerelease. My guess is that the bug disappeared with #2523 where the behavior of `TreeView.SelectedItem` was refactored as it is now a DependencyProperty. 

After updating the repro apps from the issues linked above to the latest WinUI 2.5 prerelease, none of them reproduced the crash. 

@ranjeshj I think we can close this issue then, your thoughts?

**Comment by ranjeshj** [comment]
@chingucoding Thanks for investigating. @michael-hawker can you please try WinUI2.5 preview and reopen this issue if you still see the crash ? Thanks!

**Comment by zhuxb711** [comment]
@ranjeshj @chingucoding 
This problem still exists in the latest preview version, when assigning a value to SelectedNode may trigger a serious error

**Comment by zhuxb711** [comment]
It is probably caused by the CreateTrackerHandle() function

**Comment by chingucoding** [comment]
Could you create a new issue with a repro project? It's a bit difficult to assess what is causing this issue without being able to reproduce it locally. Thank you!

**Comment by zhuxb711** [comment]
@chingucoding  Now I can’t reproduce it, next time I encounter this problem I will submit a new issue

**Comment by chingucoding** [comment]
Great, thanks!

**Comment by schallot** [comment]
I believe I'm experiencing the same issue.  I've posted detailed steps to reproduce here: https://github.com/schallot/Microsoft.UI.Xaml.Controls-TreeView-Selection-Issue
