### ISSUE TITLE
Cannot run WinUI 3 in desktop(C#) after updating toolset

### ISSUE THREAD

**Issue by huoyaoyuan** [microsoft/microsoft-ui-xaml#2677]
I confirmed that I can run the template app when it released at Duild.
But now, I can neither run the code I created then, nor a blank new template app.
The original version I deployed at May can run, so it's a toolset issue, not an OS issue.

What I've done from Build (May 20):
- Update patch versions of VS(16.6.0->16.6.2, 16.7P1->16.7P2)
- Install Windows SDK 19041, but haven't uninstalled 18362
- Update .NET 5 from Preview 4 to Preview 5

What symptoms I've met now:
- At the default state, deployment of the package project will fail, claims that .NET Framework 4.5.1 target pack is not found. The *Universal Windows Development* workload of VS requires 4.5, not 4.5.1
- After manually select and installed the target pack, deployment successes, but the app throws at `WinRT.ComWrappersSupport.InitializeComWrappers`, as-if it's running unpacked

I guess the first issue is caused by new Windows SDK, and the second issue is caused by new preview of .NET 5. I don't want to downgrade them to confirm this. Please consider to update the template version.

The detailed environment of my machine (You can create a new VM and confirm if the template app  will fail):
```
Windows 10 Pro 19041
Visual Studio Enterprise 16.6.2
  - .NET Desktop workload
  - UWP workload, 18362 and 19041 selected
Visual Studio Community 16.7 Preview 2
  - .NET Desktop workload
  - UWP workload, no optional checkbox selected
  - WinUI3 vsix template
.NET 5 SDK Preview 5 x64 (and also the versions come with VS)
```

**Comment by ranjeshj** [comment]
@stevenbrix as FYI

**Comment by stevenbrix** [comment]
@huoyaoyuan the issue with the latest .NET5 Preview5 is a known issue: https://github.com/microsoft/CsWinRT/issues/316

Can you elaborate a bit more on the first one? I'm surprised you need the .NET Framework SDK at all?

**Comment by huoyaoyuan** [comment]
@stevenbrix The error was raised at `Microsoft.Common.CurrentVersion.targets, L1177`
Invoking `Build` on the package project in VS16.7P2 raises it.

Using toolset from VS16.7 Preview raises the error, but VS16.6 toolset can build succesfully.

Here are msbuild logs:

[binlog.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4784919/binlog.zip)

**Comment by stevenbrix** [comment]
@huoyaoyuan thanks for sharing the binlogs! It looks like there was a change to the `Microsoft.DesktopBridge.targets` in VS16.7 Preview2 that broke this.

VS 16.6:
![image](https://user-images.githubusercontent.com/9649518/86067701-5410c780-ba2a-11ea-9028-64eb4d7310aa.png)

VS 16.7 Preview2:
![image](https://user-images.githubusercontent.com/9649518/86067674-3fccca80-ba2a-11ea-9da9-5aa90de0ddf2.png)

I'll reach out to the VS folks to see if this is a known issue. I found the commit that caused this regression, and it's weird because this should affect VS16.7 Preview1 as well, but I don't think we've had issues with that?

**Comment by stevenbrix** [comment]
@huoyaoyuan can you try adding this to your .wapproj and see if that fixes it for you?

```xml

  <PropertyGroup>
    <TargetFrameworkIdentifier>.NETCore</TargetFrameworkIdentifier>
    <TargetFrameworkVersion>v5.0</TargetFrameworkVersion>
  </PropertyGroup>
```

**Comment by huoyaoyuan** [comment]
> @huoyaoyuan can you try adding this to your .wapproj and see if that fixes it for you?

@stevenbrix Yes, it fixes building of `wapproj`.

**Comment by stevenbrix** [comment]
@huoyaoyuan that's good to know. Do you have the .NET Framework SDK installed? VS will install that by default, so I'm wondering if maybe your install was unsuccessful?

**Comment by huoyaoyuan** [comment]
> Do you have the .NET Framework SDK installed?

The versions of .NET Framework target packs I've installed:
- The one required by .NET Desktop workload (4.7.2)
- The one required by UWP workload (4.5)
- The one I've manually chosen (4.8)

But, `Microsoft.Common.targets` was asking for 4.5.1.
I'd expect UWP workload to ask for 4.5 because it does list 4.5 as it's dependency.

**Comment by huoyaoyuan** [comment]
@stevenbrix Latest update:
It works with **.NET 5 Preview 6** with latest CsWinRT(0.1.0-prerelease.200629.3) installed.
It still have build issue with VS 16.7P4. Your workaround is valid, but please mention the VS SDK folks.

**Comment by stevenbrix** [comment]
VS bug regarding the regression is filed here: https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1149356/

**Comment by Scottj1s** [comment]
Closing this issue as both symptoms have been resolved

**Comment by huoyaoyuan** [comment]
The VS issue is still present in 16.7P6. Please remember it before 16.7 is released.

**Comment by huoyaoyuan** [comment]
@stevenbrix I have to mention you again, because this issue prevents me from building the WinUI3 desktop branch of xaml controls gallery.
It generates two errors for missing reference assemblies for `.NET Framework, Version=4.5.1` and `.NET Framework, Version=5.0`. Your workaround only eliminates the first one. Confirmed on VS16.7.1.
Is the fix applied in 16.8?

**Comment by stevenbrix** [comment]
@huoyaoyuan i'm updating to vs16.7.2 and will let you know what i find

**Comment by stevenbrix** [comment]
@huoyaoyuan I wonder if your VS config is a bit off. I was able to build with VS16.7.2.

Here is a link to my [vs config](https://github.com/microsoft/microsoft-ui-xaml/files/5092689/vsconfig.zip)

See the documentation for how to import this file: https://docs.microsoft.com/en-us/visualstudio/install/import-export-installation-configurations?view=vs-2019#import-a-configuration

This should hopefully get your VS in the correct state.

**Comment by huoyaoyuan** [comment]
@stevenbrix I've installed a brand new instance with your config, but was still not able to build it.

To be clear, the solution I built is [XamlControlGallery.Desktop.sln](https://github.com/microsoft/Xaml-Controls-Gallery/blob/winui3preview/XamlControlsGallery/XamlControlsGallery.Desktop.sln) in **winui3preview** branch. Could you confirm that your configuration does work with that solution? Thanks!

**Comment by stevenbrix** [comment]
Hmm I was able to build and run the desktop sln as well @huoyaoyuan

**Comment by huoyaoyuan** [comment]
@stevenbrix I tried on my another machine, and the issue is still present.
Here is the binlog produced.
[XamlControlsGallery.binlog.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5144885/XamlControlsGallery.binlog.zip)

**Comment by stevenbrix** [comment]
@huoyaoyuan do you have the setting in VS to enable preview versions of .NET Core SDKs?

![vs-enablepreview](https://user-images.githubusercontent.com/9649518/91767086-73de7c00-eb90-11ea-9663-6b497202e27c.png)

**Comment by huoyaoyuan** [comment]
@stevenbrix Thanks, that solves the problem. I always use `global.json` to specify preview SDK and have nearly forgotten the global switch.

**Comment by stevenbrix** [comment]
@huoyaoyuan, fantastic! Yeah, I usually get different errors when I don't have this enabled, you can thank @alwu-msft for this one :)
