### ISSUE TITLE
SwapChainPanel has limited size and leaves white area after being removed

### ISSUE THREAD

**Issue by dotMorten** [microsoft/microsoft-ui-xaml#2933]
**Describe the bug**
If I create a SwapChainPanel, there's a limit to how large the rendering area can be. The surface stretches beyond that, but only white is rendered outside that area.
![resizebug](https://user-images.githubusercontent.com/1378165/87723981-7c5d2d80-c76f-11ea-92d3-0db0010b7dda.gif)

**Steps to reproduce the bug**
1. Create a new project from the template "DirectX 11 and XAML app (Universal Windows - C++/CX) **
2. Port this project to WinUI and C++/CX
Or open the attached project here and run it:
[SwapChainPanelBug.zip](https://github.com/microsoft/microsoft-ui-xaml/files/4934366/SwapChainPanelBug.zip)
(note this was a quick and dirty port, and I didn't add al the handlers in the original template, like pointer interaction, dpi change detection etc)

**Expected behavior**
- SwapChain resizes to any size.

**Version Info**

NuGet package version: Microsoft.WinUI.3.0.0-preview2.200713.0

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            | Yes   |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

** Would be nice if that project template from step 1 also was shipped with WinUI

**Comment by StephenLPeters** [comment]
@RBrid who did some work to enable swapchain panel on winui3.

**Comment by dotMorten** [comment]
Actually the surface night not resize at all but you can't tell it's getting smaller because it's getting clipped by the window.

**Comment by codendone** [comment]
This is a XAML bug:  we're not properly updating the size of the SpriteVisual which contains the swapchain.

The visual here is on an internal SwapChainElement.  This element doesn't have any size (because it didn't need a size in the past), so therefore it doesn't see a size change and doesn't update the visual's size.  We should properly size this element.

**Comment by dotMorten** [comment]
Thanks @codendone! I was playing with using the `VisualTreeHelper.GetChild` and `ElementCompositionPreview.GetElementChildVisual(swapchainpanel)` to try and get at that element so I could resize it, but looks like that doesn't work. Can you think of a way to get around that and get at that element and manually resize it until this bug has been fixed?

**Comment by codendone** [comment]
As you noticed, that internal element is hidden from any app code.

Looking at the code, it looks like there is one possible workaround:  call SetSwapChain(nullptr) on the SwapChainPanel and then call it again with the swapchain.  This will mark that internal element as dirty so its Visual properties will be updated.

**Comment by dotMorten** [comment]
Just confirming that I'm seeing this is fixed with the latest preview

**Comment by Gavin-Williams** [comment]
So is this meant to be fixed? Because when I run the project found in SwapChainPanel.zip - the bug is still evident. And even in my own project, I'm using Scaling.Stretch but the swapchain is not being stretched.

**Comment by dotMorten** [comment]
@Gavin-Williams  I’m confused? This was fixed long ago. Are you using my repro?

**Comment by Gavin-Williams** [comment]
I just downloaded the project you linked to above. It is not resizing.

**Comment by dotMorten** [comment]
Did you upgrade it to v1.0.0?

**Comment by Gavin-Williams** [comment]
Do you mean Windows App SDK?

**Comment by dotMorten** [comment]
Yes. This big was logged over a year ago and the repro is naturally based on that old version that was available Back then. A lot has changed since I logged this

**Comment by Gavin-Williams** [comment]
Alright, I see you use WinUI, but it looks like we don't use that package anymore.

**Comment by dotMorten** [comment]
Yes as I said a lot has changed since. WinUI is part is the win app Sdk now

**Comment by Gavin-Williams** [comment]
OK. Done, I see that it works now. Thank you.
