### ISSUE TITLE
Make a NavigationViewItem bahave like a button when pressed and released

### ISSUE THREAD

**Issue by seven-mile** [microsoft/microsoft-ui-xaml#3085]
# Proposal: Make a NavigationViewItem bahave like a button when pressed and released

## Rationale

Generally on Windows (even on other most platforms), a button is regarded as "clicked" and to execute its command if and only if the cursor is pressed on it and released on it, 

which means after pressed, the cursor can move freely, as long as the cursor is on the button when released.

* I have to point out that the NativeUI NavViewItem indeed obeys this rule. However, WinUI's doesn't until now.

* Not only does this problem affect whether the navigating operation will be done, it also brings wrong UI feedback effects and item styles.

In detail, when you press the item and move the cursor out of the rectangle, even after releasing it, the item stays "pressed" style without exception. (It should be a little bug.) **Gif:**

![1.gif](https://i.loli.net/2020/08/09/GvVk7jsrH2q4JZt.gif)

**Comment by kmgallahan** [comment]
> Not only does this problem affect whether the navigating operation will be done, it also brings wrong UI feedback effects and item styles.

Already resolved via #2625 and available in the latest preview release.

> Generally on Windows (even on other most platforms), a button is regarded as "clicked" and to execute its command if and only if the cursor is pressed on it and released on it

Note that tabs in Chrome / new Edge are activated before release, which is likely the predominant form of navigation in Windows by a large margin.

Other places where navigation doesn't require a release would be OneNote for W10 top nav, classic Excel bottom nav, File Explorer top nav.

**Comment by seven-mile** [comment]
> Already resolved via #2625 and available in the latest preview release.

Sorry, I had tested with WinUI 3 Preview 2 (yesterday I tried WinUI3 for Win32, so I did it.). But that problem still exists. Did I miss something? I don't know... But since it has been solved, that should be OK!

> Navigation menus don't / shouldn't necessarily behave exactly like buttons, since they serve different purposes.

Indeed. But its behavior is kind of counter-intuitive, haha. Maybe the best design is worth discussing a little further.

**Comment by kmgallahan** [comment]
I know it is resolved in the [latest WinUI 2.5 pre-release](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0-prerelease.200708003). I'm not sure if it was pushed to the latest WinUI 3 preview yet or not. @RBrid

**Comment by shaheedmalik** [comment]
> I know it is resolved in the [latest WinUI 2.5 pre-release](https://www.nuget.org/packages/Microsoft.UI.Xaml/2.5.0-prerelease.200708003). I'm not sure if it was pushed to the latest WinUI 3 preview yet or not. @RBrid

A bunch of the updates on 2.5 haven't gone to WinUI 3.0 yet.

**Comment by RBrid** [comment]
That is correct - for instance the #2625 fix has not been pushed into WinUI 3 yet. Thanks.

**Comment by YuliKl** [comment]
This appears to be a WinUI 3 problem. WinUI 2 is already working as described here (and expected).

**Comment by ranjeshj** [comment]
I suspect this is a point in time issue that should be fixed with the next merge of WinUI2 into WinUI3.
