### ISSUE TITLE
ContextFlyout>MenuFlyout Doesn't Work After Windows 1809 Update

### ISSUE THREAD

**Issue by GRS-Leedo** [Microsoft/microsoft-ui-xaml#329]
**Describe the bug**
I am developing a Windows UWP app targeting Windows 10 1803.  On Monday, my development machine was running 1803 and my app behaved as expected.  On Tuesday morning, my machine received the 1809 update.  Afterwards, I opened VS2017 to continue development and the ContextMenu no longer appeared as it should.  No errors were generated.

I created a very simple app with minimal UI to test with and again, the Context Menu did not open.  I trapped the MenuFlyout Opening event and found that it was not being fired.  The UI of the test code is as follows:
```xaml
    <Grid>
        <StackPanel>
            <Border BorderBrush="Green" BorderThickness="5" Width="200" Height="100">
                <TextBlock VerticalAlignment="Center" HorizontalAlignment="Center">
                    <TextBlock.ContextFlyout>
                        <MenuFlyout x:Name="testFO" Opening="TestFO_Opening">
                            <MenuFlyoutItem Name="Item1" Text="Bob"/>
                            <MenuFlyoutItem Name ="Item2" Text="Jim"/>
                        </MenuFlyout>
                    </TextBlock.ContextFlyout>
                    This is a test
                </TextBlock>
            </Border>
        </StackPanel>
    </Grid>
```

To verify that this issue was related to 1809, I copied the project to another development machine that was still running 1803 and it functioned as expected.  The Opening event was fired and the MenuFlyoutItems appeared.

Searching the web revealed little useful information.  A user on the MSDN forum was able to verify the issue.  It works correctly in 1709 and 1803 but not in 1809.

Any help or suggestions or a Fix, would be greatly appreciated.

Thanks,

Glen

**Steps to reproduce the bug**
Create a new UWP app on a development machine running 1803.  Use the above code as the UI and add the 'Opening' event handler to the code behind.  Code will function as expected.
Save the project.
Open the project on a development machine running 1809.  'Opening' event will not be triggered and MenuFlyoutItems will not be shown.

This was verified by another MSDN forum user.  The app runs as expected in 1709 and 1803 but not 1809.

**Expected behavior**
The ContextFlyout -> MenuFlyout -> MenuFlyoutItems to be displayed

**Screenshots**
Nothing to show since it does not work.

**Version Info**
Development Machine - Windows 10 1803 Updated to 1809
VS2017 Pro version 15.9.7

NuGet package version: 
Microsoft.NetCore.UniversalWindowsPlatform 6.2.3
[App1.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2885014/App1.zip)

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (18334)                   | Yes   |
| October 2018 Update (17763)   |Yes   |
| April 2018 Update (17134)        | No   |
| Fall Creators Update (16299)     | 1709? No  |
| Creators Update (15063)           |    |
| Anniversary Update (14393)      |    |

| Device form factor | Saw the problem? |
| :-------------------- | :------------------- |
| Desktop                 Yes   |
| Mobile                   |    |
| Xbox                      |    |
| Surface Hub          |     |
| IoT                         |     |

**Additional context**

[App1.zip](https://github.com/Microsoft/microsoft-ui-xaml/files/2885016/App1.zip)

**Comment by jevansaks** [comment]
That's frustrating, we'll investigate.

**Comment by kmahone** [comment]
@GRS-Leedo, thank you for reporting this issue. I can reproduce the problem. It is a bug in the Xaml platform that was introduced in the 1809 release. We will investigate fixing this in a future version of Windows.

The problem is that a ContextFlyout on a TextBlock will not show unless that TextBlock has text selection enabled.

In order to get your application to function on existing versions of Windows, it should be possible to work around this bug. Can you move the ContextFlyout from the TextBlock to a different element? For example, in the Xaml snippet that you provide, if the ContextFlyout is moved to the TextBlock's parent (the Border element), then the ContextFlyout will function correctly.

**Comment by kmahone** [comment]
Filed an [internal issue](https://microsoft.visualstudio.com/OS/_workitems/edit/20587589) on this.

**Comment by kmahone** [comment]
The internal issue has been resolved and the fix will be available in a future release of Windows.

**Comment by duke7553** [comment]
I don't intend to "wake up" this closed issue, but this bug still affects the latest 1809 releases. The ContextFlyout is a crucial part of the app I'm working on, and creating a MenuFlyout and attaching it to a Grid with `Grid.ContextFlyout ` results in no flyout. The ContextRequested event isn't fired for that matter. I am also unable to display these on the `Page`.

```
<Grid Name="RootGrid" IsRightTapEnabled="True" RightTapped="RootGrid_RightTapped">
        <Grid.ContextFlyout>
            <MenuFlyout x:Name="EmptySpaceFlyout">
                <MenuFlyout.Items>
                    <MenuFlyoutItem Text="Refresh" Name="aRefreshEmptySpace">
                        <MenuFlyoutItem.Icon>
                            <FontIcon Glyph="&#xE72C;"/>
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>
                    <MenuFlyoutItem Text="Paste" Name="aPasteEmptySpace" IsEnabled="{x:Bind local3:Interaction.PS.isEnabled, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}">
                        <MenuFlyoutItem.Icon>
                            <FontIcon Glyph="&#xE77F;"/>
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>
                    <MenuFlyoutItem Text="Open externally...">
                        <MenuFlyoutItem.Icon>
                            <FontIcon Glyph="&#xE756;"/>
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>
                    <MenuFlyoutSeparator/>
                    <MenuFlyoutItem Text="Properties">
                        <MenuFlyoutItem.Icon>
                            <FontIcon Glyph="&#xE946;"/>
                        </MenuFlyoutItem.Icon>
                    </MenuFlyoutItem>

                </MenuFlyout.Items>
            </MenuFlyout>
        </Grid.ContextFlyout>
</Grid>
```

**Comment by duke7553** [comment]
Is there at least a workaround I can apply to my project? I just need to add a right click ContextFlyout to a Grid with empty space.

**Comment by kmahone** [comment]
@duke7553 if you set Background="Transparent" on the Grid, does that result in it being shown? The bug that this issue is tracking is a bug in the framework that prevents ContextFlyout from working on TextBlock/RichEditBlock. It should not affect Grid.

**Comment by duke7553** [comment]
@kmahone Setting the background to transparent seems to have fixed it. Still un-intuitive, but thank you!

**Comment by kmahone** [comment]
@duke7553 good to hear. The reason this makes a difference is that ContextFlyout needs something to hit test against in order to work. An empty Grid does not contain anything hit-testable, so right clicking on it will not result in it processing any input. Setting a Background to anything (even Transparent) will make it hit-testable.

**Comment by duke7553** [comment]
@kmahone Good to know

**Comment by GRS-Leedo** [comment]
I am not sure about adding it to a grid.  You may need to put a border inside of your grid and attach to that.

What I ended up doing is creating a MenuFlyout in code behind.  Create the MenuFlyout, add MenuFlyoutItems to it and assign methods to their click events and then use Flyout.SetAttachedFlyout to attach to your border.

I have 2 different flyouts that I attached to 8 (in my case textblocks) each.  I created a custom class that inherits from MenuFlyoutItem so that I could add identifying information for processing the click events.  This allowed me to use a single click event listener.

Add a RightTapped to your border and in the attached method cast sender to a border, create a var FO and set it to Flyout.GetAttachedFlyOut(YourBorder) and then call FO.ShowAt(YourBorder)

The single RightTapped Event will handle all of your flyouts for all of your borders/

Works great.

I hope this helps.
