### ISSUE TITLE
OpenFileDialog is not working with WinUI3 preview 2 and .NET5 preview 7 for desktop app development

### ISSUE THREAD

**Issue by anshul-rohilla** [microsoft/microsoft-ui-xaml#3295]
I recently started migrating an old desktop app to WinUI3. The application has simple UI but complex backend business logic. I started with creating a blank new desktop application using WinUI3 preview 2 and .NET5 preview 7 and then slowly built the new UI. Everything looks great until I encountered problem with file browser functionality. OpenFileDialog is not recognized and build is failing. I have tried following:

1.  Use FileOpenPicker instead of OpenFileDialog 
     No compile time error but failed on runtime as FileOpenPicker is built for UWP.

2. Tried changing the SDK to "Microsoft.NET.Sdk.WindowsDesktop" 
    It fixes the issue with OpenFileDialog, but many other issues start surfacing.

3. Tried changing target framework to "net5.0-windows"
    Visual Studio is not recognizing the target framework at all.

Can someone please help me out here? This is the only blocker I have.

**Comment by StephenLPeters** [comment]
@stevenbrix This sound really familiar, do you remember something like this (a cswinrt bug causing file picker to fail)?

**Comment by stevenbrix** [comment]
@anshul-rohilla can you take a look at https://github.com/microsoft/WinUI-3-Demos/tree/master/DemoBuildCs? This should be fixed by Preview3 so that you don't have any awkward steps or weird wrappers

**Comment by anshul-rohilla** [comment]
@StephenLPeters @stevenbrix thank you so much for providing updates. I will wait for Preview 3, meanwhile I will check the demo link you have provided.

**Comment by kirilvalev** [comment]
This is still failing with preview 3. Any update on the issue?

**Comment by cornem** [comment]
This is still not working in preview 4. Here are some details:

```xml
<TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
<PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview4.210210.4" />
```

```csharp
private async Task LoadFileAsync()
{
    var picker = new FileOpenPicker
    {
        ViewMode = PickerViewMode.Thumbnail,
        SuggestedStartLocation = PickerLocationId.PicturesLibrary
    };

    picker.FileTypeFilter.Add(".jpg");
    picker.FileTypeFilter.Add(".jpeg");
    picker.FileTypeFilter.Add(".png");

    await picker.PickSingleFileAsync();
}
```

Calling this method will throw `System.Runtime.InteropServices.COMException` with this message: `Invalid window handle. (0x80070578)"`.

**Comment by wbokkers** [comment]
The workaround mentioned by @cornem is not working when using PickMultipleFilesAsync()

See: https://gist.github.com/wbokkers/cc8bcc7bc5a646b82a4d41b337330c69#gistcomment-3649439

**Comment by Gavin-Williams** [comment]
This issue is still present in May 2022 - Windows App SDK 1.1.0-preview3. What's the deal?

**Comment by castorix** [comment]
> This issue is still present in May 2022 - Windows App SDK 1.1.0-preview3. What's the deal?

Which issue ?

 **WinRT.Interop.InitializeWithWindow.Initialize** works fine for me, with PickSingleFileAsync or PickMultipleFilesAsync
(Windows 10 21H1)

**Comment by lukedukeus** [comment]
Using this way, I get the same issue.

> This is still not working in preview 4. Here are some details:
> 
> ```
> <TargetFramework>net5.0-windows10.0.19041.0</TargetFramework>
> <PackageReference Include="Microsoft.WinUI" Version="3.0.0-preview4.210210.4" />
> ```
> 
> ```cs
> private async Task LoadFileAsync()
> {
>     var picker = new FileOpenPicker
>     {
>         ViewMode = PickerViewMode.Thumbnail,
>         SuggestedStartLocation = PickerLocationId.PicturesLibrary
>     };
> 
>     picker.FileTypeFilter.Add(".jpg");
>     picker.FileTypeFilter.Add(".jpeg");
>     picker.FileTypeFilter.Add(".png");
> 
>     await picker.PickSingleFileAsync();
> }
> ```
> 
> Calling this method will throw `System.Runtime.InteropServices.COMException` with this message: `Invalid window handle. (0x80070578)"`.
> 
> Edit: I could get it to work by using the solution from [this comment](https://github.com/microsoft/microsoft-ui-xaml/issues/2716#issuecomment-727043010).


If i use the fix mentioned above, I get `System.Runtime.InteropServices.COMException: 'Error HRESULT E_FAIL has been returned from a call to a COM component.'`

I am on windows 11 22000 and using Windows App SDK 1.1.0-preview3

**Comment by Gavin-Williams** [comment]
The interop workaround is working OK. I'm just surprised that the OpenFileDialog doesn't work. The discussion at https://github.com/microsoft/WindowsAppSDK/discussions/1887 goes into the steps to be taken to slightly improve the code steps to workaround over the short-term and mentions that long term (haha - seriously) the API will work as expected.
