### ISSUE TITLE
Theme is not applied to NavView items on App Startup when assigning Dark or Light Theme

### ISSUE THREAD

**Issue by vmadurga** [microsoft/microsoft-ui-xaml#3384]
**Describe the bug**
Theme is not applied to NavView items correctly on Application Startup when assigning Dark or Light Theme:
 
**Steps to reproduce the bug**
 
In the attached repro project
 
1. Start ThemeSupportApp
2. Go to the setting page
3. Change to Dark theme
4. Close the app
5. Start ThemeSupportApp again

 
**Observed**
 
=> NavViewItem Text is not shown (see screenshot)
![imagen](https://user-images.githubusercontent.com/25466105/95321769-c8fe6380-089b-11eb-930a-1b03ed6c26e7.png)

Closing and opening the NavView with the Hamburger Menu Button makes the items appear again
![imagen](https://user-images.githubusercontent.com/25466105/95321849-e8958c00-089b-11eb-9fef-60dbf86fc2a6.png)
 

**Expected behavior**
 
NavView Items should show correctly
 
**Version Info**
 
WinUI3 3.0.0-preview2.200713.0
 
**Repro**
[ThemeSupportApp.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5340087/ThemeSupportApp.zip)

 
The project was created with WinUI3 Templates from Windows Template Studio, tracking issue on our side is https://github.com/microsoft/WindowsTemplateStudio/issues/3810

**Comment by ranjeshj** [comment]
Can you try to repro with an item that does not have an icon and see if the text is clipped ?

**Comment by vmadurga** [comment]
Hi @ranjeshj ,

Removing the NavigationViewItem Icon:
![imagen](https://user-images.githubusercontent.com/25466105/95428755-c0646680-0949-11eb-98e9-c5f6b59401d2.png)

If we select a navigation item, the content still doesn't show propertly:
![imagen](https://user-images.githubusercontent.com/25466105/95428848-dd009e80-0949-11eb-8c72-dd843f5c8729.png)

It's look like the content does not calc the correct size and apply the size when de menu is closed

**Comment by StephenLPeters** [comment]
I beleive this is an issue that was fixed in winui 2.5 which has not yet been ported to Winui3. However I can't seem to find the issue or the PR.  @chingucoding or @Felix-Dev I believe one of you fixed the issue (Thank you!) do you know its number?  @YuliKl do you remember? I think the your phone team was hitting it.

**Comment by chingucoding** [comment]
The issue with content clipping was fixed with #2717 by @Felix-Dev . Not sure what is happening with the theme issue here, don't think that happened in WinUI 2 yet.

**Comment by StephenLPeters** [comment]
Ah, I think @ranjeshj found it https://github.com/microsoft/microsoft-ui-xaml/pull/2810  This change should fix that issue but is not included in the current preview of winui3.

**Comment by mvegaca** [comment]
Fixed on WinUI 3 Preview 4

**Comment by mvegaca** [comment]
After testing in a different screen resolution we've seen that it still happens, launching the app with the navigation view opened the items texts is not visible.

![image](https://user-images.githubusercontent.com/5556784/108035883-cd037480-7037-11eb-9dcc-febfb5ab6d6d.png)

Adding the app shown in the screenshot (WinUI 3 Preview 4)

[Issue3384App.zip](https://github.com/microsoft/microsoft-ui-xaml/files/5987073/Issue3384App.zip)

**Comment by sibille** [comment]
This issue is still happening after updating to Project Reunion 0.5 Preview

**Comment by sibille** [comment]
This is still happening after updating to Project Reunion Version 0.5.6, but we could fix it by adding the NavView to a ShellPage instead of a ShellWindow.
