### ISSUE TITLE
NavigationView OpenPaneLength does not apply to PaneToggleButton automatically

### ISSUE THREAD

**Issue by Shad0wlife** [microsoft/microsoft-ui-xaml#3456]
**Describe the bug**
When changing the OpenPaneLength of a NavigationView (on the left of the window) while the Pane is Expanded, the Pane area is correctly changed, but the button area of the PaneToggleButton does not change with it. It only updates after Toggling the Pane twice.

**Steps to reproduce the bug**
1. Create a NavigationView
EDIT: 1.5: Set the PaneTitle of the NavigationView
2. Bind PaneOpenLength to a variable that can change during runtime (I specifically bound it to the pixelwidth of a grid below, that I resized with a Toolkit GridSplitter)
3. Resize the Pane while it is fully expanded
4. See that the pane area correctly changes its width, but the mouseover area of the PaneToggleButton doesn't match the Pane length anymore.
(5. Optional: Collapse and Expand the Pane to see that the Button width now matches the (changed) Pane Length again)

**Expected behavior**
The PaneToggleButton's width for the Expanded Pane is kept in sync with the OpenPaneLength at all times (like a One-Way binding).

**Screenshots**
Please post if desired, I'd have to censor the information visible or make a demo app, both of which would take time.

**Version Info**

NuGet package version: 
Microsoft.UI.Xaml 2.5.0-prerelease.200923002

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       | Yes   |
| May 2019 Update (18362)            |   |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |   |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               | |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
None yet.

**Comment by Felix-Dev** [comment]
@Shad0wlife This is how it looks for me:

![navview-panetogglebutton](https://user-images.githubusercontent.com/1398851/96722584-d3e1e980-13ad-11eb-8731-1e17a0c0d87f.gif)
where clicking the button increases the OpenPaneWidth by 50 on each click. 

This looks like the correct behavior to me. The PaneToggleButton is not a NavigationViewItem which fills the complete pane width. It's a button with width 40 to act as a touch target. It does not fit the pane width even with default OpenPaneWidth.

> Optional: Collapse and Expand the Pane to see that the Button width now matches the (changed) Pane Length again

As you can see in the gif, collapsing and expanding the pane did not change the button width.

Did I misunderstand you?

**Comment by StephenLPeters** [comment]
@Felix-Dev can you try this repro with the PaneTitle property set to something? I think that changes this behavior.

**Comment by StephenLPeters** [comment]
@Shad0wlife do you have the PaneTitle property set to something?

**Comment by Felix-Dev** [comment]
@StephenLPeters Yep, this should be it:

![navview-panetogglebutton](https://user-images.githubusercontent.com/1398851/96801465-f43e9200-1407-11eb-809f-a6acd3b56c8b.gif)

I assume this is a bug then and I could take a look at this.

**Comment by Shad0wlife** [comment]
Yes, I have the Pane Title set. (It also happens with localization via x:Uid and Resources.resw)
Thanks for looking into it!

**Comment by ranjeshj** [comment]
Thanks @Felix-Dev - that makes it very clear. Please go ahead with your investigation. Thanks!

**Comment by chingucoding** [comment]
Could it be that this was addressed with #4573?

**Comment by Shad0wlife** [comment]
Fairly certain that it was not adressed, as I still experience the above behaviour in WinUI 2.6
