### ISSUE TITLE
Desktop App - Empty DesktopWindowXamlSource window visible on task bar

### ISSUE THREAD

**Issue by bridgesquared** [microsoft/microsoft-ui-xaml#3698]
**Describe the bug**
When running a Win UI Desktop app with Win UI 3 Preview 3 (default template app, Xaml Controls Gallery or my own app), either through debug in VS 2019 16.9 Preview 1 (or 16.8) or from the Start Menu, a blank window with title DesktopWindowXamlSource appears on the task bar along side the app.

**Steps to reproduce the bug**
1. Run VS 2019
2. File | New | Project | Blank App, Packaged (WinUI in Desktop)
3. F5 (Debug package)

**Expected behavior**
I expect  a single window with title "WinUI Desktop" to be visible in the task bar and when you hover over the icon I would expect a single thumbnail.

**Actual behavior**
A second (empty) window thumbnail with title "DesktopWindowXamlSource" is visible ;-)

**Screenshots**

![image](https://user-images.githubusercontent.com/11475368/100217907-e949b680-2f0b-11eb-93be-c668f5b63dc1.png)
![image](https://user-images.githubusercontent.com/11475368/100218076-24e48080-2f0c-11eb-86a9-54ca98812e26.png)

**Version Info**

NuGet package version: 
[Microsoft.WinUI 3.0.0-preview3.201113.0]

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| 20H2 (19042)              | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

I can't say when this started to appear, I tried Win UI 3 Preview 3 the moment it was available for download, don't know whether it was there in Preview 2, only started to notice it when clicking on the taskbar to bring up the app. Was surprised to see it in the Xaml Controls Gallery build as well but again can't say when it first appeared. Look forward to seeing whether any one else is reporting this. Thanks

**Comment by huoyaoyuan** [comment]
This is regression in Preview 3. I've used Preview 2 for 3 months and never seen this.

**Comment by StephenLPeters** [comment]
@pratikone is this the core window issue you worked on? I thought this was resolved.

**Comment by FreddyD-GH** [comment]
Are there any situations where the empty DesktopWindowXamlSource DOES NOT occur?  I've seen it 100% of the time when using Preview 3.  Perhaps it should be documented as a known issue at: [https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-3-limitations-and-known-issues](https://docs.microsoft.com/en-us/windows/apps/winui/winui3/#preview-3-limitations-and-known-issues)?

**Comment by Austin-Lamb** [comment]
We have fixed this issue internally, it should show up in the next preview.

**Comment by anawishnoff** [comment]
Confirming that this bug has been fixed, and the fix will be available in our next release - WinUI 3 Preview 4. We're hoping to ship this preview release in early February. Thanks!

**Comment by crramirez** [comment]
Wiiiiiii

**Comment by crramirez** [comment]
I heavily recommend opening a new issue. This one is related to WinUI 3, and I am inclined to think that the cause of this and the one you are reporting is different.

Regards,
Carlos

**Comment by taenri** [comment]
@crramirez - Sounds good, just posted: https://github.com/microsoft/microsoft-ui-xaml/issues/6490

**Comment by rollsch** [comment]
I am seeing this with the parent process as OneDrive. Closing it closes onedrive.

**Comment by nubix** [comment]
> I am seeing this with the parent process as OneDrive. Closing it closes onedrive.

I can confirm this issue.

**Comment by hebernielsen** [comment]
Showed up on my machine about 4 weeks ago. Double taskbar, empty window. I'm not good enough to trace it down to a Windows build. I don't get Previews, so it cannot be a feature of a beta version as far as I know.

**Comment by jcpt928** [comment]
> I am seeing this with the parent process as OneDrive. Closing it closes onedrive.

Confirming - been at least 6 weeks since it started occurring on OneDrive.

**Comment by taenri** [comment]
@jcpt928 - Hmm, I thought that we had fixed this bug last month. But maybe we missed something. Can you please let me know what version of OneDrive and Windows you are currently using when you get the chance?

**Comment by jcpt928** [comment]
> 

![image](https://user-images.githubusercontent.com/7883133/210395577-e5eef802-d0e3-4fa1-a6e7-0d2389ef04e2.png)

![image](https://user-images.githubusercontent.com/7883133/210395691-250254dc-4e00-4e8a-ae9c-04016cfc3e14.png)

This is a device that will not be upgrading to Windows 11.

**Comment by taenri** [comment]
@jcpt928 - Thank you for the info! Curiously, your OneDrive build _should_ have the correct fix that we implemented in November. Unfortunately, and even more curiously, I have been unable to repro the issue even while using the same Windows build number. I will continue to investigate further and update this issue when I have more useful information.

-Tai

**Comment by rollsch** [comment]
My onedrive is fixed now

**Comment by nubix** [comment]
The issue still persists with these this build.

![image](https://user-images.githubusercontent.com/151969/210749731-94fa5186-aca9-4b15-a370-22d29c36c8f3.png)

Edition	Windows 10 Education
Version	22H2
Installed on	‎23.‎08.‎2020
OS build	19045.2364
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Comment by jcpt928** [comment]
The endpoint in question pulled the 22H2 update, and, the issue persists. Interestingly, it seems to be impacting only the "personal" OneDrive instance now (white cloud), instead of both the "personal" (white cloud) and "organization" (blue cloud). I've got no idea why that might be.

**Comment by gomble** [comment]
Issue still persist with both private and business:
![image](https://user-images.githubusercontent.com/6769445/212033829-cccfc5ee-33d6-4707-be2f-69489d3596ec.png)

**Comment by jdmarch** [comment]
Confirming issue persists on personal OneDrive version: Build 23.002.0102.0001 (64-bit).
Windows 10.0.19045
Scary to realize that I've been seeing this, and closing the window as detritus, for what seems like years, meaning that my OneDrive has usually not been syncing.

**Comment by dawnli-github** [comment]
In version 22.225, I got this error when I opened the Settings, but it was fine for normal use; In versions 22.245 to 23.002, I just started OneDrive, and the problem started.
Windows Version: 19045.2545

**Comment by kudlav** [comment]
The desktopwindowsxamlsource window appears with auto-startup of OneDrive: Build 22.248.1127.0001 (64bit), Windows 10 22H2.

**Comment by littl3viking** [comment]
Same problem with OneDrive version: Build 22.253.1204.0001 (64-bit). 
![explorer_BGAkydAz5V](https://user-images.githubusercontent.com/20413396/212707275-ff4c6287-a0a0-4a66-8f96-9b187dd852d5.png)
![explorer_cyWm69nEw1](https://user-images.githubusercontent.com/20413396/212707319-2e2b9bca-23cc-4224-ab38-5152bf1cd496.png)

**Comment by mario-beeler** [comment]
Hello
I have the same problem with Win10 22H2 (64bit) and OneDrive 22.248.1127.0001 (64bit). I reinstalled OneDrive, but still the same problem.
Before the reinstall there was OneDrive 22.253.1204.0001 (64bit) and it gets the same problem. After I downloaded OneDrive from the Microsoft-Site, I have an older version than it was installed before the reinstall.

**Comment by mario-beeler** [comment]
It is with OneDrive-Business.

**Comment by dbivolaru** [comment]
I am also experiencing this since last week on OneDrive Business for work.
OneDrive 22.253.1204.0001 (64-bit) on Windows 10 Enterprise 21H2.

The checkbox for technology previews is disabled.

**Comment by littl3viking** [comment]
I found a temporary "solution", killing explorer.exe and restarting.
Can use this command: `taskkill.exe /f /im explorer.exe && start explorer.exe`

**Comment by Firebird626** [comment]
I am having this issue now on build 23.002.0102.0004
I am on Windows 10 Pro 19045.2486

**Comment by SteveKoss** [comment]
Uninstalling and installing version 22.166.0807.0002 removes the empty taskbar window. Version 22.166.0807.0002 uses the old settings GUI.  All versions I tried which use the new settings GUI have the same issue.

`taskkill.exe /f /im explorer.exe && start explorer.exe` did not work as one step for me but breaking it two steps did.
1) `taskkill.exe /f /im explorer.exe` 
2) `explorer.exe`

**Comment by mario-beeler** [comment]
@taenri  Is there any updates on this?

**Comment by moxwel** [comment]
It happened to me too, "DesktopWindowXamlSource" appears every time OneDrive is running. I'm on Windows 10 19045.2486.

I found a workaround to "hide" this empty window:

Go to `Settings > System > Multitasking > Virtual Desktops`

There it says "On the taskbar, show windows that are open", select **"Only the desktop I’m using"**.

For me, this solved "DesktopWindowXamlSource" appearing in the taskbar, but this should not be happening in the first place... Oh well...

**Comment by rollsch** [comment]
This is now back again with 
OneDrive version: Build 23.007.0109.0004 (64-bit)
Windows 10 21H2 19044.2486

**Comment by taenri** [comment]
Hi Folks,

Thank you for all the feedback and workaround information from above. We are still unsure why this continues happening in OneDrive on Windows 10 Versions 19044 and 19045. We have been unable to reproduce the issue internally since we implemented a fix to manually hide the Window late last year. I have a few theories as to why this issue persists, and am working on gathering more data/information to put these theories to the test. But I have yet to uncover anything conclusive.

If anyone else is having similar issues, I would encourage using the "[Send Feedback"](https://support.microsoft.com/en-us/office/send-onedrive-feedback-594f538c-cb25-4079-b1f2-716d91d41bde) feature in OneDrive instead of continuing to post here, as it will help our support team better to more clearly understand/triage the issue.

Since this bug only occurs on these specific versions of Windows 10, I would also recommend upgrading to Windows 11 if you are able to do so as this bug has been fixed at the OS level in these later versions.

That said, the workarounds suggested by @moxwel and @littl3viking are also very interesting. These workarounds may give us some hints as to why our current workaround code in OneDrive does not work as consistently in the wild as it does in-house.

Thanks,
Tai

**Comment by MattTheTechLV** [comment]
Good Afternoon, I am about to submit using "Send Feedback", but I just wanted to mention here as well, that I just started experiencing this bug.

The Workaround suggested by @moxwel did help to fix it for me, but as I use Virtual Desktops and like my Taskbar Icon's to show up on all Virtual Desktops, I would prefer to find a fix to this bug. I noticed some similarities in terms of my system as others experiencing this issue.

I am running Windows 10 22H2 Enterprise, and while my PC is capable of Upgrading to Windows 11, I prefer Windows 10 so I won't be upgrading. I run WIndows 11 in a few VM's though, and am warming to it, but there are a number of reasons why Windows 10 is still the best OS for me.

I run dual monitors. I use the Business Version of One Drive. The Specific Version number of OneDrive is: [23.011.0115.0006]

This issue just started happening today when My OneDrive updated to this newest version. I know it just updated today, because earlier today I was adding another sharepoint folder to sync with, so I was in settings and it still had the older style look. Shortly after I noticed the OneDrive Icon on my Taskbar that had the "DesktopWindowXamlSource" title, and when I closed it, it closed Outlook altogether. Then I went into the settings to see if there was a setting I could change, and noticed it now had a new look more consistent with the Windows 11 Settings UI. 

Here are some other system specs in case they happen to be relevant, I doubt they are, but figured I would mention them in case they help with diagnosing the issue.

In One Drive, I sync to an Actual OneDrive Business Account, and to multiple Sharepoint Folders. I am not connected at all to a Non Business OneDrive account.

One of the settings I use in OneDrive is that I limit Upload Speeds, doubt that is relevant, but mentioning it just in case.

I have the Insider Builds turned off for Both OneDrive and Windows 10 itself.

System Specs:
Ryzen 9 5900x
64GB Ram 3600Mhz CL16
RTX 3080
Win10 22H2 Enterprise

Hopefully this helps, here are some screenshots of the issue and the version.

![image](https://user-images.githubusercontent.com/61740449/216474928-bb97f276-6074-4a4c-8089-bcbe2b869c7a.png)

![image](https://user-images.githubusercontent.com/61740449/216475254-4a45920b-c94e-4635-9d4f-4b44defd5e09.png)

![image](https://user-images.githubusercontent.com/61740449/216475512-8052ad21-5faa-4c24-8e64-d5ee5a8e12f8.png)

I edited out Device ID's out of habit.

Thank You for your work!

**Comment by Cipheriax** [comment]
> Thank you for all the feedback and workaround information from above. We are still unsure why this continues happening in OneDrive on Windows 10 Versions 19044 and 19045. We have been unable to reproduce the issue internally since we implemented a fix to manually hide the Window late last year.

Hi @taenri , can you show me the KB# that addressed this and the fix on how to manually hide it? 
Since you said;
> That said, the workarounds suggested by @moxwel and @littl3viking are also very interesting. 
I assume killing the explorer isn't what you were talking about.

**Comment by jcpt928** [comment]
How is this "closed", when it very clearly continues to occur, with no definitive, and appropriate, fix implemented? Workarounds =/= fixes, Microsoft - surely you guys have taken your ITIL classes.

**Comment by TemporaryAl** [comment]
This is still present, needs to be reopened.

**Comment by pratikone** [comment]
The actual issue is opened in a new issue :   #6490 
Onedrive's not same as this issue, hence, it is closed. Please provide info in that other issue, it is open.

**Comment by TemporaryAl** [comment]
But the issue is in Onedrive, not this XAML Islands thing for me


-------- Ursprüngliche Nachricht --------
Von: Pratik Anand ***@***.***>
Datum: 09.02.23 09:39 (GMT+01:00)
An: microsoft/microsoft-ui-xaml ***@***.***>
Cc: TemporaryAl ***@***.***>, Comment ***@***.***>
Betreff: Re: [microsoft/microsoft-ui-xaml] Desktop App - Empty DesktopWindowXamlSource window visible on task bar (#3698)


The actual issue is opened in a new issue : #6490<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml%2Fissues%2F6490&data=05%7C01%7C%7Cf6b84cb72f7b4d9663e908db0a791cf8%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115287513254044%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JZlvzL1QE0g0QVsG5mOaz4jFTOVQM%2FM3EP4VYJ8kzuQ%3D&reserved=0> (XAML Islands - Empty DesktopWindowXamlSource window visible on task bar)
Onedrive's not same as this issue, hence, it is closed. Please provide info in that other issue, it is open.

**Comment by pratikone** [comment]
In that case, please use `Feedback Hub` to report it to OneDrive team. You can use shortcut `Win+F` to bring up Feedback Hub.

**Comment by TemporaryAl** [comment]
The issue is already there, it just needs to be reopened as it is NOT solved, and I reported that in the thread itself. There is no need to report it again through feedback hub. The workarounds provided in the thread are not acceptable.


-------- Ursprüngliche Nachricht --------
Von: Pratik Anand ***@***.***>
Datum: 09.02.23 09:53 (GMT+01:00)
An: microsoft/microsoft-ui-xaml ***@***.***>
Cc: TemporaryAl ***@***.***>, Comment ***@***.***>
Betreff: Re: [microsoft/microsoft-ui-xaml] Desktop App - Empty DesktopWindowXamlSource window visible on task bar (#3698)


In that case, please use Feedback Hub to report it to OneDrive team. You can use shortcut Win+F to bring up Feedback Hub.

**Comment by MattTheTechLV** [comment]
lol. I just posted my issue where @pratikone suggested, didn't realize until now that that is actually a different issue... 

I agree with @TemporaryAl , this issue shouldn't be closed, it is obviously still an open issue that OneDrive users are still having, and the issue is with OneDrive.

**Comment by MattTheTechLV** [comment]
> It is happening on various different PCs, with different editions (pro, home, education) with the latest versions of Onedrive. Italian language being installed is the only particular thing I can think of on all of them
> […](#)
> -------- Ursprüngliche Nachricht -------- Von: MattTheTechLV ***@***.***> Datum: 09.02.23 10:02 (GMT+01:00) An: microsoft/microsoft-ui-xaml ***@***.***> Cc: TemporaryAl ***@***.***>, Mention ***@***.***> Betreff: Re: [microsoft/microsoft-ui-xaml] Desktop App - Empty DesktopWindowXamlSource window visible on task bar (#3698) lol. I just posted my issue where @pratikone<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpratikone&data=05%7C01%7C%7Ce3746f713637471fd73008db0a7c5823%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115301398018753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=X4V79CY5fhdb8O9K%2Fh7PD%2FEUNO6Ipzvjz2KEgh1wtN8%3D&reserved=0> suggested, didn't realize until now that that is actually a different issue... I agree with @TemporaryAl<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FTemporaryAl&data=05%7C01%7C%7Ce3746f713637471fd73008db0a7c5823%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115301398018753%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zGM%2FJFGdKNjYxu3cs696u%2FF1KM3PRDawr4RP3I3GoY8%3D&reserved=0> , this issue shouldn't be closed, it is obviously still an open issue that OneDrive users are still having, and the issue is with OneDrive. — Reply to this email directly, view it on GitHub<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmicrosoft%2Fmicrosoft-ui-xaml%2Fissues%2F3698%23issuecomment-1423847738&data=05%7C01%7C%7Ce3746f713637471fd73008db0a7c5823%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115301398174961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=blY4neYJhfhoN34HoHPs24I9NH8qwpK5ba3KQ4Clymw%3D&reserved=0>, or unsubscribe<https://emea01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAU3E37UKHD4VTQO5N4Y5MFTWWSXBTANCNFSM4UCHN62A&data=05%7C01%7C%7Ce3746f713637471fd73008db0a7c5823%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C638115301398174961%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=ooy%2BNLCzSs0%2BGmRCuS%2Bcnn28Y%2FUWQAQWg%2FdtScCgsuI%3D&reserved=0>. You are receiving this because you were mentioned.Message ID: ***@***.***>

I can confirm that My PC does not have the Italian Language installed. Only English. But I agree with your statement otherwise. It only happened for me with the latest version of OneDrive, specifically [23.011.0115.0006], and I have the Enterprise Edition of Windows 10 22H2, so thats yet another edition that is impacted. Seems its just a problem between Windows 10 21h2 and newer, and OneDrive Version [23.011.0115.0006], no matter what Edition of Windows 10 you have.

Would be nice if they would reopen the issue, so more people would give them information. I too have used the Send Feedback Page in OneDrive, but its nice to be able to keep track on the progress of a particular issue.

**Comment by jcpt928** [comment]
> The actual issue is opened in a new issue : #6490 (XAML Islands - Empty DesktopWindowXamlSource window visible on task bar) Onedrive's not same as this issue, hence, it is closed. Please provide info in that other issue, it is open.

This is unacceptable. You don't arbitrarily "roll-up" an issue into another without verifying as such; and, as others have pointed out, this is a OneDrive issue, that continues to occur.

I'm sure most of us reporting this issue are more than knowledgeable enough to transition to alternative solutions, if we choose to do so, and move any user bases we're engaged with as well; so, I'm not sure "telling us to go over in a corner and be quiet" is a wise decision on the part of those Microsoft technicians that are apart of this thread. This is starting to feel an awful lot like an "Experts Exchange" thread.

**Comment by jcpt928** [comment]
This continues to be an ACTIVE issue. Officially requesting the issue be REOPENED until Microsoft provides a solution.

**Comment by carter-canedy** [comment]
> @bpulliam / @Austin-Lamb - Our team has rediscovered this bug in WinUI 2.8.0 preview, but it only repros on Windows 10 version 21H2 (specifically on build 19044.1348).
> 
> It repros both with our own application, and the xaml-islands playground application by @asklar : https://github.com/asklar/xaml-islands/tree/main/Playground To repro with the Playground project above, comment out lines 172-251 in Playground\WindowsProject1.cpp WindowsProject1.cpp. Doing this ensures that the DesktopWindowXamlSource hwnd content is never set, which exposes the invisible window appearing in the taskbar.
> 
> Are there any plans to fix this bug in WinUI2X preview versions? We must use WinUI2X instead of 3X in order to properly use XAML Islands in Unpackaged Win32 applications, which is why upgrading to WinUI3X is not currently an option for us.
> 
> If you would prefer that I open a new issue instead of re-opening this one, please let me know.
> 
> Any information you can provide on this issue would be greatly appreciated. Cheers!

This looks like it's an active issue in any of the 19044 OS builds, I'm able to reproduce it using revision 2604. In my case it's happening when using the OneDrive desktop app.

**Comment by taenri** [comment]
Update for folks with OneDrive issues specifically on this thread - We were able to find a fix for this issue from our side and checked in a change for it into our master branch yesterday. It will still be some time before the latest build finishes rolling out to Production (usually takes about 2-3 weeks, but only about 1 week if you opt-in to Insider builds). The build to look for would be **23.045.0228.0001** or greater.

In case others find our solution useful, we ended up using the `ITaskbarList::DeleteTab` Win32 API to explicitly remove the `DesktopWindowXamlSource` handle from the taskbar ourselves.

**Comment by TemporaryAl** [comment]
Yes, Amazing! Finally, I was starting to lose hope. Thank you so much!

Inviato da Posta<https://go.microsoft.com/fwlink/?LinkId=550986> per Windows 10

Da: ***@***.***>
Inviato: giovedì 9 marzo 2023 10:57
A: ***@***.***>
Cc: ***@***.***>; ***@***.***>
Oggetto: Re: [microsoft/microsoft-ui-xaml] Desktop App - Empty DesktopWindowXamlSource window visible on task bar (#3698)


We were able to find a fix for this issue from our side and checked in a change for it into our master branch yesterday. It will still be some time before the latest build finishes rolling out to Production (usually takes about 2-3 weeks, but only about 1 week if you opt-in to Insider builds). The build to look for would be 23.045.0228.0001 or greater.

Can confirm, the window is gone! I'm on 23.045.0228.0001
Thank you for looking into this rather minor but annoying issue.

**Comment by SteveKoss** [comment]
23.045.0228.0001 fixes issue for me too. Thank-you!

**Comment by kansasSamurai** [comment]
sorry but this is a piece of crap.  this is not fixed.  it's March 2023, still occurring.  Microsoft OS sucks (and I'm fine with this post being from my primary account becuase this is very true; I stand behind my assessment/statement)
