### ISSUE TITLE
Windows Store App Certification Fails after upgrading Microsoft.UI.XAML to v2.5.0

### ISSUE THREAD

**Issue by under3415** [microsoft/microsoft-ui-xaml#3780]
**Describe the bug**
After updating Microsoft.UI.Xaml from 2.5.0-prerelease201202003 to the v.2.5.0 (release) the UWP app got rejected from the store with the following errors. This was the only change to the app, It was all good with pre-release UI.Xaml

**FAILED**
    General metadata correctness

    Error Found: The general metadata correctness test detected the following errors:
        Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
        The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

        Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
        The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

**Steps to reproduce the bug**
Submit UWP app  to store with UI>XAML and Microsoft.Toolkit.Uwp.UI.Lottie (either v.6.1.0 or v7 preview4)
This is NOT picked up by app cert kit on PC

**Expected behavior**
No certification issues

**Screenshots**

**Version Info**

NuGet package version: 
Microsoft.UI.XAML v.2.5.0

Examples

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2020 Update (19041)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |  |

**Additional context**

**Comment by YuliKl** [comment]
Sounds related to #3298.

@StephenLPeters FYI.

**Comment by StephenLPeters** [comment]
@kmahone and @ranjeshj FYI as well

**Comment by StephenLPeters** [comment]
The workaround is simple – app developers need to open the .csproj or .vcxproj file that has a reference to the Project which targets the winui2 nuget package (or includes a project which does, like lottie) NuGet package and insert this target at the bottom of the file right before </Project>:

  <Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="_CreatePackageLayout">
    <Copy
        SourceFiles="@(_PackageLayoutFileSource)"
        DestinationFiles="@(_PackageLayoutFileSource->'$(AppxLayoutDir)%(Filename)%(Extension)')"
        Condition="'%(Filename)%(Extension)' == 'Microsoft.UI.Xaml.winmd'" />
  </Target>

That will have MSBuild copy the WinMD file to the root of the AppX, which should allow WACK certification to find it.

I think we can also fix this from the Winui2 side and should take a patch to the 2.5 release.

**Comment by under3415** [comment]
> The workaround is simple – app developers need to open the .csproj or .vcxproj file that has a reference to the Project which targets the winui2 nuget package (or includes a project which does, like lottie) NuGet package and insert this target at the bottom of the file right before :
> 
> That will have MSBuild copy the WinMD file to the root of the AppX, which should allow WACK certification to find it.
> 
> I think we can also fix this from the Winui2 side and should take a patch to the 2.5 release.

Not sure if I did the right thing. When you say "insert this target at the bottom of the file right before :" do you mean before a colon character or is something missing? 

This is what the end of my csproj file looks like and this did NOT resolve the issue, it still got rejected by the store. Am I not doing it right?

` <Import Project="$(MSBuildExtensionsPath)\Microsoft\WindowsXaml\v$(VisualStudioVersion)\Microsoft.Windows.UI.Xaml.CSharp.targets" />
  <Target Name="_AddXamlWinmdToPackageLayoutRoot" AfterTargets="_CreatePackageLayout">
    <Copy SourceFiles="@(_PackageLayoutFileSource)" DestinationFiles="@(_PackageLayoutFileSource->'$(AppxLayoutDir)%(Filename)%(Extension)')" Condition="'%(Filename)%(Extension)' == 'Microsoft.UI.Xaml.winmd'" />
  </Target>
  
</Project>`

**Comment by michael-hawker** [comment]
@StephenLPeters this is resolved now, eh? We just shipped the WCT Sample App via the store with 2.5 as a dependency for our 7.0.0 release...

**Comment by llongley** [comment]
A fix is in final testing, hopefully to be checked in by today or tomorrow:

https://github.com/microsoft/microsoft-ui-xaml/pull/4218

It'll be part of the 2.6.0 release.

**Comment by under3415** [comment]
Hi, I was NOT getting this error in UI.XAML prerelease packages until yesterday. Now the error is back with 
Microsoft.UI.XAML 2.6.0-prerelease.210315002

**Comment by under3415** [comment]
Hi
I can confirm this is still an issue with the latest versions of UI XAML and Lottie:

- Microsoft.UI.XAML 2.6.0-prerelease.210405001
- Microsoft.Toolkit.Uwp.UI.Lottie v7.0.2

> Error Found: The general metadata correctness test detected the following errors:
> 
>     Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
>     The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.ILottieVisualSourceClass in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.
>     Parameter value of method add_AnimatedVisualInvalidated of type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd references the non-Windows Runtime type Microsoft.UI.Xaml.Controls.IDynamicAnimatedVisualSource. Windows Runtime types can reference only Windows Runtime types.
>     The type Microsoft.UI.Xaml.Controls.IAnimatedVisual referenced by type Microsoft.Toolkit.Uwp.UI.Lottie.LottieVisualSource in file Microsoft.Toolkit.Uwp.UI.Lottie.winmd was not found. All types referenced in metadata files must be discoverable.

**Comment by rajeshangappan** [comment]
Please anyone suggest which version is working fine for store submission. I tried the below version and facing some other exceptions.
Microsoft.UI.Xaml - 2.5.0-prerelease201202003 and Lottie - 6.1.0

**Comment by jp-weber** [comment]
@rajeshangappan 
I have successfully made the store submission with the following packages in the last days:
Microsoft.UI.Xaml -2.6.0-prerelease.210227001 & the newest Lottie version.

**Comment by under3415** [comment]
If you are on version 2.5, it worked in 2.5.0-prerelease.201202003, but not the release 2.5.0

**Comment by llongley** [comment]
@under3415 Do you have or could you create a repro app that you could share, by any chance?  I created a test app that includes Lottie 7.0.2 and WinUI 2.6.0-prerelease.210405001, and the AppX produced passes WACK metadata tests, so I haven't been able to repro the issue you're seeing.

**Comment by under3415** [comment]
This issue is not picked up by the certification app, or even in the Store in the test flight! 
It is only rejected by the Store when you try to submit to "production", so it is really hard to test and replicate. 
You have to deploy the app to the public store to see the issue.

**Comment by llongley** [comment]
Ah, I see the WACK failure now that I tried to submit the test app to the store.  Thanks, we'll investigate.

**Comment by llongley** [comment]
Sorry for the trouble - I have [a fix out for PR](https://github.com/microsoft/microsoft-ui-xaml/pull/4820).

**Comment by RobbyRobbyRobby** [comment]
I can confirm that with the latest preview  (v2.6.0-prerelease.210430001) that apps again pass the store submission.

![image](https://user-images.githubusercontent.com/25928318/117077722-fc469980-ad7b-11eb-96bc-f7705a116adb.png)

Thanks everyone.
Rob.

**Comment by under3415** [comment]
Hi, 
Another RTM release, another store rejection! 

I have updated Microrsoft.UI.Xaml to 2.6.0 and my app got rejected by the store (in test flight). There were no other changes. 

Unfortunately, the store no longer gives any details, just says "failed certification". There is no report :-( 
![image](https://user-images.githubusercontent.com/3857822/124190503-7d20d800-db16-11eb-9200-c4b86e859d9e.png)

Cert App on PC does not detect any issues. 

Can we please re-open this issue?

**Comment by StephenLPeters** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/5298 is tracking this issue.
