### ISSUE TITLE
Microsoft.VCLibs could not be found when using Microsoft.UI.Xaml in a class library

### ISSUE THREAD

**Issue by asierpn** [microsoft/microsoft-ui-xaml#4483]
The "Microsoft.VCLibs could not be found" warning appears when using the Microsoft.UI.Xaml 2.5.0 nuget package in a UWP class library project.

**Steps to reproduce the bug**
1. Create a new UWP class library project (Universal Windows)
2. Install the Microsoft.UI.Xaml 2.5.0 nuget package
3. Compile the project
4. Close Visual Studio and open the project again
5. A reference to Microsoft.VCLibs is added to the project with a warning

**Expected behavior**
No warning for this reference when using Microsoft.UI.Xaml in a class library.

**Screenshots**

![image](https://user-images.githubusercontent.com/9281751/110757729-005aad00-824c-11eb-9e2d-90f62b8e0c4b.png)

**Version Info**

NuGet package version: 

Microsoft.UI.Xaml 2.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes | No |

**Comment by StephenLPeters** [comment]
@jevansaks thoughts on this?

**Comment by jevansaks** [comment]
Does it cause any compile errors or other negative side effects?

**Comment by asierpn** [comment]
The class library compiles fine but there is not way to get rid of this warning, in our production app we have 7 class libraries using WinUI 2.5 so we have 7 warnings in our log all time. If you manually remove the reference to VCLibs the warning goes until you restart Visual Studio. This is very annoying.

**Comment by jevansaks** [comment]
This was ostensibly fixed by this change, but it's been in for a long time. The SdkReference isn't supposed to be getting added unless OutputType == AppContainerExe.
https://github.com/microsoft/microsoft-ui-xaml/commit/d0eb58a68dfa4fdd26d830a094df7d1bf390486a#diff-ca529d193fa795d44750b7a9fad01101bd2f3ffaa7cd647ef008a0eb9f608494

@RBrid  can you take a look?

**Comment by ArchieCoder** [comment]
I still have this issue in my UWP app! I would love to get rid of this warning.
