### ISSUE TITLE
Mouse right-click in TextBox crashes the application

### ISSUE THREAD

**Issue by Herdubreid** [microsoft/microsoft-ui-xaml#4804]
**Describe the bug**
Mouse right-click in TextBox crashes the application.

**Steps to reproduce the bug**
- Create new WinUI 3 in Desktop project.
- Add a TextBox to MainWindow.xaml
```xaml
    <StackPanel Orientation="Horizontal" HorizontalAlignment="Center" VerticalAlignment="Center">
        <Button x:Name="myButton" Click="myButton_Click">Click Me</Button>
        <TextBox/>
    </StackPanel>
```
- Run the application
- Right-click with the mouse pointer inside the TextBox

**Expected behavior**

Application doesn't crash.

**Screenshots**

**Version Info**

NuGet package version: 

WinUI 3 - Project Reunion 0.5: 0.5.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by Noemata** [comment]
Screenshot of where it crashes:

![image](https://user-images.githubusercontent.com/6632315/114579914-573d1300-9c4c-11eb-9ac8-626dc7b7181b.png)

Just including the control is enough to cause the crash on a right click.

**Comment by Noemata** [comment]
Having devs do all the unit testing results in problems like the one above.  Developers are too well behaved and scoped when evaluating their own work.

**Comment by StephenLPeters** [comment]
Is this another first chance exception that can be continued through?

**Comment by Noemata** [comment]
@StephenLPeters , despite some of these exceptions being benign (you can continue), they are a performance drain and need to be stomped out.  They also contribute to a negative developer experience.

**Comment by StephenLPeters** [comment]
I agree.  I'm just trying to get information that might be useful for the team.  I suspect that a lot of these types of issues have similar  root causes.

**Comment by Noemata** [comment]
@StephenLPeters , hopefully the next WinUI release will calm things down a little.  I've got a dozen other bugs I'll report when the next release is out.  It's best not to distract too much at this point.  Most of the bugs have existed in UWP for years.  I'm hoping both UWP and WinUI can get sorted out simultaneously.  These are all UI related.

**Comment by codendone** [comment]
I debugged this, and the caught exception comes from AcrylicBrush.

**Comment by Noemata** [comment]
@codendone , thank you for the clarification.  Before you put out the next release, I suggest you run through these samples (release build, without VS attached):  https://github.com/Noemata/RosettaNavigation

UWP runs most of these indefinitely.  So should WinUI.  Presently, all except the WebView test end in a crash within a couple hours of runtime on a system with 16GB of ram.

**Comment by anawishnoff** [comment]
Hi @Herdubreid, you should see a fix for this bug in the upcoming WinUI 3/Project Reunion 0.8 Preview, which you can expect soon. Thanks for filing this!

**Comment by nCastle1** [comment]
This is still an issue with the released version. I'm using the latest released windows app sdk and build tools that I could get working.

![image](https://user-images.githubusercontent.com/29742178/146284421-10c3fb05-190a-4bfb-b8de-bfff61498446.png)

The only difference is the textbox needs to have text in it; it no longer repros when it starts empty.

**Comment by knightmeister** [comment]
This is still happening for me in the current release of the Windows App SDK (Nuget Package Microsoft.WindowsAppSDK 1.0.0)

Right clicking a text box (regardless of whether there is text in it causes a crash).

```
Exception thrown at 0x00007FFC30F54F69 in App1.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000E41B57C2B0.
```

This gets written to the output window:

```
mincore\com\oleaut32\dispatch\ups.cpp(2122)\OLEAUT32.dll!00007FFC31F29DD6: (caller: 00007FFC31F291E9) ReturnHr(1) tid(19b4) 8002801D Library not registered.
Exception thrown at 0x00007FFC30F54F69 (KernelBase.dll) in App1.exe: WinRT originate error - 0x80070490 : 'Element not found.'.
onecore\com\combase\winrt\error\restrictederror.cpp(1016)\combase.dll!00007FFC3163C363: (caller: 00007FFC31646049) ReturnHr(1) tid(19b4) 8007007E The specified module could not be found.
Exception thrown at 0x00007FFC30F54F69 in App1.exe: Microsoft C++ exception: winrt::hresult_error at memory location 0x000000E41B57C2B0.
```

**Comment by EmrecanKaracayir** [comment]
Same issue with RichTextBlock. Any news?

**Comment by eku1s** [comment]
I am also experiencing this issue with the latest SDKs. As a beginner WinUI developer, experiences like this make us believe we've done something wrong when we haven't, which is quite frustrating. 

Is there any way to re-open this issue?

**Comment by Abdelfattah-Radwan** [comment]
This must be re-opened. The issue is still present in `Microsoft.WindowsAppSdk` version **_1.0.0_** that was released on **_Tuesday, November 16, 2021 (11/16/2021)_**.

**Comment by codendone** [comment]
This is a noisy exception. F5 in the debugger will continue, or the debugger could be changed to not always break in on C++/WInRT exceptions.

The noisy exception is coming from CommandBarFlyoutCommandBar::UpdateVisualState(), which is calling ApplicationView::GetForCurrentView(). Some other places guard against causing an exception by only making this call "if (winrt::CoreWindow::GetForCurrentThread())" passes.

**Comment by StephenLPeters** [comment]
@llongley FYI

**Comment by CAKCy** [comment]
I had the TextBox/right click problem. "Magically" the problem disappeared when I did a repair of VS2022 due to another reason (an Extension update breaking it.)

**Comment by m1nicrusher** [comment]
> I had the TextBox/right click problem. "Magically" the problem disappeared when I did a repair of VS2022 due to another reason (an Extension update breaking it.)

Maybe when it repairs, it also installed a newer version of SDK. Could you confirm your SDK version?
Cheers

**Comment by ghost1372** [comment]
this issue is fixed in wasdk 1.1.0 stable

**Comment by knightmeister** [comment]
>this issue is fixed in wasdk 1.1.0 stable
Confirmed, I am no longer seeing this.

**Comment by Abdelfattah-Radwan** [comment]
I'm still having this issue as of Saturday, July 17, 2022 (7/17/2022) in `Microsoft.WindowsAppSDK` version `1.1.2` that was released on Saturday, July 2, 2022 (7/2/2022)

**Comment by codendone** [comment]
Fixed internally... again.

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.3.0` has been released which fixes this issue.
* [Release Notes](https://aka.ms/windowsappsdk/1.3/1.3.0/release-notes)
* [Nuget](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.3.230331000)
