### ISSUE TITLE
wapproj files not loading with Net6 sdk

### ISSUE THREAD

**Issue by arivoir** [microsoft/microsoft-ui-xaml#4898]
After installing Net 6 SDK 6.0.100-preview3.21202.5 the .wapproj projects of WinUI 3 for desktop don't load anymore

> (Package).wapproj : error  : The result "" of evaluating the value "$(ILLinkTasksAssembly)" of the "AssemblyFile" attribute in element <UsingTask> is not valid.  C:\Program Files\dotnet\sdk\6.0.100-preview.3.21202.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.ILLink.targets

Is there any way of using WinUI with Net6 sdk installed?

**Comment by arivoir** [comment]
It seems this problem only happens in VS 16.10.0 Preview 2.0. It works in the non-preview one.

**Comment by StephenLPeters** [comment]
I wasn't aware we supported .net 6 yet.  @alwu-msft  thoughts on the VS version specific issue?

**Comment by alwu-msft** [comment]
This is a known issue in the .NET SDK which has been fixed (https://github.com/dotnet/sdk/pull/17042) and will be available in VS 16.10 Preview 3.

**Comment by andrewleader** [comment]
@alwu-msft I'm running VS 16.10 Preview 4 and still seeing this issue...

```
.NET SDKs installed:
  5.0.202 [C:\Program Files\dotnet\sdk]
  5.0.300-preview.21258.4 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.3.21202.5 [C:\Program Files\dotnet\sdk]
```

```
Microsoft Visual Studio Enterprise 2019 Preview
Version 16.10.0 Preview 4.0
VisualStudio.16.Preview/16.10.0-pre.4.0+31313.381
Microsoft .NET Framework
Version 4.8.04161

Installed Version: Enterprise

Visual C++ 2019   00435-60000-00000-AA902
Microsoft Visual C++ 2019

ASP.NET and Web Tools 2019   16.10.524.62055
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0   16.10.524.62055
Azure App Service Tools v3.0.0

C# Tools   3.10.0-4.21262.12+dc0aff25e0ace6e6bf98269963612f9a67cdc897
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

IntelliCode Extension   1.0
IntelliCode Visual Studio Extension Detailed Info

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

Microsoft MI-Based Debugger   1.0
Provides support for connecting Visual Studio to MI compatible debuggers

Microsoft Visual C++ Wizards   1.0
Microsoft Visual C++ Wizards

Microsoft Visual Studio VC Package   1.0
Microsoft Visual Studio VC Package

NuGet Package Manager   5.10.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

Test Adapter for Boost.Test   1.0
Enables Visual Studio's testing tools with unit tests written for Boost.Test.  The use terms and Third Party Notices are available in the extension installation directory.

Test Adapter for Google Test   1.0
Enables Visual Studio's testing tools with unit tests written for Google Test.  The use terms and Third Party Notices are available in the extension installation directory.

TypeScript Tools   16.0.30429.2002
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   3.10.0-4.21262.12+dc0aff25e0ace6e6bf98269963612f9a67cdc897
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   16.10.0-beta.21262.7+1b23bbeda88ea3cb9be9af777f4c99fa8663df81
Microsoft Visual F# Tools

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Tools for CMake   1.0
Visual Studio Tools for CMake
```

**Comment by alwu-msft** [comment]
There's a bug in the publicly available project template (this has been fixed internally). Check that in the `.wapproj` the `<AssetTargetFallbacks>` property is defined *after* the `<TargetPlatformVersion>` property, and if not, make it so; the bug is that the former relies on the latter but was being defined first and so ended up with the wrong value.

**Comment by bharath-yadav** [comment]
> There's a bug in the publicly available project template (this has been fixed internally). Check that in the `.wapproj` the `<AssetTargetFallbacks>` property is defined _after_ the `<TargetPlatformVersion>` property, and if not, make it so; the bug is that the former relies on the latter but was being defined first and so ended up with the wrong value.

I don't even have <AssetTargetFallbacks> property defined in my .wapproj. Still the packaging project load failed. 
VS 16.10 Preview 4.0

**Comment by andrewleader** [comment]
Reopening this bug since there's two hits.

And @alwu-msft in my case, the .wapproj is never even created, it fails to even create the project (I'm trying to create a new WinUI 3 project).

**Comment by alwu-msft** [comment]
@andrewleader Try updating to the latest available versions of .NET SDK (5.0.302 and 6.0.100-preview.6). It's very possible that the preview versions your earlier comment shows didn't include the necessary fix yet.

**Comment by evelynwu-msft** [comment]
Closing as this was a .NET SDK issue that has long since been fixed.
