### ISSUE TITLE
Shadows are broken on 10bit displays

### ISSUE THREAD

**Issue by rafifos** [microsoft/microsoft-ui-xaml#4940]
**Describe the bug**

Shadows on UWP Applications are broken/blocky when the color depth configuration of the display is set to 10 bpc (on the NVIDIA Control Panel).

**Steps to reproduce the bug**

1. Go to the NVIDIA Control Panel
2. Click on Change resolution
3. Set the output color depth to 10 bpc
4. Open an Application (e.g. Files)
5. See that shadows in context menus and other components are blocky

**Expected behavior**

Shadows should not be blocky.

**Screenshots**

![image](https://user-images.githubusercontent.com/12601769/116643439-72e03300-a947-11eb-9e89-1a8e64f8a2b8.png)

**Version Info**

NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows 10 version                 | Saw the problem? |
| :--------------------------------- | :--------------- |
| Insider Build (xxxxx)              |       Yes        |
| October 2020 Update (19042)        |       Yes        |
| May 2020 Update (19041)            |       Yes        |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            |       Yes        |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

Originally reported at https://github.com/files-community/Files/issues/4801

**Comment by StephenLPeters** [comment]
@rafifos what product did you find this issue using? System Xaml, winui2.5, winui2.6 preview or winui3?

@gegao18 and @kmelmon FYI

**Comment by rafifos** [comment]
@StephenLPeters Primarly on Files (also reported here: https://github.com/files-community/Files/issues/4801), but other applications are also suffering from it. (For example, the Settings app in Windows).

Since it happens on system apps as well, I guess it's the System XAML.

**Comment by yaichenbaum** [comment]
@StephenLPeters The version of Files this was reported with was using WinUI 2.5.

**Comment by Vas0sky** [comment]
It happens on the 21H1 version as well, it doesn't only break shadows but some other UWP graphics as well (I remember OneNote for Windows 10 flickering a lot). It also happens if you set bpc to 12 (basically anything higher than 8).

**Comment by KodWhat** [comment]
Hi!
Now that Windows 11 is out in preview, I can confirm having this issue as well everywhere in the UI : Windows shadows on open/close animations, Start, Store, Settings, my own apps, ...

The 10bpc seems to be the issue as when I switch back to 8bpc, the issue is gone nearly immediately.

The shadows are not the only broken thing. Gradients doesn't show, radio buttons inner-circle doesn't show, text on buttons can glitch and font smoothing doesn't seem to apply everywhere.

Here's a few screenshots:
![image](https://user-images.githubusercontent.com/1282471/124792574-667ee480-df4d-11eb-8870-3d49b4b919cd.png)
![image](https://user-images.githubusercontent.com/1282471/124792915-c4133100-df4d-11eb-800c-89405f3bacf1.png)

https://user-images.githubusercontent.com/1282471/124793099-f2910c00-df4d-11eb-869b-d28f51f45041.mp4
Yep, even the last one is gone after switching back to 8bpc. The issue might not come 100% from WinUI but from Windows itself

**Comment by jesseinsf** [comment]
All this seems to be more noticeable when setting your refresh rate to 60hz (Maybe 120Hz). The reason is 10bpc may not enable when refresh rate is set higher than 120hz.

**Comment by jesseinsf** [comment]
The Windows 10 issues have been happening since Nvidia released 30-bit support in driver version 431.70 which was released on Mon Jul 29, 2019. I've been reporting this ever since then and each time I've been thrown under the bus.

**Comment by rafifos** [comment]
> The Windows 10 issues have been happening since Nvidia released 30-bit support in driver version 431.70 which was released on Mon Jul 29, 2019. I've been reporting this ever since then and each time I've been thrown under the bus.

@jesseinsf So we should report it on the NVIDIA Forum (again)?

**Comment by jesseinsf** [comment]
> > The Windows 10 issues have been happening since Nvidia released 30-bit support in driver version 431.70 which was released on Mon Jul 29, 2019. I've been reporting this ever since then and each time I've been thrown under the bus.
> 
> @jesseinsf So we should report it on the NVIDIA Forum (again)?

I have been forever and every time I have been thrown under the bus. It is not but a few days ago that they have finally shown interest. 

[My Nvidia forum post](https://www.nvidia.com/en-us/geforce/forums/notifications/topic/249451/)

[Nvidia Windows 11 Feedback Thread](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/462146/windows-11-insider-preview-display-driver-feedback/)

**Comment by jesseinsf** [comment]
> > The Windows 10 issues have been happening since Nvidia released 30-bit support in driver version 431.70 which was released on Mon Jul 29, 2019. I've been reporting this ever since then and each time I've been thrown under the bus.
> 
> @jesseinsf So we should report it on the NVIDIA Forum (again)?

Yes, I think we need to be more aggressive with reporting. We need to break through their "Godlike" ignorant attitudes.

**Comment by Squall-Leonhart** [comment]
If believe the primary issue is that WinUI/DXGI are not using more than R10G10B10A2 types when the driver is circumventing and overriding the windows behavior to achieve 10bit, this results in there not being enough transparency bits to display the intended gradual blending out of the shadows leading to them being hard and blocky.

**Comment by jesseinsf** [comment]
Nvidia's driver 471.68 seems to have fixed this issue in Windows 11. Has anyone tried this driver version out on Windows 10? Did it also fix the Windows 10 issue?

**Comment by crysehillmes** [comment]
Seems NVIDIA finally fixed these issues.
After upgrading to NVIDIA 471.68 driver, shadow problems, flickers and glitches are all disappeared on Windows 11. 

Release notes:
[Game Ready Driver Release Notes (v471.68)](https://us.download.nvidia.com/Windows/471.68/471.68-win11-win10-win8-win7-release-notes.pdf)

**Comment by jesseinsf** [comment]
> Seems NVIDIA finally fixed these issues.
> After upgrading to NVIDIA 471.68 driver, shadow problems, flickers and glitches are all disappeared on Windows 11.
> 
> Release notes:
> [Game Ready Driver Release Notes (v471.68)](https://us.download.nvidia.com/Windows/471.68/471.68-win11-win10-win8-win7-release-notes.pdf)

It took them 743 days to acknowledge it was their problem.

**Comment by rafifos** [comment]
From the release notes linked above:

> - Rendering artifacts appear on the desktop when using NVIDIA SDR deep color (10pbc). [3340917]

**Comment by RobinTTY** [comment]
I'm currently using driver version 471.96 and Windows 10 19043.1165, still encountering this visual glitch:
<img width="898" alt="2021-09-19" src="https://user-images.githubusercontent.com/27669180/133911740-223db9fc-fe7a-471c-8f40-550bdece69c7.png">

**Comment by Squall-Leonhart** [comment]
This issue is present with Windows 10 and its version of the new windows store on the reportedly fixed drivers, nvidia has been informed.

![unknown 1](https://user-images.githubusercontent.com/1098176/143421801-2d2e3ad2-ec10-456c-8bfe-931bdfa138ff.png)

**Comment by Squall-Leonhart** [comment]
This has been fixed on Windows 10 as of Release 496

**Comment by Xer0o** [comment]
The same issue exist on AMD's GPUs too sadly with the latest driver and the latest Windows 11 Insider Dev build, it happens when I open an app and when I close it

![ezgif com-gif-maker](https://user-images.githubusercontent.com/34497713/168036166-36da69ef-f777-445f-94fd-5c890e9a39df.gif)

**Comment by ciriousjoker** [comment]
I'm still facing the exact issue of @Xer0o , although it happens only sometimes and isn't reproducible.

I mainly noticed it when opening the first instance of Notepad, but not other Windows as far as I can recall.

**Comment by Squall-Leonhart** [comment]
you'd be best off contacting AMD to have them fix their driver then.
