### ISSUE TITLE
App.UnhandledException doesn't catch exceptions from other threads.

### ISSUE THREAD

**Issue by artkat** [microsoft/microsoft-ui-xaml#5221]
**Describe the bug**
Unable to catch UnhandledException (at app level) when the exception originates from async Task.

**Steps to reproduce the bug**
1. Create new WinUI3 project
2. In App.cs handle UnhandledException:
```
public App()
        {
            this.InitializeComponent();
            this.UnhandledException += App_UnhandledException;
        }


        private void App_UnhandledException(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e)
        {
            Debug.WriteLine("WinUI App Crashed");
        }
```
3. In MainWindow.cs add a button with code-behind that will throw a devide-by-zero exception from an Async method:
```
private async void myButton_Click(object sender, RoutedEventArgs e)
        {
            int t = await Task.Run(() =>
            {
                var x = 0;
                var y = 3 / x;
                return y;
            });
        }
```

**Expected behavior**
Would expect the App_UnhandledException to 'handle' this exception.

**Screenshots**
![image](https://user-images.githubusercontent.com/3071447/122634239-9b96d480-d10f-11eb-84ec-669c2ada83f9.png)

**Version Info**
WinUI 0.8.0-preview
Windows 10 

NuGet package version: 
Microsoft.ProjectReunion (0.8.0-preview)
Microsoft.ProjectReunion.Foundation (0.8.0-preview)
Microsoft.ProjectReunion.WinUI (0.8.0-preview)

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| No | Yes |

| Windows 10 version                  | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        | Yes   |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |   |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
GitHub example with 2 'identical' projects, one UWP (WinUI2) and one WinUI3, to show the difference in behavior between the two.
https://github.com/artkat/CrashingApp
[](https://github.com/artkat/CrashingApp)

**Comment by StephenLPeters** [comment]
@chrisglein I think the addition context implies that this is a winui3 regression.  I'm a bit surprised that Application.UnhandledException could catch off thread exceptions though, I thought this was designed for UI thread exceptions (although the name certainly implies all exceptions)

**Comment by Marv51** [comment]
Is [`CoreApplication.UnhandledErrorDetected`] the more relevant event for this?

**Comment by artkat** [comment]
> @chrisglein I think the addition context implies that this is a winui3 regression. I'm a bit surprised that Application.UnhandledException could catch off thread exceptions though, I thought this was designed for UI thread exceptions (although the name certainly implies all exceptions)

In UWP this was often used to handle (read: log) fatal crashes.
AppCenter framework is also unable to catch fatal WinUI3 crashes.
Any idea how else how to log them?

**Comment by chrisglein** [comment]
Still repros on WinAppSDK 8.2.
Confirmed this does get caught on UWP but doesn't in WinUI3, so this is for sure a regression (or not yet implemented).

**Comment by Panchus** [comment]
Windows.ApplicationModel.Core.CoreApplication.UnhandledErrorDetected and Application.UnhandledException works for me on a WinUI 1.0 .Net 6 application, but only on synchronous operations, they fail to catch even the same kind of exceptions thrown in async methods.
Any idea or alternative to do this or I am doing something wrong?

**Comment by d2dyno1** [comment]
> Windows.ApplicationModel.Core.CoreApplication.UnhandledErrorDetected and Application.UnhandledException works for me on a WinUI 1.0 .Net 6 application, but only on synchronous operations, they fail to catch even the same kind of exceptions thrown in async methods. Any idea or alternative to do this or I am doing something wrong?

You might be interested in `TaskScheduler.UnobservedTaskException` @Panchus

**Comment by Panchus** [comment]
> > Windows.ApplicationModel.Core.CoreApplication.UnhandledErrorDetected and Application.UnhandledException works for me on a WinUI 1.0 .Net 6 application, but only on synchronous operations, they fail to catch even the same kind of exceptions thrown in async methods. Any idea or alternative to do this or I am doing something wrong?
> 
> You might be interested in `TaskScheduler.UnobservedTaskException` @Panchus

I tried that, but in only triggers when you dont await Tasks, this isn't what I want
In any case I know now that there's no way to do this since they are essentially different threads and therefore every async method must catch their own exceptions
Thanks anyways!

**Comment by knightmeister** [comment]
Really need a neat way to be able to catch unhandled exceptions, for a few reasons:

1. analytics (i.e. app center)
2. display a helpful message to the user

Nothing is more jarring than just having an app disappear.

**Comment by sjb-sjb** [comment]
Maybe there is a way to do this by replacing the synchronization context?

**Comment by StephenCleary** [comment]
Seems like they already have a `SynchronizationContext`, so it's probably just a matter of catching the exception at the top level in that context and raising the top-level event. (Exceptions from `async void` methods are raised directly on the `SynchronizationContext` that was current at the time the method started executing).

**Comment by artkat** [comment]
This bug has been reported nearly a year ago.
Still, no one has been assigned to fix it.
I'm disappointed, frustrated, annoyed, and honestly quite pissed that this is the way Microsoft handles this project.

**Comment by knightmeister** [comment]
> This bug has been reported nearly a year ago. Still, no one has been assigned to fix it. I'm disappointed, frustrated, annoyed, and honestly quite pissed that this is the way Microsoft handles this project.

It really feels like WinUI is enormously underresourced. There are trivial bugs, and real show stopping bugs that have been kicking around for a loooong time. I'm hopeful this is going to change in the near future because I love the platform.

**Comment by sjb-sjb** [comment]
> 

@StephenCleary  how do I catch the exception at the top level in the synchronization context? Wouldn’t I have to re-write and install the synchronization context to do that?

**Comment by mattjohnsonpint** [comment]
Even when the exception is caught, it is loosing all important detail such as message and stack trace.  See  #7160

**Comment by quangtrang1111** [comment]
Please can anyone work on this issue?
I cannot trace tre bug with exception. At least we should have a workaround to catch this exception we cannot let the app crash in the end user.

**Comment by sjb-sjb** [comment]
Copying this in here as the other issue is closed -- 
Here's another version, and as minimal as one can imagine. It is synchronous, so, the problem is not only in async methods. 

Use the "Blank App, Packaged (WinUI 3 in Desktop)" template with the Visual Studio configuration copied below. Edit the OnLaunched method in App.xaml.cs as follows:

protected override void OnLaunched(Microsoft.UI.Xaml.LaunchActivatedEventArgs args)
{
    this.UnhandledException += this.App_UnhandledException;
    throw new InvalidOperationException("test");
    //m_window = new MainWindow();
    //m_window.Activate();
}

private void App_UnhandledException(object sender, Microsoft.UI.Xaml.UnhandledExceptionEventArgs e)
{
    System.Diagnostics.Debug.WriteLine("tested");
}
Expected: App_UnhandledException is invoked.

Actual: App_UnhandledException is not invoked, and the program crashes with the message "An unhandled Win32 exception occurred in [15028] Test.exe" in a window that asks you to attach a debugger.

--
Microsoft Visual Studio Community 2022
Version 17.2.0
VisualStudio.17.Release/17.2.0+32505.173
Microsoft .NET Framework
Version 4.8.04084

Installed Version: Community

Visual C++ 2022 00482-90000-00000-AA995
Microsoft Visual C++ 2022

ASP.NET and Web Tools 2019 17.2.388.21846
ASP.NET and Web Tools 2019

Azure App Service Tools v3.0.0 17.2.388.21846
Azure App Service Tools v3.0.0

C# Tools 4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools 1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger 1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager 6.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

TypeScript Tools 17.0.10418.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools 4.2.0-4.22252.24+47cdc16a21bbb8a4aadfb666b011e2059e1be5d2
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools 17.1.0-beta.22178.3+6da0245a7ce4bb8483b8d1f2993c8ecaea967ad9
Microsoft Visual F# Tools

Visual Studio IntelliCode 2.2
AI-assisted development for Visual Studio.

**Comment by dojo90** [comment]
I have the problem that XAML exceptions are not passed on.

```cs
public class FooBinding : MarkupExtension
{
	public PropertyPath Path { get; set; }
	
	protected override object ProvideValue(IXamlServiceProvider serviceProvider)
	{
		// get destination property infos
		if (serviceProvider.GetService(typeof(IProvideValueTarget)) is IProvideValueTarget provideValueTarget
			&& provideValueTarget.TargetProperty is ProvideValueTargetProperty targetProperty
			&& provideValueTarget.TargetObject is FrameworkElement frameworkElement)
		{
			// set default value
			switch (targetProperty.Name)
			{
				case nameof(frameworkElement.Visibility):
					return Visibility.Collapsed;
				default:
					throw new Exception($"unknown property type '{targetProperty.Name}' for {nameof(FooBinding)}");
			}
		}
		return base.ProvideValue(serviceProvider);
	}
}
```

```xaml
<FooControl Tag="{home:FooBinding Path=MyViewModel.MyProperty}"/>
```

![grafik](https://user-images.githubusercontent.com/17551597/179469551-ad3a290d-1a8c-48dc-8b65-a1389ff9f6f6.png)

**Comment by mattjohnsonpint** [comment]
It's worth pointing out that `AppDomain.CurrentDomain.UnhandledException` *does* fire for exceptions on background threads, even though exceptions on the main UI thread only fire on `Microsoft.UI.Xaml.Application.Current.UnhandledException`.

So the workaround is to hook both.

**Comment by Scottj1s** [comment]
App.UnhandledException fix will be available in Windows App SDK 1.2 Preview 2

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK v1.2.220930.4-preview2` has been released which fixes this issue.
		
Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2-preview2/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.220930.4-preview2)

**Comment by k563** [comment]
Sorry guys, this is only a partial fix. My experiments show that Exceptions still don't get caught by 'App.UnhandledException' if they are thrown from a method such as an override of App.OnLaunched, or a MainWindow.Activated event handler. However, an exception thrown from a UI event handler eg in response to a button click, is now caught as expected so at least that's an improvement. I've updated to the preview2 SDK and to the 1.2-preview2 runtime - is there anything else I need to do for this to work properly ?

**Comment by k563** [comment]
Here's a little app that illustrates how 'App.UnhandledException' still only works partially in SDK1.2-preview2 :

https://github.com/k563/WinUI3_UnhandledExceptionTestApp

Maybe there's still time for the WinUI team to address this show-stopper before the 1.2 release ?

**Comment by Scottj1s** [comment]
@k563 Thank you for the feedback and the repro - investigating!

**Comment by Scottj1s** [comment]
@k563 The repro project was very helpful and reminded me of several loose ends I neglected to tie up.  I've captured these in several new issues:
[App_UnhandledException's UnhandledExceptionEventArgs.Exception can only be fetched once - should be cached](https://github.com/microsoft/CsWinRT/issues/1258)
[Do_Abi_* event/callback handlers should wrap invocations with RoReportUnhandledError](https://github.com/microsoft/CsWinRT/issues/1259)
[When debugging, an exception-invoked FailFast does not terminate, but allows the app to continue in a bad state](https://github.com/microsoft/microsoft-ui-xaml/issues/7812)

Please note the workarounds for the first two issues, which should largely unblock you until these are resolved.

**Comment by Scottj1s** [comment]
Closing this issue, having captured remaining issues

**Comment by Scottj1s** [comment]
@gabbybilka Can we see to it that the workarounds noted above are relnoted for the 1.2 release?

**Comment by Scottj1s** [comment]
Issue has been fixed internally and will be included in v1.3

**Comment by gabbybilka** [comment]
:tada:`Microsoft.WindowsAppSDK.1.2.221209.1` has been released which fixes this issue.

Handy links:
* [Release Notes](https://aka.ms/windowsappsdk/1.2/1.2.221209.1/release-notes)
* [Official Nuget Release](https://www.nuget.org/packages/Microsoft.WindowsAppSDK/1.2.221209.1)

**Comment by Inrego** [comment]
I am still experiencing a crash in my Windows MAUI app, that I for the life of me can't get any exception details of.
In `App` constructor, I am hooking up these events:

        this.UnhandledException += App_UnhandledException;
        System.AppDomain.CurrentDomain.UnhandledException += CurrentDomain_UnhandledException;
        Microsoft.UI.Xaml.Application.Current.UnhandledException += CurrentOnUnhandledException;
        AppDomain.CurrentDomain.FirstChanceException += CurrentDomain_FirstChanceException;

The app initializes fine, but under certain circumstances, the app crashes when I navigate to a specific page.
Those circumstances cannot be reproduced on my development machine, it only happens on some laptops.

Either way, each of the above event handlers will write the exception to a txt file. But none of them fire.
I went down this path, because Sentry didn't pick up the exceptions either. It's really frustrating to work with.

I am using .NET 8 MAUI, which depend on Microsoft.WindowsAppSDK v1.3.230724000

**Comment by sjb-sjb** [comment]
@Inrego  check out #8885 linked above. If it also applies to MAUI then the fix is to wrap delegates in try / catch before dispatching them to the UI thread, and call the unhandled event handler yourself in the catch clause.

**Comment by Inrego** [comment]
After all this debugging, I have try/catch everywhere related to the crash. Nothing is caught, it still crashes.
If connected with TeamViewer to the PC, it doesn't crash. It's such a weird thing.
I'm at a place where I can remove the crash by removing some UI elements. But adding just a `<Label Text="Test" />` will make the crash happen again.
On some PCs, it helps to maximize the window, on others not.
Only thing I get when it crashes, is an entry in event viewer, which doesn't give me much:

> Navn på program med fejl: Iris.MAUI.exe, version: 1.0.0.0, tidsstempel: 0x65a80000
> Navn på modul med fejl: Microsoft.ui.xaml.dll, version: 3.1.3.0, tidsstempel: 0xea4b25b7
> Undtagelseskode: 0xc0000005
> Forskydning med fejl 0x00000000009327cd
> Proces-id 0x0x1A68
> Programmets starttidspunkt 0x0x1DA7083B99B077A
> Programsti: C:\Program Files\WindowsApps\c8389d99-ee7a-4c64-a3f0-6bd7acefbbb5_1.0.38.0_x64__970kh9ves4628\Iris.MAUI.exe
> Modulsti: C:\Program Files\WindowsApps\Microsoft.WindowsAppRuntime.1.3_3000.934.1904.0_x64__8wekyb3d8bbwe\Microsoft.ui.xaml.dll
> Rapport-id: e9a003c6-d115-43da-9395-aef0515ccecd
> Fuldt navn på program med fejl: c8389d99-ee7a-4c64-a3f0-6bd7acefbbb5_1.0.38.0_x64__970kh9ves4628
> Relativt program-id for program med fejl: App

Sorry it's in danish, but it's an end-user PC as I am not able to replicate the crash on any of my PCs.

**Comment by StephenCleary** [comment]
@Inrego If your customer is open to this, you could try running [ProcDump](https://learn.microsoft.com/en-us/sysinternals/downloads/procdump) with the `-e` command line parameter, and then open the `dmp` file in Visual Studio. You should be able to get a call stack at least.

**Comment by Inrego** [comment]
Thanks, I'll keep that in mind. I finally found a fix. A horizontal CollectionView seems to have been the culprit.
Changing it to RadListView from Telerik at least seems to have stopped the crash for now.

What boggles my mind is why it only crashed on some PC's. And why a TeamViewer connection to the PC almost always prevented the crash. And sometimes maximizing the window prevented the crash.

Anyhoo, after a few days of trying different things, it finally seems crash-free now. Our next app def. won't be in MAUI.

**Comment by k563** [comment]
In the WinUI Community Call yesterday, Scott illustrated how in 1.5 it's possible to debug the underlying WinUI code and see where the exception is being thrown. He showed an example where the UnhandledException event was not being fired if the exception was related to a 'NaN', whereas an error due to an unexpected negative value *did* raise that event. It seems that there are still a few places like this in the WinUI code which have yet to be cleaned up. So this kind of silent crash will be possible in *any* WinUI app, and it's not necessarily MAUI's fault. A desktop app or an Uno app would be equally susceptible ?

**Comment by Inrego** [comment]
I'm aware it's a WinUI issue. But MAUI hasn't been great all around. So for our next app, we'll probably look at choices outside the .NET ecosystem

**Comment by vsvsav** [comment]
The latest WinUI3 + .NET9 has the same situation - App.UnhandledException only catches exceptions from synchronous methods.
And it's interesting, that app crashes for
[RelayCommand]
public Task FooAsync(){...}
but app does not crash for 
ICommand  FooCommand { get; } 
FooCommand = new RelayCommand(  () => _ = FooAsync());

**Comment by vsvsav** [comment]
updated

**Comment by jeremy-visionaid** [comment]
@vsvsav Yup, also seeing this. Looks like it has regressed in 1.7.250310001 and later (1.6.250602001 works as expected)

**Comment by bogdan-patraucean** [comment]
@jeremy-visionaid that regression issue was closed as fixed, but I found a more specific scenario that still doesn't work: https://github.com/microsoft/microsoft-ui-xaml/issues/11253
