### ISSUE TITLE
winui 3 apps scrollbar doesn't work with mouse wheel

### ISSUE THREAD

**Issue by vsfeedback** [microsoft/microsoft-ui-xaml#5470]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/winui-3-apps-scrollbar-doesnt-work-with/1471992)._

---
[severity:I'm unable to use this version]
i can't scroll throw my controls like a listview or webview 2 in a new created app even "winui 3 controls gallery" app doesn't scroll with the mouse wheel the scrollbar only work when i drag it with the cursor

---
#### Feedback Bot on 7/11/2021, 08:02 PM: 

<p>We have directed your feedback to the appropriate engineering team for further evaluation. The team will review the feedback and notify you about the next steps.</p>

---
### Original Solutions
(no solutions)

**Comment by StephenLPeters** [comment]
Similar to https://github.com/microsoft/microsoft-ui-xaml/issues/5299 , however we haven't seen any issues with listview. Can the author provide a gif of the UI which isn't working or more information about what environment the app is in to help with debugging.

**Comment by ahmed-abdelrazek** [comment]
![image](https://user-images.githubusercontent.com/7858946/125732485-5cffb2d0-0856-4af1-91e2-19fd6d75d108.png)

![image](https://user-images.githubusercontent.com/7858946/125732536-9046fac0-2801-4b62-8b48-24c73c542007.png)

![image](https://user-images.githubusercontent.com/7858946/125732692-615c736c-b06d-4156-a391-60c9a1a75f99.png)

![image](https://user-images.githubusercontent.com/7858946/125732804-feee2fe2-c799-4d16-8afa-c947d6012116.png)

https://youtu.be/w7e3_z8P53E @StephenLPeters

**Comment by ahmed-abdelrazek** [comment]
@msft-github-bot bad bot

**Comment by ahmed-abdelrazek** [comment]
🙄🙄🙄🙄🙄🙄🙄

**Comment by ahmed-abdelrazek** [comment]
![image](https://user-images.githubusercontent.com/7858946/127537926-494822a8-1dc6-4753-b256-0f861d96af8f.png)

![image](https://user-images.githubusercontent.com/7858946/127538004-f4e596ad-1459-4577-8577-117cf39a200b.png)

![image](https://user-images.githubusercontent.com/7858946/127538254-70953d56-dfdd-45c7-a0f1-97bf478e85a8.png)

![image](https://user-images.githubusercontent.com/7858946/127538831-d720ca67-db6a-4a39-b29c-04f88146cf90.png)

![image](https://user-images.githubusercontent.com/7858946/127538890-983112c7-08b9-4cd4-bd40-1c87748a2550.png)

![image](https://user-images.githubusercontent.com/7858946/127538989-2e9f0ead-3e36-4d1b-918f-cf4391edd727.png)

![image](https://user-images.githubusercontent.com/7858946/127539105-db304929-e30e-4bd1-a68e-274986222f51.png)

https://youtu.be/Seu88_UEOhw

i don't think i can be any more clear here

**Comment by StephenLPeters** [comment]
Thank you!! Sorry about the Bot, it doesn't recognize you as the author because the issue originated from VSFeedback... sorry about that.

**Comment by StephenLPeters** [comment]
@codendone and @JJBrychell looks like a regression (doens't repro on an old Preview2 version of the XCG I have lying around) where these mouse wheel events aren't making it to the scroll viewer.

@beervoley from the controls side.

**Comment by codendone** [comment]
@feisu Any idea why some mouse wheels don't work? I see this working fine on 0.8 with my mouse. ScrollViewer also should have the input going directly to DManip.

**Comment by feisu** [comment]
Without a repro, it's hard to say what's going on here.

@ahmed-abdelrazek do you have another mouse you can try and see if it repros? 

Also can you file a feedback through Feedback Hub with a short repro? Please pick Input \ Mouse category and then click ReCreate My Problem to collect the trace. Then share with us the link to the feedback. This trace may not be enough to root cause the issue but should give us an idea of where wheel input is going and lead to right direction.

**Comment by ahmed-abdelrazek** [comment]
@feisu none of them work
![image](https://user-images.githubusercontent.com/7858946/127712186-5969a7c5-643f-4182-a473-20ac8904c381.png)

the feedback hub reports one with usb/mouse and the other with input/mouse
https://aka.ms/AAdboq4
https://aka.ms/AAdasxq

**Comment by ahmed-abdelrazek** [comment]
any progress?!

**Comment by akilarajesh1313** [comment]
@ahmed-abdelrazek We don't have an answer for you yet but we're currently investigating. Thank you for your patience!

**Comment by feisu** [comment]
Looking at the traces, a lot of mouse wheel messages were dropped because they were consumed by low level mouse hooks. This process XMouseButtonControl.exe has a hook and looks most suspicious.

@ahmed-abdelrazek can you stop XMouseButtonControl.exe and try it again?

**Comment by ahmed-abdelrazek** [comment]
> 
> 
> Looking at the traces, a lot of mouse wheel messages were dropped because they were consumed by low level mouse hooks. This process XMouseButtonControl.exe has a hook and looks most suspicious.
> 
> @ahmed-abdelrazek can you stop XMouseButtonControl.exe and try it again?

that's actually fixed the issue but why it occurs with winui 3 apps only?

**Comment by feisu** [comment]
I'm glad that fixed the issue.

That would be a good question to the developer of X-Mouse Button Control. It changes mouse input globally on system level through low level hooks and it's really easy to screw up input in unexpected places like this. It may just be a bug in their code.

Curious - what do you use it for? Does wheel have some special function with that app?

**Comment by ahmed-abdelrazek** [comment]
i just use it to change what the side buttons do without the manufacturer bloated limited software 
![image](https://user-images.githubusercontent.com/7858946/132072991-eabc2d6c-8093-4960-b498-971fdcb9a1e0.png)

**Comment by feisu** [comment]
I see. That makes sense.

If their code was open source, I might be able to take a look and try to debug but it appears to be closed source. You may want to consider reporting the issue to the developers and see if they can debug it.

**Comment by ahmed-abdelrazek** [comment]
will do and thank you very much

**Comment by feisu** [comment]
You are welcome. Thank you for reporting the issue!

**Comment by ahmed-abdelrazek** [comment]
@feisu disabling `Make scroll wheel scroll window under cursor` from the app `Settings` fixes the problem as mentioned here https://forums.highrez.co.uk/viewtopic.php?p=22684#p22684

**Comment by NCTrung** [comment]
Change mouse setting
![Screenshot 2023-02-05 085048](https://user-images.githubusercontent.com/7163040/216797444-ac8c987b-9ca2-4b22-9b61-0b3bb8b3a00e.jpg)

**Comment by ahmed-abdelrazek** [comment]
> This issue, with WinUI 3 not being able to scroll using the mouse wheel on some computers, still persists so this bug shouldn't have been closed. The above mouse setting change described by @NCTrung works, but still is just a workaround.

what are you talking about?
the mouse setting mentioned above is not a workaround that the setting that make this feature work in the first place
you would only have a problem if it was enabled but still didn't scroll inactive windows when hovering over them

**Comment by kjean667** [comment]
The problem in WinUI is that even though the application has focus, it still does not scroll when using the mouse wheel. Other applications works fine, but WinUI-applications does not. Changing the setting makes mouse wheel scrolling work in WinUI applications but it should have been working even without changing the setting.
What I am saying is that there is a difference between how WinUI works and other applications work regarding the mouse wheel scroll functionality. On some computers, the mouse wheel is useless in WinUI, regardless of application focus state, if the setting is not changed.

**Comment by ahmed-abdelrazek** [comment]
> The problem in WinUI is that even though the application has focus, it still does not scroll when using the mouse wheel. Other applications works fine, but WinUI-applications does not. Changing the setting makes mouse wheel scrolling work in WinUI applications but it should have been working even without changing the setting. What I am saying is that there is a difference between how WinUI works and other applications work regarding the mouse wheel scroll functionality. On **some** computers, the mouse wheel is useless in WinUI, regardless of application focus state, if the setting is not changed. However, on most computers the mouse wheel works as expected even in WinUI.

there alot of differences indeed between winui 3 and others like win32 and uwp in this case you might want to open a new issue 
as you can see here my problem here was cause because of a third party app and has been solved

**Comment by lbdalmendrayMyradar** [comment]
Hi, I found this same issue. Basically, I can't mouse-wheel-scroll when "Scroll inactive windows when hovering over them" is disabled on any new simple active WinUI 3 Desktop app. But other type of apps like WPF are working correctly. Please watch this attached video. Do you know any dev-coding fix, different from manually enabling the "Scroll inactive windows when hovering over them" toggle button? Thanks 😄  

https://github.com/user-attachments/assets/9b99b820-1e4d-4a3b-a651-eee2c10ba4b1

**Comment by Saplonily** [comment]
This issue is still present today. (Tested in winui3 gallery and powertoys, win10)
