### ISSUE TITLE
Webview2: Clicking a select element not popping up the drop down list

### ISSUE THREAD

**Issue by koenvd** [microsoft/microsoft-ui-xaml#5570]
**Steps to reproduce the bug**
1. Create basic WinUI3.0 desktop app only embedding a Webview2 control
2. Set the source of the control to https://localhost:8080
3. Serve on https://localhost:8080 a basic index.html page with a select element
4. Start the app
5. Click the select element
6. Notice the dropdown element doesn't pop up. There's a slight flickering effect visible and the drop down closes again. 

**Expected behavior**
Drop down list should pop up

**Screenshots**
This is screenshot from Edge browser
![edge_select](https://user-images.githubusercontent.com/15209987/127312659-7e2ff80b-0771-456a-9da8-bf7f1a0d6c1b.png)

This is screenshot from the app
![winUI-select](https://user-images.githubusercontent.com/15209987/127313565-c4bd506d-7874-4897-9e07-a588f45b83f7.png)

**Version Info**
Packaged WinUI3.0 Desktop app, WindowsAppSDK 8.0

NuGet package version: 
WinUI 3 - Windows App SDK 0.8: 0.8.0

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|                        |Yes                   |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            | Yes  |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**
This works both in Edge and a Win32 C++ app (taken from here https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample) so seems related to WinUI3.0. Hence I'm reporting it here instead of on the Webview2 feedback repo.

**Comment by StephenLPeters** [comment]
@codendone and @krschau FYI

**Comment by krschau** [comment]
Hi @koenvd, thanks for reporting this! I can repro it and will continue to investigate.

**Comment by koenvd** [comment]
Nice @krschau! 

Just came into mind this is probably related to the other issue I filled today: https://github.com/microsoft/microsoft-ui-xaml/issues/5615

Probably if you click the select item, the window will loose focus, which closes the drop down again. The linked ticket illustrates the issue for a button. But probably the same will happen for a select control.

Otherwise I give that a try tomorrow and will give another update.

**Comment by koenvd** [comment]
Seems indeed the windows looses focus when clicking the select button:
![Screenshot 2021-08-04 101958](https://user-images.githubusercontent.com/15209987/128147627-e9ae6d51-867c-44af-998c-0b860e6b4390.png)

Gist here: https://gist.github.com/koenvd/d1a4877e3189276da8b9a0b4d0dcc4d4

So this one might be fixed by #5615 .

Leaving it up to you if you want to keep both issues open.

**Comment by koenvd** [comment]
![Screenshot 2021-09-08 212154](https://user-images.githubusercontent.com/15209987/132572248-865a547b-90fd-4ca8-8e19-3ae5b9cb41b6.png)

This seems to be working fine as well in an UWP app with the backported Webview2 in the WinUI2.7 prerelease.  

Just wondering if you have a rough idea when this would be fixed in WinUI3.0 @krschau @codendone ?

**Comment by koenvd** [comment]
FYI but still seems to fail with WindowsAppSdk v1.0.0-preview1.

**Comment by ispysoftware** [comment]
Also happening on 1.0.0-experimental1. Is anyone working on this? A web browser control that doesn't support Select isn't a whole lot of use..

**Comment by koenvd** [comment]
Still happening on WindowsAppSdk v1.0.0-preview3 as well.

**Comment by ispysoftware** [comment]
I'm not sure if it's related but we also have a major issue with capturing the mouse using navigator.xr.requestSession
- the mouse pointer seems to be half captured, tracking runs at 50% movement/speed than it does in Edge or Chromium and the mouse pointer is periodically reset, like it's fighting something for focus.

This is it working in Edge:
https://ispyrtcdata.blob.core.windows.net/downloads/capture_edge.mp4

Not working in WebView2:
https://ispyrtcdata.blob.core.windows.net/downloads/capture_webview2.mp4

**Comment by ispysoftware** [comment]
@krschau is this going to be addressed any time soon? For such a critical issue it's very concerning that nothing has been done about it for 3+ months - we're putting a large amount of effort into our app and WebView2 is a critical part of it and no  update to this ticket is quite a massive danger sign. Just need to know if/ when it will be addressed or if we need to re-tool.

**Comment by krschau** [comment]
@ispysoftware I'm sorry that this has taken so long. Unfortunately the fix won't make it to the 1.0 release, but it should be in 1.1. (Just so you know, we don't use the Assignee field in GitHub for most WinUI 3 items, but owners are assigned elsewhere.)

**Comment by ispysoftware** [comment]
Thanks. Do you know when the 1.1 release is expected to ship?

**Comment by ilovepumpkin** [comment]
@krschau is there any workaround for this issue? Our project will be released very soon, now this issue is a stop-shipping issue for us. We have no time to wait till 1.1 release is shipped. Please help!

**Comment by krschau** [comment]
This will be fixed in the next 0.8 and 1.0 previews, but I can't really give more detail than the [roadmap](https://github.com/microsoft/microsoft-ui-xaml/blob/main/docs/roadmap.md#winui-3-feature-roadmap) on timing for those.

**Comment by gabbybilka** [comment]
Fixed in Windows App SDK 1.0.1, check out the [release notes](https://github.com/microsoft/WindowsAppSDK/discussions/2291) for more info.

**Comment by alshival** [comment]
This issue is still occurring in WindowsAppSDK v 1.5.240404000.
