### ISSUE TITLE
ElementName bindings don't work inside ItemsRepeater DataTemplate

### ISSUE THREAD

**Issue by JohnnyWestlake** [microsoft/microsoft-ui-xaml#560]
**Describe the bug**
As described, using ElementName bindings inside the datatemplate of an Items Repeater appears to fail. The same template inside anything that inherits ItemsControl works fine.

**Steps to reproduce the bug**

1. Create an ItemsRepeater
2. Inside it's DataTemplate, use an elementname binding to something outside of the ItemsRepeaters VisualTree.
3. Observe infinite nothingness

**Expected behavior**
It works.

**Version Info**
O.S. 18362.53
MinVersion SDK: 17134
MaxVersion SDK: 17763

NuGet package version: 
2.1.190405004

**Comment by JohnnyWestlake** [comment]
Is there any follow up on this? Almoat 2 years later and it seems like a pretty big thing to be missing, especially if we want ItemsRepeater to replace ListView/GridView, where it works fine.

**Comment by crodeheaver** [comment]
I'm also running into the same issue. Are there any work arounds for the issue?

**Comment by LanceMcCarthy** [comment]
@jevansaks I can confirm this bug is still present. I've tried both `ElementName` and `RelativeSource` bindings, nothing seems to be able to change the DataContext of that binding as long as it's inside the DataTemplate.

**Comment by jevansaks** [comment]
I'm sorry to hear that. @RealTommyKlein @ranjeshj any ideas?

**Comment by agneszitte-nventive** [comment]
I'm also running into the same issue even with the latest versions.

**Comment by michael-hawker** [comment]
This is a pain see folks hit trying to implement MVVM patterns.

Someone recently created a nice isolated repro of the ItemsControl/ItemsRepeater difference here on [one of our bugs](https://github.com/CommunityToolkit/Labs-Windows/issues/445#issuecomment-1596302071), thanks to @leoshusar:

```xml
<ItemsControl ItemsSource="{x:Bind ViewModel.Items}">
    <ItemsControl.ItemTemplate>
        <DataTemplate x:DataType="x:String">
            <ComboBox Name="cmbTest1">
                <ComboBoxItem Content="TextBlock" Tag="TextBlock" />
                <ComboBoxItem Content="HyperLink" Tag="HyperLink" />
                <i:Interaction.Behaviors>
                    <ic:EventTriggerBehavior EventName="SelectionChanged">
                        <ic:EventTriggerBehavior.Actions>
                            <ic:InvokeCommandAction Command="{Binding ElementName=PageRoot, Path=ViewModel.Test1Command}" CommandParameter="{Binding ElementName=cmbTest1}" />
                        </ic:EventTriggerBehavior.Actions>
                    </ic:EventTriggerBehavior>
                </i:Interaction.Behaviors>
            </ComboBox>
        </DataTemplate>
    </ItemsControl.ItemTemplate>
</ItemsControl>

<ItemsRepeater Grid.Column="1" ItemsSource="{x:Bind ViewModel.Items}">
    <ItemsRepeater.ItemTemplate>
        <DataTemplate x:DataType="x:String">
            <ComboBox Name="cmbTest1">
                <ComboBoxItem Content="TextBlock" Tag="TextBlock" />
                <ComboBoxItem Content="HyperLink" Tag="HyperLink" />
                <i:Interaction.Behaviors>
                    <ic:EventTriggerBehavior EventName="SelectionChanged">
                        <ic:EventTriggerBehavior.Actions>
                            <ic:InvokeCommandAction Command="{Binding ElementName=PageRoot, Path=ViewModel.Test2Command}" CommandParameter="{Binding ElementName=cmbTest2}" />
                        </ic:EventTriggerBehavior.Actions>
                    </ic:EventTriggerBehavior>
                </i:Interaction.Behaviors>
            </ComboBox>
        </DataTemplate>
    </ItemsRepeater.ItemTemplate>
</ItemsRepeater>
```

https://github.com/CommunityToolkit/Labs-Windows/assets/13891066/aa78f395-23d7-440f-b755-13884730cca8

[App22.zip](https://github.com/CommunityToolkit/Labs-Windows/files/11782806/App22.zip)

FYI @bpulliam

**Comment by AndrewKeepCoding** [comment]
Here's a sample app project with a [workaround](https://github.com/AndrewKeepCoding/BindingFromItemTemplateSample) that works for me.

If you want to see it in action, here's a [video](https://youtu.be/vVmtt89G8q8).

**Comment by LeonSpors** [comment]
Any ETA for this issue?

**Comment by ranjeshj** [comment]
Not sure what ItemsControl is doing to make this work. Here is a simpler repro

```
    <StackPanel>
        <Button x:Name="button" Content="MyButton" />
        <ItemsRepeater x:Name="repeater">
            <ItemsRepeater.ItemTemplate>
                <DataTemplate>
                    <Button Content="{Binding ElementName=button, Path=Content}" />
                </DataTemplate>
            </ItemsRepeater.ItemTemplate>
        </ItemsRepeater>
    </StackPanel>

    repeater.ItemsSource = Enumerable.Range(0, 10);
```

There is a small typo in the repro steps above - cmbTest2 does not exist.

**Comment by JohnnyWestlake** [comment]
I would presume it is a XAML namescope issue as ElementName requires the element to be in the same namescope, but as we can't debug the namescoping externally someone MS related will have to track it down. But given how "non-traditional" ItemsRepeater layouts are handled compared to normal Xaml ItemsControls I would imagine there's an obvious break point.

**Comment by ghost1372** [comment]
@bpulliam  any news? i can not use new control ItemsView because of this bug.

**Comment by michael-hawker** [comment]
> Here's a sample app project with a [workaround](https://github.com/AndrewKeepCoding/BindingFromItemTemplateSample) that works for me.

I wouldn't call adding `Loading` events to set properties in code-behind as a workaround to a binding issue; sure it may work, but it's so much extra code for each UIElement and property compared to the original binding.

x:Bind/Binding is just broken in so many of these scope scenarios which adds so much friction in developing with XAML (see #2508). If a bit of focus could be spent in this space, it could make the platform a dream to work with.

**Comment by ghost1372** [comment]
@duncanmacmichael  any new for this?

**Comment by AndrewKeepCoding** [comment]
> I wouldn't call adding Loading events to set properties in code-behind as a workaround to a binding issue; sure it may work, but it's so much extra code for each UIElement and property compared to the original binding.

@michael-hawker 
I totally agree with you. It's not clean and it's too much extra code for a simple binding. I just had a case that needed to make it work.
This issue and #2508 are getting very old and I'm concerned if they will ever get fixed.

**Comment by duncanmacmichael** [comment]
> @duncanmacmichael any new for this?

I'm honestly not sure since engineering handles bugs directly, but it looks like @ranjeshj is working on this so we can ask him for an update. :)

**Comment by ghost1372** [comment]
@ranjeshj  any update?

**Comment by ghost1372** [comment]
@llongley  fixed in v1.5 or v1.4.5?

**Comment by codendone** [comment]
@ghost1372 This is fixed in v1.5.

**Comment by DominicMaas** [comment]
This doesn't appear to be fixed? (1.5.240404000), anyone else here still encountering the issue?

**Comment by ranjeshj** [comment]
The simple repro I had works on latest 1.5 release. https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-1699459932. 

@DominicMaas  is your repro different? can you file a new issue with your repro (preferably small/standalone)

**Comment by ghost1372** [comment]
> The simple repro I had works on latest 1.5 release. [#560 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-1699459932).
> 
> @DominicMaas is your repro different? can you file a new issue with your repro (preferably small/standalone)

Please test with this repro
https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-1601316553

**Comment by AathifMahir** [comment]
Still Facing this Issue on Windows App SDK v1.5.240404000

**Comment by VigneshVoid** [comment]
Same here still facing the issue.

**Comment by AndrewKeepCoding** [comment]
I run my [repro project](https://github.com/AndrewKeepCoding/BindingFromItemTemplateSample) with all v1.5.x available versions but none of them worked.

**Comment by leohu1** [comment]
> @RealTommyKlein helped narrow this down to this code -
> 
> https://github.com/microsoft/microsoft-ui-xaml/blob/7198c4e69019516fb08ecb3937492ffff5fe9702/dxaml/xcp/dxaml/lib/FrameworkElement_partial.cpp#L1169
> ItemsRepeater is not an ItemsHost so it is being skipped from this check.

The same thing happens to ItemsView, I believe.

**Comment by ghost1372** [comment]
it seems that issue fixed in v1.6-exp2
![vvv](https://github.com/user-attachments/assets/fe185636-8be5-422f-9194-4dbd5a1917d5)

**Comment by abdes** [comment]
Same issue still there when you use the ItemsRepeater inside a ControlTemplate in a style. Binding with a relative source to the templatedparent does not work.

**Comment by weitzhandler** [comment]
[Comment from AndrewKeepCoding](https://github.com/microsoft/microsoft-ui-xaml/issues/560#issuecomment-1627544604):
> Here's a sample app project with a workaround that works for me.

I ended up using this nasty workaround to achieve it the ugly way. Eww!

```csharp
private void TreeView_Expanding(TreeView sender, TreeViewExpandingEventArgs args)
{
    var dataItem = args.Item;
    var node = args.Node;

    var container = sender.ContainerFromNode(node) as TreeViewItem;
    if (container is not null)
    {
        container.DataContext = this;
    }
}
```
