### ISSUE TITLE
CommandBarFlyout primary and secondary flyouts are misaligned when flow direction is set to RTL

### ISSUE THREAD

**Issue by winston-de** [microsoft/microsoft-ui-xaml#5694]
**Describe the bug**

**Steps to reproduce the bug**

1. Create app with CommandBarFlyout
2. Set FlowDirection to rtl
3. Open the CommandBarFlyout
4. Primary and secondary flyouts are misaligned

**Expected behavior**
Primary and secondary flyouts should line up like in ltr

**Screenshots**

![image](https://user-images.githubusercontent.com/59544401/129489735-387b6f42-87a2-413c-ac57-c3654ff41afb.png)

**Version Info**

2.6.1
NuGet package version: 

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|  |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (22000.132)              | yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Additional context**

**Comment by llongley** [comment]
Thanks for the report!  This is a known issue that we've already fixed internally.

**Comment by winston-de** [comment]
Great, thanks!

**Comment by winston-de** [comment]
> Thanks for the report! This is a known issue that we've already fixed internally.

@llongley This issue still seems to be present in winui 2.7. Is there an eta on when this fix will be released?
