### ISSUE TITLE
Microsoft.UI.Xaml.Media.PointCollection throws TypeLoadException

### ISSUE THREAD

**Issue by nordleif** [microsoft/microsoft-ui-xaml#5782]
**Describe the bug**
You cannot create a Polygon from code. XAML works. 
App throws:
TypeLoadException: Could not load type 'ABI.Windows.Foundation.Point' from assembly 'Microsoft.WinUI, Version=3.0.0.0, Culture=neutral, PublicKeyToken=de31ebe4ad15742b'.

**Steps to reproduce the bug**
```
var polygon = new Microsoft.UI.Xaml.Shapes.Polygon();
 polygon.Points.Add(new Point(10, 110));

var collection = new Microsoft.UI.Xaml.Media.PointCollection();
```

1. Create new Blank App, Packaged with WAP (WinUI 3 in Desktop).
2. Open MainWindow.xaml.cs.
3. Create polygon with points.
4. Run code

**Expected behavior**
The code should work like xaml
`<Polygon Points="10,110 60,10 110,110" Fill="Blue" />`

**Screenshots**
![image](https://user-images.githubusercontent.com/425306/131110137-fb994251-6f95-40ed-9b27-8eb4bbf3835b.png)

**Version Info**

NuGet package version: 
Microsoft.WindowsAppSDK.WinUI 1.0.0-experimental1

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
|                         |  Yes                    |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | <Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                | |

**Additional context**

**Comment by Marv51** [comment]
I think this is the same issue as microsoft/cswinrt#971

**Comment by StephenLPeters** [comment]
I think this requires one of the helper classes.. @MikeHillberg and @codendone thoughts?

**Comment by Marv51** [comment]
This was fixed, but no update has been released yet. (See https://github.com/microsoft/WindowsAppSDK/discussions/1436)

**Comment by DevakumarDhanapoosanam** [comment]
@Marv51 Still facing same error reported for PointCollection in latest. Can you please check on this issue fix were moved in latest version?

**Comment by Marv51** [comment]
As I said: CsWinRT has fixed this, but no update has been released yet. Feel free to upvote that discussion I linked.
