### ISSUE TITLE
CommandBarFlyout has gap between primary and secondary commands when secondary are shown above.

### ISSUE THREAD

**Issue by eugenegff** [microsoft/microsoft-ui-xaml#5833]
**Describe the bug**
CommandBarFlyout has gap between primary and secondary commands when secondary are shown above.

**Steps to reproduce the bug**
1. VS2019, new blank C++/CX app, target 19041, min target 17763
2. Add button aligned to the bottom of page with attached CommandBarFlyout
```
    <Page.Resources>
        <CommandBarFlyout x:Name="CommandBarFlyout1">
            <AppBarButton Label="Share" Icon="Share" ToolTipService.ToolTip="Share" />
            <AppBarButton Label="Save" Icon="Save" ToolTipService.ToolTip="Save" />
            <AppBarButton Label="Delete" Icon="Delete" ToolTipService.ToolTip="Delete" />
            <CommandBarFlyout.SecondaryCommands>
                <AppBarButton x:Name="ResizeButton1" Label="Resize"/>
                <AppBarButton x:Name="MoveButton1" Label="Move"/>
            </CommandBarFlyout.SecondaryCommands>
        </CommandBarFlyout>
    </Page.Resources>

    <Button VerticalAlignment="Bottom" Content="Show Flyout" Flyout="{StaticResource CommandBarFlyout1}"/>
```
3. Press button - flyout is shown with gap between primary and secondary commands
4. Press button again - flyout is shown without gap between primary and secondary commands

**Expected behavior**
CommandBarFlyout should show secondary commands above primary ones without any gap between

**Screenshots**
![image](https://user-images.githubusercontent.com/34012295/132059681-d13f8468-f448-4e49-ac37-cdd0a89f2926.png)

![image](https://user-images.githubusercontent.com/34012295/132059707-a592727c-d568-4631-a836-57e43126f824.png)

**Version Info**
CommandBarFlyout from both Microsoft.UI.Xaml 2.6.2 and  Windows.UI.Xaml has this bug
Host OS 19043.1165
UWP App, WinUI 2.6.2

Windows app type:
| UWP              | Win32            |
| :--------------- | :--------------- |
| Yes |  |

| Windows version                    | Saw the problem? |
| :--------------------------------- | :-------------------- |
| Insider Build (xxxxx)              |    |
| May 2021 Update (19043)            | Yes   |
| October 2020 Update (19042)        |    |
| May 2020 Update (19041)            |    |
| November 2019 Update (18363)       |    |
| May 2019 Update (18362)            |    |
| October 2018 Update (17763)        |    |
| April 2018 Update (17134)          |    |
| Fall Creators Update (16299)       |    |
| Creators Update (15063)            |    |

| Device form factor | Saw the problem? |
| :----------------- | :--------------- |
| Desktop            | Yes |
| Xbox               |  |
| Surface Hub        |  |
| IoT                |  |

**Comment by eugenegff** [comment]
I suspect that problem is within CommandBar code used inside CommandBarFlyout. From my investigation container for secondary commands measures too large, and then shrinks on first closing. But without CommandBar source code it is hard to move further

**Comment by zhuxb711** [comment]
They just don't want to fix this issue since I mention it on Aug, 2020
[#3209](https://github.com/microsoft/microsoft-ui-xaml/issues/3209)

**Comment by eugenegff** [comment]
New knowledge - the height of the gap is proportional to the count of the secondary commands aka menu items. Seems that CommandBar has code that attempts to predict corresponding height, but does it incorrectly till the first layout. For my menu with 9 secondary items in file CommandBarFlyoutCommandBar.cpp, line 538
```
                m_secondaryItemsRoot.get().Measure({ std::numeric_limits<float>::infinity(), std::numeric_limits<float>::infinity() });
                const auto overflowPopupSize = m_secondaryItemsRoot.get().DesiredSize();
```
I initially got overflowPopupSize == 370 and popup was shown with large gap as on third attached screenshot, and then on second context menu opening overflowPopupSize was 298, i.e. less by 72px, 8px per secondary menu item

**Comment by eugenegff** [comment]
New knowledge - it is AppBarButton in CommandBarFlyout.SecondaryCommands measured as 40px before first showing, becaming 32px on second and following showing attempt. Could be seen and worked around with code like this
```
	[Windows::Foundation::Metadata::WebHostHidden]
	public ref class CommandBarFlyoutItem sealed
		: public Windows::UI::Xaml::Controls::AppBarButton
	{
	public:
		CommandBarFlyoutItem() {}
	protected:
		virtual Windows::Foundation::Size MeasureOverride(Windows::Foundation::Size availableSize) override
		{
			auto sz = __super::MeasureOverride(availableSize);
			sz.Height = 32.0f; // workaround for wrong measured height
			return sz;
		}
	};
```

**Comment by StephenLPeters** [comment]
@eugenegff I beleive this issue has been fixed in windows 11, are you able to verify you don't see the behavior on windows 11?

**Comment by eugenegff** [comment]
latest Windows 11, 10.0.22000.184, problem still exist

![image](https://user-images.githubusercontent.com/34012295/133230418-ea7fd1e1-d9d7-4e3c-9f8c-77ca8d989409.png)

**Comment by eugenegff** [comment]
OTOH, it became less reproducible.

With the repro code in first post it is still reproducible with WUX CommandBarFlyout, but not with MUX 2.6.2 in either ControlsResourcesVersion mode.

In our app bug is still reproducible with MUX 2.6.2 CommandBarFlyout in ControlsResourcesVersion=Version1 mode.

So the bug is definitely still with us.

**Comment by StephenLPeters** [comment]
@eugenegff what scale factor is your display at when you get these repro's?

**Comment by eugenegff** [comment]
> @eugenegff what scale factor is your display at when you get these repro's?

4K monitor, 150% scale. I repeated tests on 100% scale - it does not matter, everything including gap became proportionally smaller.

**Comment by eugenegff** [comment]
> It was AppBarButton in CommandBarFlyout.SecondaryCommands measured as 40px before first showing, becaming 32px on second and following showing attempt. Unfortunately wrong size was already used to calculate overflow popup size. Could be seen and worked around with quick and dirty code like this
> 
> ```
> 	[Windows::Foundation::Metadata::WebHostHidden]
> 	public ref class CommandBarFlyoutSecondaryItem sealed
> 		: public Windows::UI::Xaml::Controls::AppBarButton
> 	{
> 	public:
> 		CommandBarFlyoutSecondaryItem() {}
> 	protected:
> 		virtual Windows::Foundation::Size MeasureOverride(Windows::Foundation::Size availableSize) override
> 		{
> 			auto sz = __super::MeasureOverride(availableSize);
> 			sz.Height = 32.0f; // workaround for wrong measured height
> 			return sz;
> 		}
> 	};
> ```
> 
> and somewhere inside Themes\generic.xaml
> `<Style TargetType="local:CommandBarFlyoutItem" BasedOn="{StaticResource CommandBarFlyoutAppBarButtonStyle}"/>`

**Comment by zadjii-msft** [comment]
Not to necro an old thread, but we saw this with the Terminal too - until we switched to the `Microsoft.UI.Xaml.Controls:CommandBarFlyout` version. Then it just worked like a charm. We were able to do that as a drop-in replacement, just change the namespace. 

Figured that future readers may find that helpful.

**Comment by ranjeshj** [comment]
@zadjii-msft good find. There is only one CommandBarFlyout in WinAppSDK, but there are 2 in WinUI2/OS Xaml. The WinUI2 CommandBarFlyout which is Microsoft.UI.Xaml.Controls.CommandBarFlyout is the updated version that is recommended. This is the same for few other controls like the Progress controls.

**Comment by eugenegff** [comment]
@ranjeshj This bug and https://github.com/microsoft/microsoft-ui-xaml/issues/5813 are actually the same bug.
