### ISSUE TITLE
Layout cycle detected (crash) for some list view sizes when scrolling to end of listview

### ISSUE THREAD

**Issue by wbokkers** [microsoft/microsoft-ui-xaml#6218]
### Describe the bug

I have a list view with group headers and a data template that had **no issues** in UWP and WinUI 3 WinAppSDK 0.8.

In WinAppSDK 1.0 Preview 3, when scrolling to the end of the list view, I get a layout cycle detected exception. But this is only the case when the listview is of a particular size. Most sizes work fine, though. The size for which the crash happens probably depends on the listview contents, but I am not sure about that.

### Steps to reproduce the bug (crash on user interaction)

This issue can be reproduced using this test control:
https://gist.github.com/wbokkers/4a07fedfb99d49d4b8e8ff62971d4eb8

1. Use the test control in a WinUI 3 WASDK 1.0 project.
2. Click on the Next Seed button. This will choose random content and list box sizes for each seed. 
3. See when the app crashes. (most of the time it crashes on seed 9, sometimes it skips 9 and crashes on larger seed)

NOTE: Most of the time the app crashes right away for seed 9. Sometimes you need to scroll up and down **using the touch pad** to get the exception. 

### Reproduce using less code/XAML (crash on load)
The issue can be reproduced with even less and simpler code:
https://gist.github.com/wbokkers/011011af9bf95066967bd4998dca9d77

1. Use this test control in a WinUI WASDK 1.0 project.
2. Show the control.
3. Crash

(For non-crashing situations: change the initial _seed or the listview height in the source code)

### Expected behavior

There should be no layout cycle detected exception. 

### NuGet package version

WinUI 3 - Windows App SDK 1.0 Preview 3

### Device form factor

Desktop

### Windows version

May 2021 Update (19043)

**Comment by wbokkers** [comment]
![image](https://user-images.githubusercontent.com/4835617/140317284-4a4aecd2-1ae7-437d-89da-b5d5e5357845.png)

**Comment by StephenLPeters** [comment]
@RBrid and @codendone FYI

**Comment by wbokkers** [comment]
This issue is happening all over the place where I am using listviews. It also happens for lists without group headers.
It really needs to be fixed in 1.0 for the product to be stable.

**Comment by wbokkers** [comment]
Please fix this. It's still in Windows App SDK 1.0. How is it possible to leave such an issue in the product an call it stable?
@marb2000

**Comment by wbokkers** [comment]
Any news on this issue that is blocking our project for weeks now? @gabbybilka, @marb2000, @ryandemopoulos, @SavoySchuler

**Comment by gabbybilka** [comment]
@wbokkers is this still occurring in 1.0?

**Comment by wbokkers** [comment]
@gabbybilka Yes, it occurs mainly in 1.0. It is a very frequent crash. I think I have seen this occur in 0.8 as well, but only a couple of times.

**Comment by wbokkers** [comment]
I added a new way to reproduce this issue. It's just a matter of using the test control to immediately crash the app.
There's nothing wrong with the code. Using most other list view heights and contents will work as expected. But it's just happening way too often in real world scenario's.

**Comment by wbokkers** [comment]
@gabbybilka Any news on this and other open issues? The silence is deafening. 🦻

**Comment by MikeHillberg** [comment]
It's getting into an infinite loop where layout A is triggering a response to change layout to B, and that's triggering a response to change layout to A, B, A, ... until it hits the max layout count. Certainly that's not supposed to happen, but it appears to be an issue in the ScrollBar track layout code getting triggered by [ItemsStackPanel.ItemsUpdatingScrollMode](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.ItemsStackPanel.ItemsUpdatingScrollMode); removing that stops the cycle:

```xml
<ListView.ItemsPanel>
    <ItemsPanelTemplate>
        <ItemsStackPanel VerticalAlignment="Bottom" ItemsUpdatingScrollMode="KeepLastItemInView" />
    </ItemsPanelTemplate>
</ListView.ItemsPanel>
```

**Comment by wbokkers** [comment]
@MikeHillberg Removing ItemsUpdatingScrollMode is not an option. I need to keep the last item in view as soon as one arrives in the list view. (it's a chat-like experience).

Removing ItemsUpdatingScrollMode and using my own code to scrool to the last item will also trigger a layout cycle (less frequent) and I can't always get it to scroll down completely using this method. So there's also no good workaround.

**Comment by wbokkers** [comment]
@MikeHillberg @gabbybilka Any news on the status? 

This is the crash report of te latest version of our app, with Windows App SDK 1.0.
I can see 10 crashes in 24 hours due to this issue. The new version is installed by 434 users. Most users are not heavy users, so I think these numbers are quite disturbing.

![image](https://user-images.githubusercontent.com/4835617/147211884-91da0eb1-c5df-48a7-bc5b-c5dd015e9bfb.png)

**Comment by MikeHillberg** [comment]
Adding @ranjeshj.

**Comment by wbokkers** [comment]
@MikeHillberg @ranjeshj 
I see this issue happening for all kind of listviews. Not only those that has ItemsUpdatingScrollMode set. 
For some sizes, scrolling to the end (using the touchpad) just crashes due to a layout cycle.

**Comment by wbokkers** [comment]
You can see the crash happen for this simple XAML:

````xml
    <ScrollViewer
        Margin="12,8"
        Height="427.2">
        <StackPanel>
            <Border Margin="8" Height="192" Background="Green" Width="40"/>
            <Border Margin="8" Height="192"  Background="Blue" Width="40"/>
            <Border Margin="8" Background="Yellow" Height="30" Width="40"/>
        </StackPanel>
    </ScrollViewer>
```
Note the specified Height! The content of the scroll viewer is very simple. It looks like the crash is related to the content height AND the scroll viewer height.

**Comment by RBrid** [comment]
@wbokkers, thank you very much for the information you provided. This looks very much like a bug I have been investigating recently.  That one depends on the Scale factor used on the machine, 100%, 125%, 150%, 175%, 200%, etc...  It needed 175% to repro.

I tried all the Scale factors, but I could not repro the crash with the simple ScrollViewer markup above.  What scale factor are you using on your machine to repro?  Thank you.

**Comment by wbokkers** [comment]
@RBrid My scale factor is 125% with a 1920x1080 resoltion. That is works with a different scale factor does not surprise me. The issue is very much dependent on the height of the scroll area and the contents, and changing the scale will change the relative sizes of the scroll area and the contents.

**Comment by wbokkers** [comment]
The scale factor setting is probably why I don't see this issue occurring for all of our users.

**Comment by wbokkers** [comment]
Changing the scale factor with only 1% will 'solve' the ScrollViewer-example on my machine. But I am not convinced that this will solve all situations.

**Comment by wbokkers** [comment]
The XAML Controls Gallery app also crashes on some listviews when scrolling to the end of the list on my machine. This is probably the same issue:
xamlcontrolsgallery://item/NavigationView

**Comment by RBrid** [comment]
Thank you @wbokkers, I can repro the crash now. The reason why I did not repro earlier is because I was using a plain UWP app. I needed to make use of WinUI 2.7 which changed the control template of the ScrollViewer by adding a 1px padding around its 2 ScrollBars.

**Comment by wbokkers** [comment]
@RBrid Good to hear that you can repro the crash! It's a great relief to me that you are tackling this now.
I found the crash on WinUI 3. If there's a fix on UWP, will this be ported to WinUI 3 as well?

**Comment by RBrid** [comment]
@wbokkers, yes you bet it will be ported into WinUI 3.

**Comment by wbokkers** [comment]
@RBrid any change that a fix will be available in the next servicing release op app sdk 1.0?
This crash is reported more frequently by users of our app:
![image](https://user-images.githubusercontent.com/4835617/151168118-689a9dae-0072-4104-a2a0-b2d6a5830a00.png)

**Comment by wbokkers** [comment]
While you are working on the fix, I decided to put the blame on Microsoft when this crash occurs. Users may think it is our apps fault.
In the unhandled exception handler, I now will show the following message:
![image](https://user-images.githubusercontent.com/4835617/151202005-4df65e7a-e45a-48b7-9d9f-adc6a8f09608.png)

**Comment by wbokkers** [comment]
@gabbybilka will this issue be resolved in the next Windows App SDK servicing release? This is by far the most reported crash in our WinUI app.

**Comment by wbokkers** [comment]
@gabbybilka @RBrid @marb2000

Why is this not fixed in the servicing release 1.0.1? All of our users with a scaling other than 100% will see frequent crashes. This bug even occurs in your own WinUI 3 gallery app. 

This would be a blocking issue in every other professional software development organization! Why can Microsoft can get away with this?

**Comment by wbokkers** [comment]
@RBrid the issue is gone for most users since servicing-1.0.2, but it is still happening in some situations and for some users. 0.1% of our users still see this crash.

**Comment by AkshayFT** [comment]
@RBrid @wbokkers the issue is still exists in the latest UWP. We're using the List inside List, when we try to scroll the second list left and right frequently, the app is getting crashed by saying layout cycle detected crash.

**Comment by ynborokh** [comment]
@RBrid Still regularly observed for Win App SDK 1.1.1, when large lists (~1000 items) are frequently scrolled up and down.

**Comment by Bondarenko1990** [comment]
@wbokkers and what is interesting is that if you use gridview, then there is no crash

**Comment by LucaCris** [comment]
Same crash for me, SDK 1.1.1, if many elements are present in a TreeView...

![tree1](https://user-images.githubusercontent.com/50824617/174622877-4ddda1e8-9608-44a1-ad0c-be93642433a1.jpg)

...or also into an AutoSuggestBox:

![tree2](https://user-images.githubusercontent.com/50824617/174623604-5361f652-635f-4eb6-a518-f8ecae58c671.jpg)

The problem is only using mouse, scrolling fast.

It is a BIG problem.

**Comment by marb2000** [comment]
Interesting, I see the internal bug #36940611 closed with the pull request within the bugfix and shipped in WinAppSDK 1.0.2 @krschau or @MikeHillberg can we reopen this or create a new bug for tracking?

@LucaCris, @Bondarenko1990, @wbokkers, and others, can you share a simple repro to accelerate the diagnostic. Also, share the DPIs and WindowsOS version to repro. I want to make sure we have enough info.

**Comment by LucaCris** [comment]
The workaround I found is to remove Height="xxx" (or MaxHeight) from TreeView and replace with:

```
<ScrollViewer Height="xxx">
    <TreeView .../>
</ScrollViewer>
```

No similar workaround possible for AutoSuggestBox, but limiting suggestions to 80 items it works (but 85 crash, for example).

**Comment by LucaCris** [comment]
To easly replicate, @marb2000 , add the selected code to the WinUIGallery demo project:

![immagine](https://user-images.githubusercontent.com/50824617/174809666-19102b03-128f-45f9-ab2c-45aa911ca2f8.png)

And try the AutoSuggestBox, where cat name is 100x presented. Scroll fast using mouse, almost immediate crash!

**Comment by LadderLogic** [comment]
@marb2000 looks like the issue still persists in the latest SDK, but limited to mouse wheel scrolling input.

**Comment by alibi4e** [comment]
> until it hits the max layout count. Certainly that's not supposed to happen, but it appears to be an issue in the ScrollBar track layout code getting triggered by [ItemsStackPanel.ItemsUpdatingScrollMode](https://docs.microsoft.com/uwp/api/Windows.UI.Xaml.Controls.ItemsStackPanel.ItemsUpdatingScrollMode); removing that stops the cycle:

This is still reproducible after removing ItemsUpdatingScrollMode="KeepLastItemInView"

**Comment by alibi4e** [comment]
> @wbokkers and what is interesting is that if you use gridview, then there is no crash

Hi @Bondarenko1990, I tired GridView but the issue is still reproducible

**Comment by Bondarenko1990** [comment]
> > @wbokkers and what is interesting is that if you use gridview, then there is no crash
> 
> Hi @Bondarenko1990, I tried GridView but the issue is still reproducible
> 
> Here is the solution with GridView @ https://github.com/alibi4e/LayoutCycleTest

bad

**Comment by NicolasKlaas** [comment]
Also having the same issue with TreeView, @LucaCris workaround seems to fix it (moving the TreeView in a ScrollViewer).

**Comment by lgBlog** [comment]
Stuck in this bug, a crash that goes nowhere. Just use the mouse to drag the scroll bar at high speed to trigger.

**Comment by codendone** [comment]
Note that there is another crash which is also impacting scrollbar dragging: #7101

**Comment by LucaCris** [comment]
> Note that there is another crash which is also impacting scrollbar dragging: #7101

It is marked as **fixed** 3 days ago! Someone can test 1.1.4 for our problems here? (I'm on holidays for another week)

**Comment by LucaCris** [comment]
I think it should be fixed: I had three reproducible "cases", and after applying 1.1.4 they are gone...

**Comment by bpulliam** [comment]
If this has been fixed, please close it.  Thanks!

**Comment by wbokkers** [comment]
I still see these crashes now and then (reported for 0.2 % of our 20k users). So I don't consider it fixed. It is far less common though.

**Comment by vgromfeld** [comment]
I had the same layout cycle issue in a XAML island control within a Win32 app using WinUI 2.8.2 when zoom is enabled on the `Scrollviewer`.
When using a zoom factor greater than 4.0 scrolling to the bottom is triggering the layout cycle.

Removing the 1px margin around the scrollbar seems to fix the issue.

```xml
<UserControl.Resources>
  <Thickness x:Key="ScrollViewerScrollBarMargin">0</Thickness>
</UserControl.Resources>
```

**Comment by LucaCris** [comment]
> I had the same layout cycle issue in a XAML island control within a Win32 app using WinUI 2.8.2 when zoom is enabled on the `Scrollviewer`. When using a zoom factor greater than 4.0 scrolling to the bottom is triggering the layout cycle.
> 
> Removing the 1px margin around the scrollbar seems to fix the issue.
> 
> ```
> <UserControl.Resources>
>   <Thickness x:Key="ScrollViewerScrollBarMargin">0</Thickness>
> </UserControl.Resources>
> ```

Upgrade to 3.0 then retry. :)

**Comment by Reza-Noei** [comment]
I had similar problem with my UserControl. 
I have binded an `Slider` to a `TextBox` in `TwoWay` mode.
It cause the same issue but when I added this `UpdateSourceTrigger=PropertyChanged` to my binding command It got resolved:

     "{Binding ElementName=decoratedSlider, Path=Maximum, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"

**Comment by soroshsabz** [comment]
@Reza-Noei Please add your SDK version and Windows version

**Comment by soroshsabz** [comment]
@bpulliam any update for this issue exists from Microsoft? I think crash bug must have high priority from Developer teams

**Comment by soroshsabz** [comment]
> I had similar problem with my UserControl in `WinUI3` I have binded an `Slider` to a `TextBox` in `TwoWay` mode.
> 
> **TargetFramework:** net6.0-windows10.0.19041.0 **Microsoft.WindowsAppSDK:** 1.3.230602002 **OS Edition:** Windows 11 Pro **Version:** 22H2 **OS build:** 22621.1992 **Experience:** Windows Feature Experience Pack 1000.22644.1000.0
> 
> ```
> <UserControl
>     x:Class="BSN.Kava.UI.SDK.UserControls.DecoratedSlider"
>     xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
>     xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
>     xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
>     xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
>     xmlns:converters="using:BSN.Kava.UI.SDK.Converters"
>     Name="decoratedSlider"
>     mc:Ignorable="d">
>     <UserControl.Resources>
>         <converters:DoubleStringConverter x:Key="DoubleStringConverter" />
>     </UserControl.Resources>
>     <StackPanel>
>         <TextBlock Margin="0 0 0 8"
>                    FontWeight="Normal" 
>                    Text="{Binding Title, ElementName=decoratedSlider}"/>
>         <Grid>
>             <Grid.ColumnDefinitions>
>                 <ColumnDefinition Width="1*"/>
>                 <ColumnDefinition Width="auto"/>
>             </Grid.ColumnDefinitions>
> 
>             <Slider x:Name="Slider" 
>                     Grid.Column="0"
>                     Margin="0 0 18 0"
>                     Padding="0 6 0 6"
>                     Value="{Binding ElementName=decoratedSlider, Path=Value, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
>                     Minimum="{Binding ElementName=decoratedSlider, Path=Minimum, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
>                     Maximum="{Binding ElementName=decoratedSlider, Path=Maximum, Mode=TwoWay, UpdateSourceTrigger=PropertyChanged}"
>                     VerticalAlignment="Bottom">
>             </Slider>
> 
>             <StackPanel Grid.Column="1" >
>                 <TextBox Width="80" 
>                          TextAlignment="Center"
>                          KeyDown="SliderTextBox_KeyDown"
>                          LostFocus="SliderTextBox_LostFocus"
>                          Text="{Binding ElementName=Slider, Path=Value, Mode=TwoWay, Converter={StaticResource DoubleStringConverter}}"></TextBox>
>             </StackPanel>
>         </Grid>
>     </StackPanel>
> </UserControl>
> ```
> 
> And here is my complete code-behind:
> 
> ```
> public sealed partial class DecoratedSlider : UserControl
> {
>     public DecoratedSlider()
>     {
>         this.InitializeComponent();
>     }
> 
>     public static readonly DependencyProperty TitleProperty = DependencyProperty.Register(nameof(Title), typeof(string), typeof(DecoratedSlider), new PropertyMetadata("Decorated Slider"));
> 
>     public string Title
>     {
>         get => (string)GetValue(TitleProperty);
>         set => SetValue(TitleProperty, value);
>     }
> 
>     public static readonly DependencyProperty MinimumProperty = DependencyProperty.Register(nameof(Minimum), typeof(double), typeof(DecoratedSlider), new PropertyMetadata(100.0));
> 
>     public double Minimum
>     {
>         get => (double)GetValue(MinimumProperty);
>         set => SetValue(MinimumProperty, value);
>     }
> 
>     public static readonly DependencyProperty MaximumProperty = DependencyProperty.Register(nameof(Maximum), typeof(double), typeof(DecoratedSlider), new PropertyMetadata(500.0));
> 
>     public double Maximum
>     {
>         get => (double)GetValue(MaximumProperty);
>         set => SetValue(MaximumProperty, value);
>     }
> 
>     public static readonly DependencyProperty ValueProperty = DependencyProperty.Register(nameof(Value), typeof(double), typeof(DecoratedSlider), new PropertyMetadata(300.0));
> 
>     public double Value
>     {
>         get => (double)GetValue(ValueProperty);
>         set => SetValue(ValueProperty, value);
>     }
> 
>     private void SliderTextBox_KeyDown(object sender, KeyRoutedEventArgs e)
>     {
>         if (e.Key == Windows.System.VirtualKey.Enter)
>         {
>             if (double.TryParse((sender as TextBox).Text, out _) == false)
>                 (sender as TextBox).Text = Slider.Value.ToString();
> 
>             Slider.Focus(FocusState.Keyboard);
>         }
>     }
> 
>     private void SliderTextBox_LostFocus(object sender, RoutedEventArgs e)
>     {
>         if (double.TryParse((sender as TextBox).Text, out _) == false)
>             (sender as TextBox).Text = Slider.Value.ToString();
>     }
> }
> ```
> 
> and here is my `ValueConverter`:
> 
> ```
> public class DoubleStringConverter : IValueConverter
> {
>     public object Convert(object value, Type targetType, object parameter, string language)
>     {
>         return value.ToString();
>     }
> 
>     public object ConvertBack(object value, Type targetType, object parameter, string language)
>     {
>         double doubleValue;
> 
>         if (double.TryParse(value.ToString(), out doubleValue) == false)
>             return 0;
>         
>         return doubleValue;
>     }
> }
> ```

@marb2000 please see @Reza-Noei example for better diagnosis

**Comment by codendone** [comment]
A fix for this issue has just been completed for 1.5. Fixes in `CFrameworkElement::MeasureCore` and `CFrameworkElement::ArrangeCore` were necessary in order to ensure consistent results without sizing larger than the available space.

**Comment by christosk92** [comment]
@codendone I updated to 1.5 experimental, but I still see it occur sometimes. Was it expected to be fixed in 1.5 exp-1 ? Or is it schedule for a future release? 

Thanks!

**Comment by christosk92** [comment]
https://github.com/microsoft/microsoft-ui-xaml/assets/13438702/73a7b3eb-d0cc-460f-98df-674c9f0a1b73

I have attached a video showcasing that it occurs with just a basic ItemsRepeater, that is incrementally loaded based on scroll position.

**Comment by christosk92** [comment]
@wbokkers It seems that my specific case is caused by the incremental loading mechanism of my app. I hook into the "ViewChanged" event of a ScrollView. it seems that this may cause an infinite layout cycle. 

Has anyone else figured out a better way of incrementally loading ItemsRepeater? 

P.S: The [incrementalloadingcollection ](https://learn.microsoft.com/ko-kr/dotnet/communitytoolkit/windows/collections/incrementalloadingcollection)does not work with ItemsRepeater.

**Comment by jinzaz** [comment]
@christosk92 i was use `ItemsRepeater.EffectiveViewportChanged` event to solve this question, determine `EffectiveViewportChangedEventArgs.EffectiveViewport` Point Is it close to ItemsRepeater‘s bottom Point.
I'm not sure if I can solve your problem.

**Comment by kaismic** [comment]
> @codendone Hi I'm just wondering if the fix has already been released or not yet? I'm using WindowsAppSDK 1.5.240428000 but still have the same issue.

Actually I tried using `ScrollViewer` instead of `ScrollView` and now it works without problem.
