### ISSUE TITLE
"The WinUI Desktop Window object has already been closed." exceptions occur when we closed the window.(WinUI_Desktop)

### ISSUE THREAD

**Issue by SathiyathanamSathish** [microsoft/microsoft-ui-xaml#6352]
### Describe the bug

"The WinUI Desktop Window object has already been closed." exceptions occur when we closed the window.  (This issue happens when we did any editing-related process in the UI). Here first we have tried to edit the text box after that we closed the window. This time only the reported exception occurs.

### Steps to reproduce the bug

1. Run the sample.
2. Then type (edit) any letters in the textbox.
3. Then closed the window.

**Observed behavior:**

You can see the reported exception occurs in the output window.

### Expected behavior

The "WinUI Desktop Window object has already been closed." exceptions should not occur.

### Screenshots

 **And we have seen the below exception after we closed the application.** 

![image](https://user-images.githubusercontent.com/89458634/142573742-0a84ecce-6109-47c2-abbb-1bc2593eedb7.png)

**Sample code snippets, which we have tried in our sample:**

![image](https://user-images.githubusercontent.com/89458634/142573839-b1f00520-4cf8-473c-a8da-263997581581.png)

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

October 2020 Update (19042)

### Additional context

Please find the system information below:

![image](https://user-images.githubusercontent.com/89458634/142580201-5eee6e29-0a55-4680-a7c2-a4dfffa9ddaa.png)

**Comment by schroedl** [comment]
These messages and exceptions are concerning. What do we need to change to address them?

**Comment by pratikone** [comment]
this has been fixed and no longer happens. closing the bug. if you find it happening again on latest versions of winappsdk, do reopen the bug

**Comment by parko65** [comment]
Reopen, it's still happening

> this has been fixed and no longer happens. closing the bug. if you find it happening again on latest versions of winappsdk, do reopen the bug

Happening now in 1.2.230118.102

**Comment by ifgotmoney** [comment]
@pratikone, I'm still seeing this exceptions in debug mode:
```
onecore\windows\directx\database\helperlibrary\lib\directxdatabasehelper.cpp(383)\dxgi.dll!00007FFC5A57B5D7: (caller: 00007FFC5A579722) ReturnHr(1) tid(2cf8) 80070057 参数错误。
onecoreuap\windows\frameworkudk\dxprivatescommon.cpp(53)\Microsoft.Internal.FrameworkUdk.dll!00007FFC22519E45: (caller: 00007FFC2258227D) ReturnHr(1) tid(1950) 80004002 不支持此接口
onecoreuap\windows\frameworkudk\dxprivatescommon.cpp(53)\Microsoft.Internal.FrameworkUdk.dll!00007FFC22519E45: (caller: 00007FFC2258227D) ReturnHr(2) tid(1950) 80004002 不支持此接口
onecoreuap\windows\frameworkudk\dxprivatescommon.cpp(53)\Microsoft.Internal.FrameworkUdk.dll!00007FFC22519E45: (caller: 00007FFC2258227D) ReturnHr(3) tid(273c) 80004002 不支持此接口
Exception thrown at 0x00007FFC5C34CD29 (KernelBase.dll) in MainUI.exe: WinRT originate error - 0x80000013 : 'The given object has already been closed / disposed and may no longer be used.'.
```

Do you have any idea about how to fix this?
working with Win10 + VS 2019
![image](https://user-images.githubusercontent.com/34210461/227774463-62bd893b-5aba-4c25-b166-2928e753f4db.png)

**Comment by pratikone** [comment]
@ifgotmoney  this error can occur due to many different reasons. Since this issue has been quite old, it would be best if you can start a new issue with this error, also highlighting your sample code and the libraries used, just like the above. We will be able to track it separately that way.
