### ISSUE TITLE
How to display ContentDialog backdrop/smoke over custom TitleBar

### ISSUE THREAD

**Issue by Petrarca181** [microsoft/microsoft-ui-xaml#6534]
As in title. Current result is this.  https://imgur.com/HKuIZ4E

How to dispay it over custom titlebar? Till preview 3 all was ok.

**Comment by WelterDevelopment** [comment]
I think you can't, it seems to be a bug. Are you targeting Win11 exclusively or do you need backwards compatibility to Win10? In W11 you should switch from the old SetTitleBar() method to the new AppWindow system. Here is a snippet of my app that might help you:

``` csharp
public AppWindow AW { get; set; }
public bool IsCustomizationSupported { get; set; } = false;
public MainWindow()
{
	InitializeComponent();
	IsCustomizationSupported = AppWindowTitleBar.IsCustomizationSupported();

	if (IsCustomizationSupported)
	{
		AW = GetAppWindowForCurrentWindow();
		AW.TitleBar.ExtendsContentIntoTitleBar = true;
		CustomDragRegion.Height = 22;
		AW.Title = "ConTeXt IDE";
		//AW.Closing += AW_Closing;
		//AW.SetIcon(Path.Combine(Package.Current.Installed­Location.Path, @"Assets/", @"SquareLogo.png"));
	}
	else
	{
		CustomDragRegion.BackgroundTransition = null;
		CustomDragRegion.Background = null;
		ExtendsContentIntoTitleBar = true;
		CustomDragRegion.Height = 28;
		SetTitleBar(CustomDragRegion);
		Title = "ConTeXt IDE";
	}
}

private AppWindow GetAppWindowForCurrentWindow()
{
	IntPtr hWnd = WinRT.Interop.WindowNative.GetWindowHandle(this);
	WindowId myWndId = Microsoft.UI.Win32Interop.GetWindowIdFromWindow(hWnd);
	return AppWindow.GetFromWindowId(myWndId);
}
```
This way, at least in W11 (where IsCustomizationSupported is true) the smoke does work in the Titlebar.

**Comment by StephenLPeters** [comment]
@pratikone and @bpulliam is this possible today?

**Comment by nlogozzo** [comment]
I'm experiencing this as well on my app using Windows App SDK V1.0 @StephenLPeters @gabbybilka 
With my custom title bar and showing a ContentDialog, the entire window is blocked by the ContentDialog except for the Min, Max, and Close window buttons of the title bar. 
This is not the expected behavior of the ContentDialog as it is expected to block the caption buttons as well (as seen in apps such as the Win 11 Notepad)

**Comment by pratikone** [comment]
this is not possible today unfortunately because of the way custom titlebar is implemented. we could try to make it work, maybe ? marking it as a bug .

**Comment by Petrarca181** [comment]
App sdk 1.1  stable. Still not fixed.   I was using this style to completely  hide defailt titlebar and make my own.  

<details>
  <summary>Style</summary>
<Style x:Key="WindowChromeStyle" TargetType="ContentControl">
                <Setter Property="Template">
                    <Setter.Value>
                        <ControlTemplate TargetType="ContentControl">
                            <Grid x:Name="LayoutRoot">
                                <ContentPresenter
                                    x:Name="ClientAreaPresenter"
                                    Content="{TemplateBinding Content}"
                                    ContentTemplate="{TemplateBinding ContentTemplate}"
                                    ContentTransitions="{TemplateBinding ContentTransitions}"
                                    Foreground="{TemplateBinding Foreground}" />
  <Grid
                                    x:Name="TitleBarMinMaxCloseContainer"
                                    HorizontalAlignment="Right"
                                    VerticalAlignment="Top"
                                    Visibility="Collapsed">
                                    <Grid
                                        x:Name="MinMaxCloseContainer"
                                        HorizontalAlignment="Right"
                                        VerticalAlignment="Top"
                                        ColumnDefinitions="Auto,Auto,Auto">
                                        <Button
                                            x:Name="MinimizeButton"
                                            Grid.Column="0"
                                            AutomationProperties.AutomationId="_MinimizeButton"
                                            AutomationProperties.Name="Minimize"
                                            Content="M 0 0 H 10"
                                            Style="{StaticResource WindowCaptionButton}" />

                                        <Button
                                            x:Name="MaximizeButton"
                                            Grid.Column="1"
                                            AutomationProperties.AutomationId="_MaximizeButton"
                                            AutomationProperties.Name="Maximize"
                                            Content="M 0 0 H 10 V 10 H 0 V 0"
                                            Style="{StaticResource WindowCaptionButton}" />
                                        <Button
                                            x:Name="CloseButton"
                                            Grid.Column="2"
                                            AutomationProperties.AutomationId="_CloseButton"
                                            AutomationProperties.Name="Close"
                                            Content="M 0 0 L 10 10 M 10 0 L 0 10"
                                            Style="{StaticResource WindowCaptionButton}">
                                            <Button.Resources>
                                                <ResourceDictionary>
                                                    <ResourceDictionary.ThemeDictionaries>
                                                        <ResourceDictionary x:Key="Light">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed" />
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="Dark">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed" />
                                                        </ResourceDictionary>
                                                        <ResourceDictionary x:Key="HighContrast">
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPointerOver" ResourceKey="CloseButtonBackgroundPointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonBackgroundPressed" ResourceKey="CloseButtonBackgroundPressed" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePointerOver" ResourceKey="CloseButtonStrokePointerOver" />
                                                            <StaticResource x:Key="WindowCaptionButtonStrokePressed" ResourceKey="CloseButtonStrokePressed" />
                                                        </ResourceDictionary>
                                                    </ResourceDictionary.ThemeDictionaries>
                                                </ResourceDictionary>
                                            </Button.Resources>
                                        </Button>
                                    </Grid>
                                </Grid>
                                <VisualStateManager.VisualStateGroups>
                                    <VisualStateGroup x:Name="CommonStates">
                                        <VisualState x:Name="Normal">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="Transparent" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                        <VisualState x:Name="WindowInactive">
                                            <VisualState.Setters>
                                                <Setter Target="TitleBarMinMaxCloseContainer.Background" Value="Transparent" />
                                                <Setter Target="MinimizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MinimizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="MaximizeButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="MaximizeButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                                <Setter Target="CloseButton.Foreground" Value="{ThemeResource WindowCaptionForeground}" />
                                                <Setter Target="CloseButton.Background" Value="{ThemeResource WindowCaptionButtonBackground}" />
                                            </VisualState.Setters>
                                        </VisualState>
                                    </VisualStateGroup>
                                </VisualStateManager.VisualStateGroups>
                            </Grid>
                        </ControlTemplate>
                    </Setter.Value>
                </Setter>
            </Style>

  
</details>

But now if I  use it drag region stops working.... help please.

**Comment by Lightczx** [comment]
> ```cs
> var child = VisualTreeHelper.GetChild(parent, 0);
> ```

It actually have to be:
```
var child = VisualTreeHelper.GetChild(parent, 2);
```
The third element is the `smokeLayerBackground`

**Comment by Lightczx** [comment]
Taking advantage of the CommunityToolkit.WinUI.UI.Behaviors.BehaviorBase class
```cs
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Shapes;

/// <summary>
/// Make ContentDialog's SmokeLayerBackground dsiplay over custom titleBar
/// </summary>
public class ContentDialogBehavior : CommunityToolkit.WinUI.UI.Behaviors.BehaviorBase<FrameworkElement>
{
    /// <inheritdoc/>
    protected override void OnAssociatedObjectLoaded()
    {
        DependencyObject parent = VisualTreeHelper.GetParent(AssociatedObject);
        DependencyObject child = VisualTreeHelper.GetChild(parent, 2);
        Rectangle smokeLayerBackground = (Rectangle)child;

        smokeLayerBackground.Margin = new Thickness(0);
        smokeLayerBackground.RegisterPropertyChangedCallback(FrameworkElement.MarginProperty, OnMarginChanged);
    }

    private static void OnMarginChanged(DependencyObject sender, DependencyProperty property)
    {
        if (property == FrameworkElement.MarginProperty)
        {
            sender.ClearValue(property);
        }
    }
}
```
just add this to your project, and add xaml in your ContentDialog like below

```xaml
<ContentDialog ...>
    <mxi:Interaction.Behaviors>
        <shcb:ContentDialogBehavior/>
    </mxi:Interaction.Behaviors>
</ContentDialog>
```
Works fine for me.

**Comment by Petrarca181** [comment]
I just set titlebar container height to 0 when call contentdialog. I like the last solution,  but how make it work if I create dialog code behind?

**Comment by Lightczx** [comment]
```cs
ContentDialog dialog = new();
...
Microsoft.Xaml.Interactivity.Interaction.SetBehaviors(dialog ,new BehaviorCollection(){new ContentDialogBehavior()});
```
Tested, and works.

**Comment by Petrarca181** [comment]
> 

You are my hero.

**Comment by Petrarca181** [comment]
> ```cs
> ```cs
> var child = VisualTreeHelper.GetChild(parent, 0);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> 
> It actually has to be:
> ```cs
> var child = VisualTreeHelper.GetChild(parent, 2);
> ```
> 
> 
>     
>       
>     
> 
>       
>     
> 
>     
>   
> The third element is the smokeLayerBackground
> ```

 VisualTreeHelper.GetChild(parent, 2); - Catastrophic failture
 VisualTreeHelper.GetChild(parent, 1); - Smoke null
 VisualTreeHelper.GetChild(parent, 0); - Actually works but need to test

**Comment by Lightczx** [comment]
> > ```cs
> > ```cs
> > var child = VisualTreeHelper.GetChild(parent, 0);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It actually has to be:
> > ```cs
> > var child = VisualTreeHelper.GetChild(parent, 2);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The third element is the smokeLayerBackground
> 
> VisualTreeHelper.GetChild(parent, 2); - Catastrophic failture VisualTreeHelper.GetChild(parent, 1); - Smoke null VisualTreeHelper.GetChild(parent, 0); - Actually works but need to test

That‘s wierd.
![image](https://user-images.githubusercontent.com/36357191/182347627-f1d5d1c1-a99a-4304-815f-81840e0b8cad.png)

You can set a breakpoint and inspect the parent.Children

**Comment by Lightczx** [comment]
> > ```cs
> > ```cs
> > var child = VisualTreeHelper.GetChild(parent, 0);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > It actually has to be:
> > ```cs
> > var child = VisualTreeHelper.GetChild(parent, 2);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > The third element is the smokeLayerBackground
> 
> VisualTreeHelper.GetChild(parent, 2); - Catastrophic failture VisualTreeHelper.GetChild(parent, 1); - Smoke null VisualTreeHelper.GetChild(parent, 0); - Actually works but need to test

It cound be my issue, cause my dialog is modified from a UserContol template.

**Comment by Lightczx** [comment]
Well... Just use GetChildrenCount and a for loop to test all elements
```cs
using CommunityToolkit.WinUI.UI.Behaviors;
using Microsoft.UI.Xaml;
using Microsoft.UI.Xaml.Media;
using Microsoft.UI.Xaml.Shapes;

/// <summary>
/// Make ContentDialog's SmokeLayerBackground dsiplay over custom titleBar
/// </summary>
public class ContentDialogBehavior : BehaviorBase<FrameworkElement>
{
    /// <inheritdoc/>
    protected override void OnAssociatedObjectLoaded()
    {
        DependencyObject parent = VisualTreeHelper.GetParent(AssociatedObject);

        for (int i = 0; i < VisualTreeHelper.GetChildrenCount(parent); i++)
        {
            DependencyObject current = VisualTreeHelper.GetChild(parent, i);
            if (current is Rectangle { Name: "SmokeLayerBackground" } background)
            {
                background.Margin = new Thickness(0);
                background.RegisterPropertyChangedCallback(FrameworkElement.MarginProperty, OnMarginChanged);
                break;
            }
        }
    }

    private static void OnMarginChanged(DependencyObject sender, DependencyProperty property)
    {
        if (property == FrameworkElement.MarginProperty)
        {
            sender.ClearValue(property);
        }
    }
}
```
@pratikone This should totally work now.

**Comment by Link1J** [comment]
@Lightczx I don't know if the C# version works. The C++ version works 100% of the time, so the C# should work. If it doesn't then C# does something different to C++, and I don't know why.

**Comment by Lightczx** [comment]
> @Lightczx I don't know if the C# version works. The C++ version works 100% of the time, so the C# should work. If it doesn't then C# does something different to C++, and I don't know why.

My dialog isn't created by code, and it's initialized by XAML parser.
I think it's the only difference.

**Comment by rick-palmsens** [comment]
Ran into this today as well, it is quite annoying. The whole point of a modal dialog is to prevent any input, but due to this issue the main menu is still clickable:
![image](https://user-images.githubusercontent.com/57390463/211547164-1c2890f8-8f72-4e32-9368-a91c455ec981.png)

**Comment by EricMHeumann** [comment]
I too am still running into this. Windows App SDK 1.2.230217.4 for Windows 10.0.19041.0 on .NET 6.

![image](https://user-images.githubusercontent.com/118454794/223488580-a572fbe4-299e-405e-8edb-4b6fe5479d7d.png)

Fixed using the approach mentioned above.
```
dialog.Loaded += OnLoaded;

void OnLoaded(object sender, RoutedEventArgs e)
{
    // Set the Theme

    dialog.RequestedTheme = ThemeHelper.ActualTheme;

    // Fix the smoke layer margin at the title bar
    
    DependencyObject popupRoot = VisualTreeHelper.GetParent(dialog);

    Rectangle smokeLayer = (Rectangle) VisualTreeHelper.GetChild(popupRoot, 0);
    smokeLayer.Margin = new Thickness(0);
    smokeLayer.RegisterPropertyChangedCallback(
        FrameworkElement.MarginProperty,
        (ss, dp) =>
        {
            if (dp == FrameworkElement.MarginProperty)
            {
                ss.ClearValue(dp);
            }
        });
}

// Show dialog

ContentDialogResult result = await dialog.ShowAsync();
```

**Comment by Link1J** [comment]
A note for anyone coming across this problem still. The `AppWindow` titlebar APIs in the Windows App SDK itself to not have this problem. This does mean you need to use version 1.2 or newer of Windows App SDK if you need Windows 10 support. But it is unlikely to break or be problematic, unlike the current fix of looking thru the XAML tree for the smoke effect and patching it.

And as a bonus `AppWindow`'s version of the caption buttons match how Win32 and UWP draw them. I don't know how the XAML team messed up the caption buttons.

**Comment by Pietro228** [comment]
> I too am still running into this. Windows App SDK 1.2.230217.4 for Windows 10.0.19041.0 on .NET 6.
> 
> ![image](https://user-images.githubusercontent.com/118454794/223488580-a572fbe4-299e-405e-8edb-4b6fe5479d7d.png)
> 
> Fixed using the approach mentioned above.
> 
> ```
> dialog.Loaded += OnLoaded;
> 
> void OnLoaded(object sender, RoutedEventArgs e)
> {
>     // Set the Theme
> 
>     dialog.RequestedTheme = ThemeHelper.ActualTheme;
> 
>     // Fix the smoke layer margin at the title bar
>     
>     DependencyObject popupRoot = VisualTreeHelper.GetParent(dialog);
> 
>     Rectangle smokeLayer = (Rectangle) VisualTreeHelper.GetChild(popupRoot, 0);
>     smokeLayer.Margin = new Thickness(0);
>     smokeLayer.RegisterPropertyChangedCallback(
>         FrameworkElement.MarginProperty,
>         (ss, dp) =>
>         {
>             if (dp == FrameworkElement.MarginProperty)
>             {
>                 ss.ClearValue(dp);
>             }
>         });
> }
> 
> // Show dialog
> 
> ContentDialogResult result = await dialog.ShowAsync();
> ```

Hi, it's not related to this issue, but how do you make your "Back" arrow appear in the title bar? I know that I should change margin of the frame but how?

**Comment by Lightczx** [comment]
> how do you make your "Back" arrow appear in the title bar? I know that I should change margin of the frame but how?

Hi, @Pietro228 I'm assuming you have already set ExtendContentIntoTitleBar to true,
place this peice of code in any Resources where can be applied to your NavigationView
```
<Thickness x:Key="NavigationViewContentMargin">0,44,0,0</Thickness>
```
The top margin should be consisent with you `visual` title bar height

**Comment by pratikone** [comment]
it is fixed now with winappsdk 1.4 release. I overhauled the custom titlebar implementation and implemented so that content dialog works naturally with it. (no top offset)
