### ISSUE TITLE
Setting Foreground on MenuBarItem doesn't work

### ISSUE THREAD

**Issue by eerhardt** [microsoft/microsoft-ui-xaml#7070]
### Describe the bug

Setting the Foreground property on a MenuBarItem or a MenuBar doesn't affect the text color of the menu.

### Steps to reproduce the bug

1. Create a Blank WinUI 3 app
2. In the MainPage add the following xaml:

```xml
        <MenuBar Foreground="White" Background="Black">
            <MenuBarItem Title="File" Foreground="White" />
            <MenuBarItem Title="Edit" Foreground="White">
                <MenuFlyoutItem Text="Cut" Foreground="LightSeaGreen"/>
                <MenuFlyoutSeparator />
                <MenuFlyoutItem Text="Copy" Foreground="Blue"/>
                <MenuFlyoutSubItem Text="Other" Foreground="LightSteelBlue">
                    <MenuFlyoutItem Text="Delete" Foreground="Black"/>
                </MenuFlyoutSubItem>
            </MenuBarItem>
        </MenuBar>
```
3. Run the app

### Expected behavior

I expect to be able to read the Menu items because I set the Background to black and the Foreground to White.

I'm not sure whether setting the MenuBar Foreground should affect all the MenuBarItems inside of it or not. I can see advantages to both.

Interesting is that MenuFlyoutItem and MenuFlyoutSubItem Foreground appears to work. It is just MenuBarItem that doesn't.

### Screenshots

Notice that `File` and `Edit` aren't readable in the MenuBar.

![image](https://user-images.githubusercontent.com/8291187/167223901-da1acebb-d6a3-4e27-998d-f7dc1eb485d6.png)

### NuGet package version

WinUI 3 - Windows App SDK 1.0.3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows 10 (21H2): Build 19044

**Comment by eerhardt** [comment]
I don't believe this has been fixed has it? Can it be re-opened?

**Comment by JoeTomkinson** [comment]
This is still a problem, in-fact the same issue was reported against the WinUI-Gallery application https://github.com/microsoft/WinUI-Gallery/issues/1108

If the theme of the application changes from light to dark, or dark to light, the flyout style doesn't appropriately change. This is a bug and should be marked for triage.

Seems to me as though this has been present for at least 12 months maybe longer.

**Comment by cosmin42** [comment]
Any known workaround?

**Comment by karkarl** [comment]
Fixed in internal PR: 10250839
