### ISSUE TITLE
WinUI 3 C# Window Templates are missing in Visual Studio 2022 17.2.2 in Add new item dialogue.

### ISSUE THREAD

**Issue by engraneesahmad** [microsoft/microsoft-ui-xaml#7148]
### Describe the bug

WinUI 3 C# Window Templates are missing in Visual Studio 2022 17.2.2 in Add new item dialogue.

### Steps to reproduce the bug

WinUI 3 C# Window Templates are missing in Visual Studio 2022 17.2.2 in Add new item dialogue.

### NuGet package version

WinUI 3 - Windows App SDK 1.1 Preview 3: 1.1.0-preview3

### Windows app type

- [ ] UWP
- [X] Win32

### Device form factor

Desktop

### Windows version

Windows Insider Build (xxxxx)

### Additional context

Windows 11 (21H2) Build 22621.1

**Comment by kmgallahan** [comment]
> are missing in Visual Studio 2022 16.2.2

Visual Studio 2022 16.2.2 doesn't exist.

If you are using VS 2019 then they are installed via an extension:

https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-other%2Cvs-2019#visual-studio-project-and-item-templates

**Comment by engraneesahmad** [comment]
Sorry that was my version writing issue.

In VS 17.2.2 that is.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by kmgallahan** [comment]
Try reinstalling the templates (or check that they are selected in the below bundle):

1. Open Visual Studio Installer > Modify
2. Uncheck .NET desktop development > Modify
3. Check .NET desktop development > Modify

**Comment by engraneesahmad** [comment]
I have did it before. Even reinstalled windows 11 and reinstalled VS 2022.

Problem still exist.

If I use default Windows App SDK 1.0 installed by VS then templates are displayed.

If I use Windows App SDK 1.1.0 Preview 3 then templates are missing from C# based Win32 WinUI Project. (I need to use this version because I need to use MICA in WinUI 3)…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Pinox** [comment]
@engraneesahmad 

Make sure sure you have the following installed on .net development & C++ desktop development.  

![image](https://user-images.githubusercontent.com/5297255/170672961-4770c740-a9f8-44b9-85b0-4be863a785bf.png)

![image](https://user-images.githubusercontent.com/5297255/170673034-c31425be-efd9-4dda-aad0-a3680965c39c.png)

I agree WinUI tooling from defaults are a mess,  Not sure why the Windows App SDK is not selected by default.

Please MS fix this as it is wasting everyone's time !!

**Comment by engraneesahmad** [comment]
Hi, 
![1](https://user-images.githubusercontent.com/82972669/170683397-4686c09a-d04a-4428-a397-5ce898ce8b99.png)
![2](https://user-images.githubusercontent.com/82972669/170683406-11e4839b-460e-4779-bfd0-8f2a881ab29d.png)
![3](https://user-images.githubusercontent.com/82972669/170683410-69955a22-aaea-4a13-8aa7-452dc7dbec2a.png)
![4](https://user-images.githubusercontent.com/82972669/170683419-c32226fd-6f8d-4fb6-b1a1-0033cdc001b1.png)
![5](https://user-images.githubusercontent.com/82972669/170683423-c540d83b-41eb-48b8-93c0-765153c215ae.png)

I have already installed these components.

The issue does not arise if i use Windows App SDK 1.0 in the stable release version templates display well.

But when i install Windows App SDK 1.1.0 Preview-3 for C# then templates miss in add new item dialogue.

I have carried out clean installation of Windows 11 (21H2) Build 22000 and clean installation of VS-2022 17.2.2 with the options shown in attached images on my home computer as well. The problem persists.

And I have carried out clean installation of Windows 11 (22H2) Build 22621.1 and clean installation of VS-2022 17.2.2 with the options shown in attached images on my laptop computer as well. The problem persists.

The problem arise due to VS-2022 17.2.2 and Windows App SDK 1.1.0 Preview-3....

Currently i am creating new xaml winui3 window manually (xaml files and xaml.cs file) and enterning into cs proj manually to workaround.

Resulting Dialogue box is also attached. I have to use Windows App SDK version 1.1.0 Preview-3 in order to use MICA Effect.
![6](https://user-images.githubusercontent.com/82972669/170685104-b6ec8861-601e-4ed5-b747-4372fd8c97c2.png)

I have to use this functionality to build an application for chemical process design engineering field for my company. My time is also important. I am only started to report it to Microsoft so such problems will be eliminated in final release.

![7](https://user-images.githubusercontent.com/82972669/170685724-116c2d19-564b-4d49-88c8-f7bb5468e5a0.png)

Otherwise i have to rewrite the app using .NET WPF because that does not waste time in such problems.

I can also share my project source code with microsoft if needed to resolve this issue.

**Comment by Pinox** [comment]
@engraneesahmad 

Do u have .net 7 previews installed ?  I had a similiar issue , can't remember anymore I think it was more MAUI related.  Try unstalling all .net 7 preview if you have.

**Comment by engraneesahmad** [comment]
I do not have it installed.

Screenshoots of installed stuff is attached.

I am using Visual Studio 20222 with Enterprise Version License….

Installed preview tools are:


  1.  Microsoft Windows App SDK 1.1.0-Preview 3
  2.  Microsoft SQL Server 2022 CTP 2.0
  3.  Microsoft Windows 11 Pro (Build-22621.1)
  4.  Microsoft Office 365 for Enterprise (Current Channel Preview) – Version 2204 Build - 15128.

**Comment by Pinox** [comment]
@engraneesahmad  

Have you u tried installing VS 2022 on something like "Windows Sandbox" just to make sure it not something with you current PC installation.

![image](https://user-images.githubusercontent.com/5297255/170828727-f2688a39-0eda-4a84-bdde-ef40aa1133df.png)

**Comment by engraneesahmad** [comment]
OK I make virtual machine of windows 11 using VMWare then carry out clean installation then inform you. Give me some time…

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Pinox** [comment]
> OK I make virtual machine of windows 11 using VMWare then carry out clean installation then inform you. Give me some time…

I normally use Windows Sandbox, then there is no need to install Windows again. Also everything you install is only valid for the current session.  Next start of sandbox and it empty again.

**Comment by EddieLotter** [comment]
I updated VS 2022 Professional to 17.2.2 and now there is no template for ContentDialog.
This appears to have [been an issue before](https://github.com/microsoft/microsoft-ui-xaml/issues/6583).

**Comment by thilojaeggi** [comment]
Also facing the same issue. Manually installed Windows App SDK 1.1.0 Preview 3 C# Visual Studio 2022 extension to no avail.

**Comment by JonPerkinsOldGit** [comment]
I've spent five hours today on this issue - uninstalling Visual Studio, reinstalling, and so on. I've finally landed on this page and found it to be an issue that others have too. Would love to know if there is a better workaround than I am doing - copy and paste a different Page item and then rename the file and code name properties.

**Comment by marb2000** [comment]
Sorry @JonPerkinsOldGit and @engraneesahmad, and others.

I have just chatted with Visual Studio. There is a regression within the project templates and they already fixed it. Just waiting for the next service update, I don't have an ETA yet, I hope it doesn't take too much. As a workaround, you can use VS2022 17.3 Preview, or grab a [basic existing WinUi3 project](https://github.com/microsoft/WinUI-3-Demos/tree/master/src/Build2022Demo/BasicPhotoViewer). You can also use the [Template Studio](https://github.com/microsoft/TemplateStudio)

About the ContentDialog template, I believe we never added it to the WinAppSDK. It's the kind of thing we deprioritize against fixing bugs. It's not a big deal, and it's very convenient, but there is something else more important to do always. You know the feeling, right?

**Comment by matkovic** [comment]
Same problem here. I don't think I updated Visual Studio 2019 or project packages, but a couple of weeks ago I could see template items which are not listed there today (as I opened project again).

Could this have something to do with windows update?

**Comment by Harrisandwich** [comment]
An update on my situation if anyone here finds it helpful. I uninstalled all versions of visual studio on my machine (i had a couple), and reinstalled VS2022 with all of the options listed in the [Tools for Windows App SDK page](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/set-up-your-development-environment?tabs=vs-2022-17-1-a%2Cvs-2022-17-1-b). 

From there, I used Template Studio to create a new app. Everything seemed to work fine for that app. I was able to see a WinUI item templates ins in the Add Item dialog. I also made sure to confirm the installation of Windows App SDK through the Nuget package manager. Weirdly enough, the version was actually v1.1.0. 

For this installation I _did NOT_ use the [extension found here](https://docs.microsoft.com/en-us/windows/apps/windows-app-sdk/downloads). Perhaps using the extension was the issue? Seems a fresh install with just the workloads and components specified in the instructions worked. I think my issue was overall a result of misunderstanding/getting lost in the docs

**Comment by ghost1372** [comment]
I also have this problem since the release of v1.1.0-preview3 extension. (i reinstalled windows and VS2022) I think this problem should be reported in Visual Studio team

**Comment by JonPerkinsOldGit** [comment]
From what I have found the WinUI templates are present if you run Visual Studio 17.3 preview 1. However, on this preview build you cannot [Project -> Publish -> Create App Package] so in that case you have to revert back to the latest VS 17.2. I'm managing OK now that I've figured that out.

Life at the leading edge eh? ;-)

**Comment by kmgallahan** [comment]
After running into the issue mentioned here: [https://github.com/microsoft/WindowsAppSDK/issues/2579](https://github.com/microsoft/WindowsAppSDK/issues/2579) and losing templates, updating to VS 2022 17.3.0 Preview 1.1 now shows the extensions as installed with templates working again: 

![Screenshot 2022-06-09 140334](https://user-images.githubusercontent.com/5379488/172914768-377f9f88-f4f7-40ea-b16b-5ea436c517c8.jpg)

**Comment by marb2000** [comment]
Thanks, @japarson for the PR to fix the issue in Visual Studio

**Comment by JLBLU** [comment]
Same issue in Version 17.3.0 Preview 2.0 / WindowsAppSDK 1.1.1

**Comment by pluto-dev** [comment]
> Same issue in Version 17.3.0 Preview 2.0 / WindowsAppSDK 1.1.1

I can confirm this as well. Item templates are not available.

**Comment by tuffstuff9** [comment]
I am having the same issue. I have tried installing the experimental template extension but the install fails. I have also tried installing vs preview 2 and the templates still don't show up. What is the solution?

**Comment by kmgallahan** [comment]
@pluto-dev @tuffstuff9 https://github.com/microsoft/microsoft-ui-xaml/issues/7148#issuecomment-1138400583

**Comment by tuffstuff9** [comment]
> @pluto-dev @tuffstuff9 [#7148 (comment)](https://github.com/microsoft/microsoft-ui-xaml/issues/7148#issuecomment-1138400583)

Have tried that to no avail, unfortunately.

**Comment by ghost1372** [comment]
In UWP Project, all items is available 😅

![image](https://user-images.githubusercontent.com/9213496/175095969-2a2afe43-af5c-4462-a605-74aaee5c2d16.png)

**Comment by mahfuzmr** [comment]
> After running into the issue mentioned here: [microsoft/WindowsAppSDK#2579](https://github.com/microsoft/WindowsAppSDK/issues/2579) and losing templates, updating to VS 2022 17.3.0 Preview 1.1 now shows the extensions as installed with templates working again:
> 
> ![Screenshot 2022-06-09 140334](https://user-images.githubusercontent.com/5379488/172914768-377f9f88-f4f7-40ea-b16b-5ea436c517c8.jpg)

This Solved my Problem Also 👯‍♂️

**Comment by neos7m** [comment]
I am on 17.3 Preview 2 and the Revert button is not available. I only get Uninstalled. I already tried uninstalling and reinstalling but nothing changed. I still don't have the templates.

**Comment by gabbybilka** [comment]
Fixed with Windows App SDK 1.1.2, see [release notes](https://aka.ms/windowsappsdk/1.1/1.1.2/release-notes) for more info.

cc: @evelynwu-msft

**Comment by ArieBen** [comment]
where can I find a download for preview 1?

**Comment by ArieBen** [comment]
> 

Upgrading the nuget to Windows App SDK 1.1.2 in a new project doesn't cut it for me. I still can't see the Item templates. 
How is this a fix? Can you be a bit more specific on how to implement? thx

**Comment by ghost1372** [comment]
> > 
> 
> @gabbybilka Upgrading the nuget to Windows App SDK 1.1.2 in a new project doesn't cut it for me. I still can't see the Item templates. How is this a fix? Can you be a bit more specific on how to implement? thx

download new extension
https://aka.ms/windowsappsdk/1.1/1.1.2/vsix-2022-cs

**Comment by kmgallahan** [comment]
@ghost1372 Thanks.

@gabbybilka Item templates disappeared again for me. Neither updating to WASDK 1.1.2, updating to VS 17.3.0 Preview 3.0, or uninstalling/reinstalling the templates from the VS installer got them working. 

Only installing the extension from the above link fixed the problem, and this requirement isn't mentioned anywhere in the docs or WASDK release notes as far as I can see.

**Comment by Balkoth** [comment]
Same problem here, only got it working after manually downloading from https://aka.ms/windowsappsdk/1.1/1.1.3/vsix-2022-cs and installing this version of the addon.

**Comment by imsunburnt** [comment]
Just did reinstall of Visual Studio 2022 17.3.4 and C# UI templates are installed but do not show up in the Add New Item dialog.  Same problem as others have mentioned.  Manage Extensions screen shows Windows App SDK C# VS2022 Templates version 1.1.3.80461806 is installed.  For UWP projects the UI templates are available.  I had previously tried all the above recommendations but none worked.  Still looking for solution.

**Comment by engraneesahmad** [comment]
Can it be used having VMware already installed. Once before I tried to use it but it do not let VMware to run until unless we disable it?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows
