### ISSUE TITLE
ToggleSplitButton does not Toggle On/Off with Touch Input

### ISSUE THREAD

**Issue by techjogger** [microsoft/microsoft-ui-xaml#8061]
### Which version of the app?

WinUI 3 Gallery

### Description

Unable to toggle the control On/Off with Touch Input., the flyout is open instead. The control works as expected with Mouse and Pen input. 

https://user-images.githubusercontent.com/13125455/209179617-8f5185b9-f982-4a20-a50d-9b53ed0f0834.mp4

### Windows version

Windows 11 22H2 (22621)

**Comment by techjogger** [comment]
> Similar issue for SplitButton: #178.

Will the WinUI team fix this issue? This issue is makes toggle split button unusable

**Comment by bkudiess** [comment]
This issue was fixed internally and will be available soon :)

**Comment by techjogger** [comment]
When will the fix be released? This issue is still present in 1.6.1
