### ISSUE TITLE
WinUI3: ContentDialog is missing entrance animation

### ISSUE THREAD

**Issue by Aurumaker72** [microsoft/microsoft-ui-xaml#8476]
### Describe the bug

`ContentDialog` doesn't have an entrance animation, but has an exiting animation.

This is a possible regression, as the Windows 11 Settings app does feature `ContentDialog`s with entrance animations (see Windows Insider Program tab)

### Steps to reproduce the bug

1. Create a `ContentDialog` with an appropriate XamlRoot and arbitrary text
2. Await the `ContentDialog`'s `ShowAsync` method
3. Observe the `ContentDialog` instantly appearing with no animation.

### Expected behavior

The `ContentDialog` is expected to enter with an animation, similar to what is seen in Fluent.

### Screenshots

https://github.com/microsoft/microsoft-ui-xaml/assets/48759429/269fc753-2394-42da-8a53-2a840eae0e92

### NuGet package version

WinUI 3 - Windows App SDK 1.3.1: 1.3.230502000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by IstvanKor** [comment]
Maybe missing style assignment to your ContentDialog.

ContentDialog dialog = new ContentDialog();
....
dialog.Style = Application.Current.Resources["DefaultContentDialogStyle"] as Style;
....
await dialog.ShowAsync();

**Comment by Aurumaker72** [comment]
> Maybe missing style assignment to your ContentDialog.

This indeed fixes the issue.
It, on the other hand, begs the question: shouldn't this be assigned by default? The OOB experience is suboptimal enough as-is.

**Comment by Balkoth** [comment]
Seems strange to me that the default style is not applied automatically...

**Comment by Aurumaker72** [comment]
> Is this a problem on other controls too?

I haven't tested extensively, but all the basic controls (Button, CheckBox, ComboBox, RadioButton, Slider), collection controls, and navigation controls seem perfectly fine.

**Comment by IstvanKor** [comment]
> Looks like a dupe of #5573 to me.

#5573 is related to WinUi 2.X, this issue to WinUI 3.

**Comment by Aurumaker72** [comment]
Also, the proposed solution in #5573 does not work.

**Comment by Balkoth** [comment]
This is still an issue in Windows App SDK 1.3.2 (1.3.230602002)

**Comment by lolametro** [comment]
This is an issue _again_ in Windows App SDK 1.6-experimental-1.

**Comment by lolametro** [comment]
This is still an issue in Windows App SDK 1.6-preview-1.

Just to clarify: the workaround above (https://github.com/microsoft/microsoft-ui-xaml/issues/8476#issuecomment-1546592773 assign the style) does not help here. In 1.5 it still worked fine.
Please fix this regression before releasing 1.6!

**Comment by lolametro** [comment]
This is still an issue in the *released* Windows App SDK 1.6. 🙂

**Comment by Balkoth** [comment]
Super strange that the exit animation is still there...

**Comment by kirwan-safesurfer** [comment]
> This is still an issue in the _released_ Windows App SDK 1.6. 🙂

Also wanted to corroborate that this is a 1.6 regression not present in Windows App SDK 1.5.6.

**Comment by lolametro** [comment]
This was fixed in Windows App SDK 1.6.1 (1.6.240923002) 🙏

At least when setting the style like described in https://github.com/microsoft/microsoft-ui-xaml/issues/8476#issuecomment-1546592773. Without setting the style, there's still no animation, but at least the workaround works again.

**Comment by GF-Huang** [comment]
Issue still in `<PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260317003" />`.
