### ISSUE TITLE
Getting exceptions randomly when closing a WinUI3 app with TabView controls.

### ISSUE THREAD

**Issue by Ajith-GS** [microsoft/microsoft-ui-xaml#8575]
### Describe the bug

The following exception is thrown randomly when closing a WinUI3 app that contains TabView controls in its UI.
`The given object has already been closed/ disposed and may no longer be used.`

![ExceptionMsg](https://github.com/microsoft/WindowsAppSDK/assets/74490999/8072fdd9-c8e0-4300-b7b4-43af69d4a5f3)

Call Stack:
![CallStack](https://github.com/microsoft/WindowsAppSDK/assets/74490999/8f82e6d9-bdb8-4ba8-8c95-af7f77dc6b6c)

### Steps to reproduce the bug

1. Create a C++ WinUI3 project using "Blank App, Packaged (WinUI 3 in Desktop)" template.
2. Make it as unpackaged application using the steps described in the following link.
[https://learn.microsoft.com/en-us/windows/apps/winui/winui3/create-your-first-winui3-app#unpackaged-create-a-new-project-for-an-unpackaged-c-or-c-winui-3-desktop-app](url)
3. Add TabView controls to MainWindow.xaml
4. Build the application.
5. Run the application.
6. Interact with the TabView controls.
7. Close the application. 

### Expected behavior

Application should close without throwing any exception.

### NuGet package version

Windows App SDK 1.3.2: 1.3.230602002

### Packaging type

Unpackaged

### Windows version

Windows 10 version 22H2 (19045, 2022 Update)

### IDE

Visual Studio 2022

### Additional context

The exception is throwing only randomly. Can not be reproduced every time.
A test application is also attached.
[Tab_TestApp.zip](https://github.com/microsoft/WindowsAppSDK/files/11797047/Tab_TestApp.zip)

**Comment by ranjeshj** [comment]
@Ajith-GS this might already be fixed in WASDK 1.4. Can you please give it a try and report back ?

**Comment by Ajith-GS** [comment]
> @Ajith-GS this might already be fixed in WASDK 1.4. Can you please give it a try and report back ?

Thank you for your response, I will check and update.

**Comment by Ajith-GS** [comment]
This problem still exists in latest WASDK 1.5 (1.5.240607001).

**Comment by karkarl** [comment]
Sorry for the delayed response. Can you verify if the problem still persists in 1.6.
