### ISSUE TITLE
Build break when C++ Create and reference a WinUI 3 Component library using WinAppSDK 1.4.230913002

### ISSUE THREAD

**Issue by AnnYang01** [microsoft/microsoft-ui-xaml#8925]
### Describe the bug

Build break when C++ Create and reference a WinUI 3 Component library using WinAppSDK 1.4.230913002.
Severity	Code	Description	Project	File	Line	Suppression State	Details
```
Error	C2079	'winrt::impl::producer<D,winrt::Microsoft::UI::Xaml::Markup::IComponentConnector,void>::vtable' uses undefined struct 'winrt::impl::produce<D,I>'
        with
        [
            D=winrt::ThermometerWRC::implementation::UserControl
        ]	ThermometerWRC	C:\Users\xx\source\re\ThermometerWRC\ThermometerWRC\Generated Files\winrt\base.h	7001		
Error	C3083	'Foundation': the symbol to the left of a '::' must be a type	ThermometerWRC	C:\Users\xx\source\re\ThermometerWRC\ThermometerWRC\Generated Files\winrt\microsoft.ui.xaml.markup.h	1278		
Error	C2061	syntax error: identifier 'IInspectable'	ThermometerWRC	C:\Users\xx\source\re\ThermometerWRC\ThermometerWRC\Generated Files\winrt\microsoft.ui.xaml.markup.h	1278		
Error	C3083	'Foundation': the symbol to the left of a '::' must be a type	ThermometerWRC	C:\Users\xx\source\re\ThermometerWRC\ThermometerWRC\Generated Files\winrt\microsoft.ui.xaml.markup.h	1291		
Error	C2061	syntax error: identifier 'IInspectable'	ThermometerWRC	C:\Users\xx\source\re\ThermometerWRC\ThermometerWRC\Generated Files\winrt\microsoft.ui.xaml.markup.h	1291	
```	

### Steps to reproduce the bug

1.WinAppSdk 1.4.1 Insertion into VS [Pipelines - Run main-34126.236 (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_build/results?buildId=8454556&view=results)
 2.Create a C++ Blank App, Packaged (WinUI3 in Desktop)  project, and name it MyCppDesktopProject
3.Create a Windows Runtime Component (C++/WinRT) project, and name it ThermometerWRC

- Don't build the project yet.
- In Solution Explorer, rename "Class.idl" file to "Thermometer.idl". 
- Replace the contents of "Thermometer.idl" with the listing below:
- 
```

 // Thermometer.idl
 namespace ThermometerWRC
 {
     runtimeclass Thermometer
     {
         Thermometer();
         void AdjustTemperature(Single deltaFahrenheit);
     };
 }
```

- Save the file. Build the project.
- Right-click the project node and click "Open Folder in File Explorer".
- Copy the stub files "Thermometer.h" and "Thermometer.cpp" from the folder
- \ThermometerWRC\ThermometerWRC\Generated Files\sources\ and paste into the folder that contains your project files, which is \ThermometerWRC\ThermometerWRC\.(Replace the existing files) 
- Open "Thermometer.h" in VS, replace the content with below code:

 ```
// Thermometer.h
 #pragma once
 #include "Thermometer.g.h"
 namespace winrt::ThermometerWRC::implementation
 {
     struct Thermometer : ThermometerT<Thermometer>
     {
         Thermometer() = default;
 
         void AdjustTemperature(float deltaFahrenheit);
     private:
         float m_temperatureFahrenheit{ 0.f }; 
     };
 }
 namespace winrt::ThermometerWRC::factory_implementation
 {
     struct Thermometer :ThermometerT<Thermometer,implementation::Thermometer>
     {
     };
}
```

- Open "Thermometer.cpp" in VS, replace the content with below code: 

```
 // Thermometer.cpp
#include "pch.h"
#include "Thermometer.h"
#include "Thermometer.g.cpp"
 
namespace winrt::ThermometerWRC::implementation
{
    void Thermometer::AdjustTemperature(float deltaFahrenheit)
    {
        m_temperatureFahrenheit += deltaFahrenheit;
    }
}
```

-  Save and build the project.

4.Right click on the MyCppDesktopProject project node and select Add->Reference
5.Click the checkbox for ThermometerWRC and click OK. Your MyCppDesktopProject.vcxproj should have a reference to the ThermometerWRC.vcxproj file.
6.Right click on the ThermometerWRC project node and select Add-> New Item
7.Select User Control (WinUI 3) and press OK.
8.Build the solution. It won't successfully build but that's fine.
9.Replace the existing my_ButtonClick method in UserControl.xaml.cpp with the following

```
  void UserControl::myButton_Click(IInspectable const&, RoutedEventArgs const&)
    {
        myButton().Content(box_value(L"Clicked"));
        ThermometerWRC::Thermometer t;
        t.AdjustTemperature(20);
    }
```
10.In the pch.h file under the MyCppDesktopProject Node, add the following line:
`#include <winrt/ThermometerWRC.h>`
11.Build and Run the Solution (F5)

### Expected behavior

No errors.

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/5ff4611d-abea-4abf-9bc1-eff8bea04199)

### NuGet package version

WinUI 3 - Windows App SDK 1.4.1: 1.4.230913002

### Windows version

Windows 11 (22H2): Build 22621, Windows 10 (21H2): Build 19044

**Comment by AnnYang01** [comment]
Attach my repro project: \\ddfiles3\Team_XAML\User\v-annyang\ThermometerWRC.zip

**Comment by codendone** [comment]
This might be caused by an old version of the `Microsoft.Windows.CppWinRT` package. If your project is using a version from 2022 ("2.0.22*"), I think updating to a more recent version should fix this.

**Comment by ranjeshj** [comment]
@annyang01 Please reactivate if this still repros with latest version. Thanks!

**Comment by AnnYang01** [comment]
@ranjeshj @codendone  Only C2079 error still exist in Error List after updating the Microsoft.Windows.CppWinRT package to the latest version-2.0.230706.1, I don't have the permission to reactive this issue, please help me reactive it if necessary.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/8aaaeaeb-43ff-4b76-93f7-e677da430622)
C2079	'winrt::impl::producer::vtable' uses undefined struct 'winrt::impl::produce'
with
[
D=winrt::ThermometerWRC::implementation::UserControl
]

**Comment by codendone** [comment]
This remaining error sounds like you're missing a `#include <winrt/xxx.h>` for the relevant namespace header for that type.

**Comment by codendone** [comment]
Hopefully adding a missing `#include <winrt/xxx.h>` fixed your remaining issue. Re-closing this.

**Comment by AnnYang01** [comment]
@codendone Could you follow the repro steps and tell me where to insert the code to avoid C2079 error?
In the pch.h file under the MyCppDesktopProject Node, we have added the following line:` #include <winrt/ThermometerWRC.h>`, but C2079 error still exist.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/54223069-6fa6-4cd6-b613-bdf4fbedbd93)

**Comment by XamlTest** [comment]
@codendone We still failed with same errors on VS 17.9 Preview 3 with the original steps.

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/ac1a771d-c81a-4ade-b35e-b05c70cd2298)

After updating all packages to the latest version, errors still exist.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/e4e65719-c8fd-4820-84d3-268cf9be7143)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/97647558/39401eac-a8e8-477b-8d96-237b21fa7845)

**Comment by Scottj1s** [comment]
The direct cause of the build error is that UserControl.xaml.cpp is missing this:
   `#include <winrt/Microsoft.UI.Xaml.Markup.h>`
You can add that to either UserControl.xaml.cpp or pch.h to resolve the last build error.

However, you'll then have an issue with mismatched target platforms, since your app is Desktop Windows and your ThermometerWRC is Universal Windows.  That can be worked around by other means, but ultimately the best thing is to create your WRC project with the "Windows Runtime Component (WinUI3)" template, and not the "Windows Runtime Component (C++/WinRT)" template.  That would have avoided all of the preceding build errors and subsequent runtime errors.

**Comment by AnnYang01** [comment]
@Scottj1s  Thank you for your response and providing us with a workaround, but unfortunately it did not get rid of the C2079 error for me. please see the screenshot, could you have a look?
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/97f1c94e-6157-45ae-879a-734e1de5e637)
Thanks for reminding me to replace the WRC project with the Windows Runtime Component (WinUI3) template, but we have been testing this case against our FTE provided [WinUI BVTs - Overview (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_wiki/wikis/DevDiv.wiki/24416/WinUI-BVTs) and this case was passed in VS17.8P2-Windows App SDK 1.3.230602002 and earlier.
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/131441429/3cdc278b-b94b-41aa-be3a-b5bf642fd23b)
