### ISSUE TITLE
1.4.2 OverlappedPresenter IsMinimizable IsMaximizable bug

### ISSUE THREAD

**Issue by vash72** [microsoft/microsoft-ui-xaml#8996]
### Describe the bug

in version 1.3.2 (1.3.230724000) setting OverlappedPresenter.IsMaximizable works correctly, disabling the maximize caption button in the titlebar.
Instead in the 1.4.2 (1.4.231008000) it does not work as expected the maximize icon is colored as disabled but clicking it maximize the window

```
            AppWindow.TitleBar.ExtendsContentIntoTitleBar = true;
            if (AppWindow.Presenter is OverlappedPresenter overlappedPresenter)
            {
                overlappedPresenter.IsMinimizable = true;
                overlappedPresenter.IsMaximizable = false;
            }
```

### Steps to reproduce the bug

repro -> https://github.com/vash72/was-1.4-minimize-maximize-regression
first commit -> "version 1.3.2" use the version 1.3.2 and works as expected
second commit -> "version 1.4.2." use the version 1.4.2 have the regression

### Expected behavior

maximize button is disabled

### Screenshots

1.3.2 while hovering the maximize button (it is shown as disabled and clicking it produce non result as expected)
![immagine](https://github.com/microsoft/WindowsAppSDK/assets/40441234/65755292-f86b-43ba-bf3a-cc375f71a432)

1.4.2 while hovering the maximize button (it is shown as disabled but clicking it maximize the window)
![immagine](https://github.com/microsoft/WindowsAppSDK/assets/40441234/7890899c-9a49-44f5-8902-11751cce3ed8)

### NuGet package version

None

### Packaging type

Packaged (MSIX)

### Windows version

Windows 10 version 21H2 (19044, November 2021 Update)

**Comment by peterjtan** [comment]
Oh looks like the button is still hit-testable while the visual glyph is replaced with the disabled button one...

**Comment by duncanmacmichael** [comment]
Fixed in 1.4.3, closing issue.

**Comment by eduardobragaxz** [comment]
You can still double click the titlebar and the window will maximize. The pointer still changes when hovering the upper border too.

**Comment by dotMorten** [comment]
I see the same thing. @duncanmacmichael  Can we're open this since this is only partially fixed?

**Comment by duncanmacmichael** [comment]
@bpulliam Any input on this? We can reopen if necessary, definitely.

**Comment by wangqiang871104** [comment]
1.4.5 still has issue "You can still double click the titlebar and the window will maximize. The pointer still changes when hovering the upper border too."
