### ISSUE TITLE
Daily crashes of explorer.exe due to Windows.UI.Xaml.dll

### ISSUE THREAD

**Issue by Woovie** [microsoft/microsoft-ui-xaml#9330]
### Describe the bug

I have 5 crashes today already and I've used my computer for 2 hours. I suspect this is due to the new preview featured added to explorer in some update recently. I do not have proof of that, but everything was fine until that was added. I've disabled it for now so explorer won't lock up, but the crash continues to happen silently in the background.

```
Source
Windows Explorer

Summary
Stopped working

Date
‎2/‎11/‎2024 11:03 AM

Status
Report sent

Description
Faulting Application Path:	C:\Windows\explorer.exe

Problem signature
Problem Event Name:	APPCRASH
Application Name:	explorer.exe
Application Version:	10.0.22621.3007
Application Timestamp:	4421e92b
Fault Module Name:	Windows.UI.Xaml.dll
Fault Module Version:	10.0.22621.3007
Fault Module Timestamp:	b2ab1928
Exception Code:	c0000005
Exception Offset:	00000000003106af
OS Version:	10.0.22631.2.0.0.768.101
Locale ID:	1033
Additional Information 1:	26e5
Additional Information 2:	26e57f2d568bbced83b47a67c6777293
Additional Information 3:	cb57
Additional Information 4:	cb5745cc74d9ee7f93a607c23c1f5653

Extra information about the problem
Bucket ID:	009939d5addafeeff721eed07ae4d2cf (1666875916286218959)
```

### Steps to reproduce the bug

Unknown, started happening one day after clicking on a file from my Godot game project that was a binary _I think!_ and has not stopped since. I cannot replicate intentionally though unfortunately.

### Expected behavior

Not crashing

### Screenshots

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7304619/39f7f7ed-58c9-4407-bd06-173362b6cd5e)
![image](https://github.com/microsoft/microsoft-ui-xaml/assets/7304619/9f8fad44-c274-4eed-a548-6ae687a5fb43)

### NuGet package version

None

### Windows version

Windows 11 (23H2): Build 22631.3007

### Additional context

Edition	Windows 11 Home
Version	23H2
Installed on	‎12/‎29/‎2023
OS build	22631.3007
Experience	Windows Feature Experience Pack 1000.22681.1000.0

Device name	jbanasik-desktop
Processor	AMD Ryzen 7 5800X 8-Core Processor                4.20 GHz
Installed RAM	64.0 GB
Device ID	1A9D1AE4-AB9E-44B0-B1A5-D60789C9254B
Product ID	00326-10000-00000-AA106
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display

**Comment by Woovie** [comment]
> Hi I'm an AI powered bot that finds similar issues based off the issue title.
> 
> Please view the issues below to see if they solve your problem, and if the issue describes your problem please consider closing this one. Thank you!
> ### Closed similar issues:
> 
>     * [File Explorer crashes in Windows 11 upon right click Faulting module name: Windows.UI.Xaml.dll, version: 10.0.22000.348 (#6482)](https://github.com/microsoft/microsoft-ui-xaml/issues/6482),  similarity score: 0.79
> 
>     * [Windows.UI.Xaml.dll crash silently (ExceptionCode: c000027b) (#2820)](https://github.com/microsoft/microsoft-ui-xaml/issues/2820),  similarity score: 0.78
> 
>     * [Windows.UI.Xaml.dll crash at startup for all ms store apps (#1712)](https://github.com/microsoft/microsoft-ui-xaml/issues/1712),  similarity score: 0.76
> 
> 
> > Note: You can give me feedback by thumbs upping or thumbs downing this comment.

Checked these, while the issue is similar the crash is definitely different.

**Comment by codendone** [comment]
Thanks for providing those details. From looking at the "Bucket ID" of this access violation crash, it looks like you're hitting a bug ([internal bug reference](http://task.ms/48047295)) which should be fixed in this recent servicing update: [KB5034204](https://support.microsoft.com/en-us/topic/january-23-2024-kb5034204-os-builds-22621-3085-and-22631-3085-preview-7652acf2-56dc-430e-b8ef-ec8f56ec1028)

**Comment by Woovie** [comment]
Thanks so much for looking. I look forward to the patch!

**Comment by Joachim-Otahal** [comment]
Sadly still happens way too often. No change from 21H2, which I ran until April to 24H2, which I ran now. (I delayed upgrading 'cause shadowcopies for local drives were inaccessible/broken until April update)

![image](https://github.com/microsoft/microsoft-ui-xaml/assets/10100281/fdb4f812-d165-4aff-a9ec-96d9d51df83d)

```
- <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
- <System>
  <Provider Name="Application Error" Guid="{a0e9b465-b939-57d7-b27d-95d8e925ff57}" /> 
  <EventID>1000</EventID> 
  <Version>0</Version> 
  <Level>2</Level> 
  <Task>100</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-06-15T12:00:13.9363862Z" /> 
  <EventRecordID>11739</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="2612" ThreadID="7092" /> 
  <Channel>Application</Channel> 
  <Computer>PC-JOU</Computer> 
  <Security UserID="S-1-5-21-620362388-2233446311-3849218602-1001" /> 
  </System>
- <EventData>
  <Data Name="AppName">Explorer.EXE</Data> 
  <Data Name="AppVersion">10.0.22621.3733</Data> 
  <Data Name="AppTimeStamp">c47c2769</Data> 
  <Data Name="ModuleName">Windows.UI.Xaml.dll</Data> 
  <Data Name="ModuleVersion">10.0.22621.3672</Data> 
  <Data Name="ModuleTimeStamp">9db4ed3c</Data> 
  <Data Name="ExceptionCode">c000027b</Data> 
  <Data Name="FaultingOffset">0000000000871a80</Data> 
  <Data Name="ProcessId">0x2ab0</Data> 
  <Data Name="ProcessCreationTime">0x1dabce2f5e853f4</Data> 
  <Data Name="AppPath">C:\WINDOWS\Explorer.EXE</Data> 
  <Data Name="ModulePath">C:\Windows\System32\Windows.UI.Xaml.dll</Data> 
  <Data Name="IntegratorReportId">7f2f6771-208f-48bb-8188-7793eaff06b0</Data> 
  <Data Name="PackageFullName" /> 
  <Data Name="PackageRelativeAppId" /> 
  </EventData>
  </Event>
```

**Comment by oatkins** [comment]
I am seeing explorer.exe crash on startup, preventing startup processes from running.

This happened after before after a Windows update, maybe six months ago, and was eventually resolved by another Windows update. Now it's back. Removing the latest .NET update (KB5044091) resolves the problem temporarily, but the update gets auto-installed again and the problem returns. I've temporarily paused updated in the hope that a fix will get released soon.

My system is running Windows 10. (My AMD Threadripper CPU doesn't support Windows 11.)

I grabbed a dump of the crash. Here are some screenshots. I can provide the full crash dump privately if necessary.

![Image](https://github.com/user-attachments/assets/7bf31035-ee77-482a-95e1-5e4747db6bc0)

![Image](https://github.com/user-attachments/assets/eb1c1ff7-386b-44e9-8af0-7e749ac3a7ab)

It may be a total red herring, but my UI theme is set to Light, but that's not the theme that seems to be getting passed to `Initialize(ApplicationTheme theme)`.

**Comment by ascpixi** [comment]
Can report that I'm suffering daily crashes for about 6 months now. I hoped that a Windows update would fix the issue, but Explorer still crashes at seemingly random times.

**Comment by GJKrupa** [comment]
> I am seeing explorer.exe crash on startup, preventing startup processes from running.
> 
> This happened after before after a Windows update, maybe six months ago, and was eventually resolved by another Windows update. Now it's back. Removing the latest .NET update (KB5044091) resolves the problem temporarily, but the update gets auto-installed again and the problem returns. I've temporarily paused updated in the hope that a fix will get released soon.

Months later and I'm seeing the same still. Each Windows update seem to fix it for a short while but within 1-2 weeks it's back to this condition and I'm having to manually start all of my startup apps.

**Comment by jerrywoo96** [comment]
https://github.com/microsoft/microsoft-ui-xaml/issues/10897

I'm also having the same problem where explorer.exe crashes multiple times per hour, even on 26200.8524.

i thought it might be related as i've windbg'ed the dump file from the explorer.exe crash, and it showed me that it is related to the linked issue.

**Comment by jerrywoo96** [comment]
How i'd fixed my explorer.exe crashing. Can't guarantee it will work for the rest of you, since i'm running 2 monitors.
https://github.com/microsoft/microsoft-ui-xaml/issues/6482#issuecomment-5197803941
