### ISSUE TITLE
Dropdowns do not respond in WebView 2

### ISSUE THREAD

**Issue by alshival** [microsoft/microsoft-ui-xaml#9566]
### Describe the bug

Working on a [WinUI 3 project](https://github.com/alshival/UpWorker) with a web view to navigate a site. When a user tries to submit a job application through the app, they are unable to select from drop down selectors. 

Big bummer. I think it is related to [this issue](https://github.com/microsoft/microsoft-ui-xaml/issues/5570) that might have been solved at some point a few updates ago, though I am still seeing it occur in the latest version of SDK.

### Steps to reproduce the bug

1. Create WebView2 at [https://upwork.com](https://upwork.com).
2. Start an application to any job.
3. Click on a dropdown.

Site requires scripts, cookies, and basic tracking:
```
// WebView2 sender
sender.CoreWebView2.Profile.PreferredTrackingPreventionLevel = CoreWebView2TrackingPreventionLevel.Basic;
sender.CoreWebView2.Settings.IsScriptEnabled = true;
var cookieManager = sender.CoreWebView2.CookieManager;
var cookies = await cookieManager.GetCookiesAsync(null);
```

### Expected behavior

App makes selection.

### Screenshots

![Recording2024-04-21131104-ezgif com-video-to-gif-converter](https://github.com/microsoft/microsoft-ui-xaml/assets/129638420/af11027a-d26c-48dc-a30b-c9e254b28a2a)

### NuGet package version

WinUI 3 - Windows App SDK 1.5.2: 1.5.240404000

### Windows version

Windows 11 (22H2): Build 22621

**Comment by duncanmacmichael** [comment]
Fixed in 1.6-experiemntal1, closing issue.

**Comment by grabinat** [comment]
@duncanmacmichael 
I tested 1.6 experimental1 and the issue with the flyouts and context menus described in following issue still occur:
https://github.com/MicrosoftEdge/WebView2Feedback/issues/4140
Will this be addressed separately?

**Comment by duncanmacmichael** [comment]
> @duncanmacmichael I tested 1.6 experimental1 and the issue with the flyouts and context menus described in following issue still occur: [MicrosoftEdge/WebView2Feedback#4140](https://github.com/MicrosoftEdge/WebView2Feedback/issues/4140) Will this be addressed separately?

Thanks for checking on this! I believe the team is re-evaluating this bug, yes.

**Comment by codendone** [comment]
@grabinat We retested the specific repro steps of this issue in 1.6-experimental1 and see it as fixed. Is there something different about the scenario you're trying?

**Comment by codendone** [comment]
The fix is now also in [Version 1.5.4 (1.5.240607001)](https://learn.microsoft.com/windows/apps/windows-app-sdk/stable-channel#version-154-15240607001).

**Comment by grabinat** [comment]
> @grabinat We retested the specific repro steps of this issue in 1.6-experimental1 and see it as fixed. Is there something different about the scenario you're trying?

@codendone Sorry my bad – I just looked into it again. The project I used for testing, is packed by a separate Windows Application Packaged project. Even though, I did update the testing project to 1.6, I was not aware that the WAP was overriding it to 1.5. After adjusting the WAP it works now. Sorry for the trouble and thanks for the fix.
